import AppKit
import Foundation
import os

/// Cache cleaner service - performs cache scanning and cleaning in the background.
public final class CacheCleanerService: @unchecked Sendable {
    nonisolated static let logger = Logger(subsystem: "com.coffic.lumi", category: "cache-cleaner")
    public static let shared = CacheCleanerService()

    private let coordinator = CacheCleanerScanCoordinator()

    private init() {}

    struct CacheScanRule {
        let level: CacheCategory.SafetyLevel
        let id: String
        let name: String
        let desc: String
        let icon: String
        let paths: [String]
    }

    private var scanRules: [CacheScanRule] {
        let home = FileManager.default.homeDirectoryForCurrentUser.path
        return [
            .init(level: .safe, id: "user_app_cache", name: String(localized: "App Cache", bundle: .module), desc: String(localized: "Clear temporary files generated by applications", bundle: .module), icon: "app.badge", paths: ["\(home)/Library/Caches"]),
            .init(level: .safe, id: "browser_cache", name: String(localized: "Browser Cache", bundle: .module), desc: String(localized: "Clear Chrome, Safari, Firefox and other browser caches", bundle: .module), icon: "safari", paths: [
                "\(home)/Library/Caches/Google/Chrome",
                "\(home)/Library/Caches/com.apple.Safari",
                "\(home)/Library/Caches/Firefox",
            ]),
            .init(level: .safe, id: "dev_cache", name: String(localized: "Developer Tool Cache", bundle: .module), desc: String(localized: "Clear Xcode DerivedData, Archives, and package manager caches", bundle: .module), icon: "hammer", paths: [
                "\(home)/Library/Developer/Xcode/DerivedData",
                "\(home)/Library/Developer/Xcode/Archives",
                "\(home)/.npm/_cacache",
                "\(home)/.cargo/registry",
            ]),
            .init(level: .medium, id: "system_logs", name: String(localized: "System Logs", bundle: .module), desc: String(localized: "Clear system runtime log files", bundle: .module), icon: "doc.text", paths: [
                "\(home)/Library/Logs",
            ]),
            .init(level: .safe, id: "trash", name: String(localized: "Trash", bundle: .module), desc: String(localized: "Empty files in the trash", bundle: .module), icon: "trash", paths: [
                "\(home)/.Trash",
            ]),
        ]
    }

    // MARK: - Public API

    public func scanCaches() async -> [CacheCategory] {
        let results = await coordinator.scan(rules: scanRules)
        return results
    }

    public func progressStream() async -> AsyncStream<String> {
        await coordinator.progressStream()
    }

    public func cancelScan() async {
        await coordinator.cancelCurrentScan()
    }

    public func cleanup(paths: [CachePath]) async throws -> Int64 {
        let freedSpace = try await Task.detached(priority: .utility) {
            var total: Int64 = 0
            let fileManager = FileManager.default
            for item in paths {
                do {
                    try fileManager.removeItem(atPath: item.path)
                    total += item.size
                } catch {
                    throw CacheCleanupError(path: item.path, underlyingDescription: error.localizedDescription)
                }
            }
            return total
        }.value
        return freedSpace
    }

    fileprivate nonisolated static func scanCategory(rule: CacheScanRule) async -> CacheCategory? {
        var cachePaths: [CachePath] = []

        for path in rule.paths {
            if Task.isCancelled { return nil }
            if let info = await getPathInfo(path) {
                if path.hasSuffix("/Library/Caches") {
                    let subPaths = await scanSubDirectories(at: path)
                    cachePaths.append(contentsOf: subPaths)
                } else {
                    cachePaths.append(CachePath(
                        path: path,
                        name: URL(fileURLWithPath: path).lastPathComponent,
                        description: path,
                        size: info.size,
                        fileCount: info.count,
                        canDelete: true
                    ))
                }
            }
        }

        if cachePaths.isEmpty {
            return nil
        }

        return CacheCategory(
            id: rule.id,
            name: rule.name,
            description: rule.desc,
            icon: rule.icon,
            paths: cachePaths,
            safetyLevel: rule.level
        )
    }

    private nonisolated static func scanSubDirectories(at path: String) async -> [CachePath] {
        let url = URL(fileURLWithPath: path)
        var results: [CachePath] = []

        guard let contents = try? FileManager.default.contentsOfDirectory(at: url, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles]) else {
            return []
        }

        for content in contents {
            if Task.isCancelled { break }
            if let info = await getPathInfo(content.path), info.size > 0 {
                results.append(CachePath(
                    path: content.path,
                    name: content.lastPathComponent,
                    description: String(localized: "App Cache", bundle: .module),
                    size: info.size,
                    fileCount: info.count,
                    canDelete: true
                ))
            }
        }

        return results.sorted { $0.size > $1.size }
    }

    private nonisolated static func getPathInfo(_ path: String) async -> (size: Int64, count: Int)? {
        let fileManager = FileManager.default
        var isDir: ObjCBool = false

        guard fileManager.fileExists(atPath: path, isDirectory: &isDir) else {
            return nil
        }

        if !isDir.boolValue {
            if let attrs = try? fileManager.attributesOfItem(atPath: path),
               let size = attrs[.size] as? Int64 {
                return (size, 1)
            }
            return nil
        }

        return await Task.detached {
            var localSize: Int64 = 0
            var localCount = 0

            guard let enumerator = fileManager.enumerator(atPath: path) else { return nil }

            while let _ = enumerator.nextObject() {
                if Task.isCancelled { return nil }
                if let fileAttrs = enumerator.fileAttributes,
                   let fileSize = fileAttrs[.size] as? Int64 {
                    localSize += fileSize
                    localCount += 1
                }
            }
            return (localSize, localCount)
        }.value
    }
}

// MARK: - Scan Coordinator

actor CacheCleanerScanCoordinator {
    private var activeTask: Task<[CacheCategory], Never>?
    private var currentProgress: String? {
        didSet {
            if let p = currentProgress {
                for (_, cont) in progressContinuations { cont.yield(p) }
            }
        }
    }

    private var progressContinuations: [UUID: AsyncStream<String>.Continuation] = [:]
    private var terminatedIDs: Set<UUID> = []

    func progressStream() -> AsyncStream<String> {
        let id = UUID()
        return AsyncStream { continuation in
            Task { await self.registerContinuation(id: id, continuation: continuation) }
            continuation.onTermination = { _ in
                Task { await self.unregisterContinuation(id: id) }
            }
        }
    }

    private func registerContinuation(id: UUID, continuation: AsyncStream<String>.Continuation) async {
        addContinuation(id: id, continuation: continuation)
    }

    private func unregisterContinuation(id: UUID) async {
        removeContinuation(id: id)
    }

    private func addContinuation(id: UUID, continuation: AsyncStream<String>.Continuation) {
        if terminatedIDs.contains(id) { return }
        progressContinuations[id] = continuation
        if let p = currentProgress { continuation.yield(p) }
    }

    private func removeContinuation(id: UUID) {
        terminatedIDs.insert(id)
        progressContinuations[id] = nil
    }

    func scan(rules: [CacheCleanerService.CacheScanRule]) async -> [CacheCategory] {
        activeTask?.cancel()
        currentProgress = String(localized: "Starting scan...", bundle: .module)

        let task = Task { await performScan(rules: rules) }
        activeTask = task
        let result = await task.value

        currentProgress = nil
        finishAllStreams()
        return result
    }

    func cancelCurrentScan() {
        activeTask?.cancel()
        activeTask = nil
        currentProgress = nil
        finishAllStreams()
    }

    private func performScan(rules: [CacheCleanerService.CacheScanRule]) async -> [CacheCategory] {
        var categories: [CacheCategory] = []

        for rule in rules {
            if Task.isCancelled { break }
            currentProgress = rule.name
            if let category = await CacheCleanerService.scanCategory(rule: rule) {
                categories.append(category)
            }
        }

        return categories.sorted { $0.safetyLevel < $1.safetyLevel }
    }

    private func finishAllStreams() {
        for (_, cont) in progressContinuations { cont.finish() }
        progressContinuations.removeAll()
        terminatedIDs.removeAll()
    }
}
