// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "FactoryAppIconDesigner",
    defaultLocalization: "en",
    platforms: [.macOS(.v14), .iOS(.v17)],
    products: [
        .library(name: "FactoryAppIconDesigner", targets: ["FactoryAppIconDesigner"]),
    ],
    dependencies: [
        .package(url: "https://github.com/CofficLab/LumiThemePack.git", from: "1.0.4"),
        .package(url: "https://github.com/CofficLab/LumiKernel.git", branch: "main"),
        .package(path: "../KitLLM"),
        .package(url: "https://github.com/CofficLab/LumiLocalization.git", from: "1.0.0"),
        .package(url: "https://github.com/CofficLab/LumiUI.git", from: "1.7.0"),
        .package(path: "../PluginActivityBar"),
        .package(path: "../PluginAppIconDesigner"),
        .package(path: "../PluginCommand"),
        .package(path: "../PluginLogoCoffic"),
        .package(path: "../PluginLogoManager"),
        .package(path: "../PluginSettingGeneral"),
        .package(path: "../PluginSettingView"),
        .package(path: "../PluginStorage"),
        .package(path: "../PluginThemeManager"),
        .package(path: "../PluginThemePack"),
        .package(path: "../PluginToolManager"),
        .package(path: "../ProviderActivityBar"),
        .package(path: "../ProviderAgentLoop"),
        .package(path: "../ProviderChatSection"),
        .package(url: "https://github.com/CofficLab/LumiProviders.git", from: "1.2.7"),
        .package(path: "../ProviderConversation"),
        .package(path: "../ProviderLifecycleHooks"),
        .package(path: "../ProviderLLMManager"),
        .package(path: "../ProviderMessage"),
        .package(path: "../ProviderMessageStreaming"),
        .package(path: "../ProviderProject"),
        .package(path: "../ProviderPromptSuggestion"),
        .package(path: "../ProviderRootView"),
        .package(url: "https://github.com/CofficLab/LumiSettings.git", from: "1.0.1"),
        .package(path: "../ProviderToolManager"),
    ],
    targets: [
        .target(
            name: "FactoryAppIconDesigner",
            dependencies: [
                .product(name: "LumiThemePack", package: "LumiThemePack"),
                .product(name: "KernelCore", package: "LumiKernel"),
                .product(name: "KitLLM", package: "KitLLM"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalization"),
                .product(name: "LumiUI", package: "LumiUI"),
                .product(name: "PluginActivityBar", package: "PluginActivityBar"),
                .product(name: "PluginAppIconDesigner", package: "PluginAppIconDesigner"),
                .product(name: "PluginCommand", package: "PluginCommand"),
                .product(name: "PluginLogoCoffic", package: "PluginLogoCoffic"),
                .product(name: "PluginLogoManager", package: "PluginLogoManager"),
                .product(name: "PluginSettingGeneral", package: "PluginSettingGeneral"),
                .product(name: "PluginSettingView", package: "PluginSettingView"),
                .product(name: "PluginStorage", package: "PluginStorage"),
                .product(name: "PluginThemeManager", package: "PluginThemeManager"),
                .product(name: "PluginThemePack", package: "PluginThemePack"),
                .product(name: "PluginToolManager", package: "PluginToolManager"),
                .product(name: "ProviderActivityBar", package: "ProviderActivityBar"),
                .product(name: "ProviderAgentLoop", package: "ProviderAgentLoop"),
                .product(name: "ProviderChatSection", package: "ProviderChatSection"),
                .product(name: "ProviderCommand", package: "LumiProviders"),
                .product(name: "ProviderConversation", package: "ProviderConversation"),
                .product(name: "ProviderContentView", package: "LumiProviders"),
                .product(name: "ProviderDocsView", package: "LumiProviders"),
                .product(name: "ProviderLifecycleHooks", package: "ProviderLifecycleHooks"),
                .product(name: "ProviderLLMManager", package: "ProviderLLMManager"),
                .product(name: "ProviderMessage", package: "ProviderMessage"),
                .product(name: "ProviderMessageStreaming", package: "ProviderMessageStreaming"),
                .product(name: "ProviderProject", package: "ProviderProject"),
                .product(name: "ProviderPromptSuggestion", package: "ProviderPromptSuggestion"),
                .product(name: "ProviderRailView", package: "LumiProviders"),
                .product(name: "PluginRootView", package: "ProviderRootView"),
                .product(name: "ProviderRootView", package: "LumiProviders"),
                .product(name: "ProviderSettingView", package: "LumiSettings"),
                .product(name: "ProviderStorage", package: "LumiProviders"),
                .product(name: "ProviderTheme", package: "LumiProviders"),
                .product(name: "ProviderToolManager", package: "ProviderToolManager"),
                .product(name: "ProviderToolbar", package: "LumiProviders"),
            ]
        ),
        .testTarget(
            name: "FactoryAppIconDesignerTests",
            dependencies: ["FactoryAppIconDesigner"]
        ),
    ]
)
