import LumiUI
import SwiftUI

// MARK: - Manual View

/// 磁盘管理器使用手册 —— 模拟纸质说明书的章节式文档:
/// 编号章节、编号步骤、条目列表与线框示意图,克制严谨,不含宣传性内容。
/// 通过 `pluginManualView` 暴露,在 设置 → 通用 → 新手引导 → 说明书 中阅读。
struct DiskManagerManualView: View {
    @LumiTheme private var theme

    var body: some View {
        VStack(alignment: .leading, spacing: 22) {
            ManualHeader(
                title: L("Disk Manager"),
                subtitle: L("User Manual")
            )

            ManualSectionHeader(number: 1, title: L("Overview"))
            Text(L("This manual covers the interface and basic operations of the Disk Manager: viewing disk usage, scanning for large files and caches, and cleaning them."))
                .font(.appBody)
                .foregroundColor(theme.textPrimary)
                .fixedSize(horizontal: false, vertical: true)

            ManualSectionHeader(number: 2, title: L("Interface"))
            ManualBulletList(items: [
                .init(L("Cleanup sidebar: the category list, with a disk usage card above it showing the used and available space of the current disk.")),
                .init(L("Main area: shows the scan control, the scan progress, and the results list of the selected category.")),
                .init(L("Footer: shows the total size of the selected items and the clean action.")),
            ])
            interfaceFigure

            ManualSectionHeader(number: 3, title: L("Basic Operations"))
            ManualStepList(items: [
                .init(L("Select a category in the cleanup sidebar, such as Large Files or System Cleanup.")),
                .init(L("Click Start Scan and wait for the scan to finish; click Stop Scan to cancel at any time.")),
                .init(L("Review the results list and check the items you want to clean.")),
                .init(L("Check the total size in the footer and click Clean.")),
            ])

            ManualSectionHeader(number: 4, title: L("Cleanup Categories"))
            ManualBulletList(items: [
                .init(L("Large Files: finds the largest files on the disk and sorts them by size.")),
                .init(L("Directory Analysis: scans folder sizes to show how disk space is distributed.")),
                .init(L("System Cleanup: finds system and application caches that can be safely rebuilt.")),
                .init(L("Xcode Cleanup: clears build caches, archives, and simulator files generated by Xcode.")),
                .init(L("Project Cleanup: removes build products and cached dependencies in development projects.")),
            ])

            ManualSectionHeader(number: 5, title: L("Notes"))
            ManualBulletList(items: [
                .init(L("Confirm the selected items before cleaning; cleaned items cannot be restored.")),
                .init(L("System and Xcode caches can be rebuilt automatically, but files that are currently in use should not be deleted.")),
                .init(L("Xcode cleanup may require Full Disk Access; grant it in System Settings if prompted.")),
            ])
        }
        .frame(maxWidth: 620, alignment: .leading)
    }

    // MARK: - 图 1 界面布局

    private var interfaceFigure: some View {
        ManualFigure(caption: L("Figure 1: Interface layout")) {
            VStack(spacing: 12) {
                HStack(spacing: 0) {
                    // ① 清理侧边栏:磁盘用量卡 + 分类列表示意
                    VStack(alignment: .leading, spacing: 7) {
                        groupLabel(L("Disk Cleanup"))
                        usageRingMock()
                        Divider()
                        categoryRowMock()
                        categoryRowMock(selected: true)
                        categoryRowMock()
                        Spacer(minLength: 0)
                    }
                    .padding(10)
                    .frame(width: 122, height: 172, alignment: .topLeading)
                    .overlay(alignment: .topLeading) { ManualFigureMarker(1).padding(-7) }

                    Divider()

                    // 主区域:② 扫描控制 + 结果列表,③ 底部合计与清理
                    VStack(spacing: 0) {
                        VStack(spacing: 10) {
                            HStack(spacing: 6) {
                                toolbarPill("magnifyingglass")
                                progressBarMock(width: 58)
                                Spacer(minLength: 0)
                            }
                            .overlay(alignment: .top) { ManualFigureMarker(2).offset(y: -9) }

                            resultRowMock()
                            resultRowMock()
                            resultRowMock()
                            Spacer(minLength: 0)
                        }
                        .padding(10)

                        Divider()

                        HStack(spacing: 6) {
                            lineMock(width: 40)
                            Spacer(minLength: 0)
                            toolbarPill("trash")
                        }
                        .padding(.horizontal, 10)
                        .padding(.vertical, 8)
                        .overlay(alignment: .bottomLeading) { ManualFigureMarker(3).offset(y: 9) }
                    }
                    .frame(maxWidth: .infinity)
                    .frame(height: 172)
                }

                HStack(spacing: 16) {
                    ManualFigureLegendItem(1, L("Cleanup sidebar"))
                    ManualFigureLegendItem(2, L("Main area"))
                    ManualFigureLegendItem(3, L("Footer"))
                }
            }
        }
    }

    // MARK: - 示意简笔元素

    /// 侧边栏分组小标题。
    private func groupLabel(_ text: String) -> some View {
        Text(text)
            .font(.system(size: 8, weight: .semibold))
            .foregroundColor(theme.textSecondary)
    }

    /// 磁盘用量卡示意:用量环 + 两根文字线。
    private func usageRingMock() -> some View {
        HStack(spacing: 8) {
            ZStack {
                Circle()
                    .stroke(theme.appDivider, lineWidth: 3)
                Circle()
                    .trim(from: 0, to: 0.68)
                    .stroke(theme.primary.opacity(0.75), style: StrokeStyle(lineWidth: 3, lineCap: .round))
                    .rotationEffect(.degrees(-90))
            }
            .frame(width: 26, height: 26)

            VStack(alignment: .leading, spacing: 3) {
                lineMock(width: 44)
                lineMock(width: 30)
            }
        }
        .padding(6)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 6, style: .continuous)
                .strokeBorder(theme.appDivider)
        )
    }

    /// 分类行示意:图标 + 一根文字线,选中时带勾选标记。
    private func categoryRowMock(selected: Bool = false) -> some View {
        HStack(spacing: 6) {
            Image(systemName: "doc")
                .font(.system(size: 8))
                .foregroundStyle(theme.textSecondary)
                .frame(width: 14, height: 14)
            lineMock(width: 48)
            Spacer(minLength: 0)
            if selected {
                Image(systemName: "checkmark")
                    .font(.system(size: 7))
                    .foregroundStyle(theme.primary)
            }
        }
        .padding(.vertical, 3)
        .padding(.horizontal, 5)
        .background(
            RoundedRectangle(cornerRadius: 5, style: .continuous)
                .fill(selected ? Color.primary.opacity(0.08) : Color.clear)
        )
    }

    /// 扫描结果行示意:勾选框 + 两根文字线 + 尺寸。
    private func resultRowMock() -> some View {
        HStack(spacing: 6) {
            RoundedRectangle(cornerRadius: 2)
                .strokeBorder(theme.appDivider)
                .frame(width: 9, height: 9)
            VStack(alignment: .leading, spacing: 3) {
                lineMock(width: 88)
                lineMock(width: 56)
            }
            Spacer(minLength: 0)
            lineMock(width: 22)
        }
        .padding(5)
        .background(
            RoundedRectangle(cornerRadius: 6, style: .continuous)
                .fill(Color.primary.opacity(0.04))
        )
    }

    /// 工具栏按钮示意。
    private func toolbarPill(_ systemImage: String) -> some View {
        Image(systemName: systemImage)
            .font(.system(size: 9))
            .foregroundStyle(theme.textSecondary)
            .padding(.horizontal, 8)
            .padding(.vertical, 5)
            .background(
                RoundedRectangle(cornerRadius: 6, style: .continuous)
                    .strokeBorder(theme.appDivider)
            )
    }

    /// 扫描进度条示意。
    private func progressBarMock(width: CGFloat) -> some View {
        ZStack(alignment: .leading) {
            RoundedRectangle(cornerRadius: 2)
                .fill(Color.primary.opacity(0.08))
            RoundedRectangle(cornerRadius: 2)
                .fill(theme.primary.opacity(0.6))
                .frame(width: width * 0.55)
        }
        .frame(width: width, height: 5)
    }

    /// 示意图中的占位文字线。
    private func lineMock(width: CGFloat) -> some View {
        RoundedRectangle(cornerRadius: 1)
            .fill(Color.primary.opacity(0.14))
            .frame(width: width, height: 3)
    }

    // MARK: - Localization

    private func L(_ key: String) -> String {
        PluginDiskManagerLocalization.string(key)
    }
}

#if DEBUG
#Preview {
    ScrollView {
        DiskManagerManualView()
            .padding(22)
    }
    .frame(width: 560, height: 900)
}
#endif
