// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "FactoryLumiACP",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "FactoryLumiACP", targets: ["FactoryLumiACP"]),
        .executable(name: "LumiACPExecutable", targets: ["LumiACPExecutable"]),
    ],
    dependencies: [
        .package(path: "../KernelCore"),
        .package(path: "../KitLLM"),
        .package(path: "../ProviderActivityBar"),
        .package(path: "../ProviderAgentLoop"),
        .package(path: "../ProviderChatSection"),
        .package(path: "../ProviderCommand"),
        .package(path: "../ProviderContentView"),
        .package(path: "../ProviderConversation"),
        .package(path: "../ProviderConversationInput"),
        .package(path: "../ProviderDocsView"),
        .package(path: "../ProviderExternalFile"),
        .package(path: "../ProviderIdleTime"),
        .package(path: "../ProviderLegacyData"),
        .package(path: "../ProviderLifecycleHooks"),
        .package(path: "../ProviderLLMContext"),
        .package(path: "../ProviderLLMManager"),
        .package(path: "../ProviderLogo"),
        .package(path: "../ProviderMenuBar"),
        .package(path: "../ProviderMessage"),
        .package(path: "../ProviderMessageRendering"),
        .package(path: "../ProviderMessageSender"),
        .package(path: "../ProviderMessageStreaming"),
        .package(path: "../ProviderNetwork"),
        .package(path: "../ProviderPluginControl"),
        .package(path: "../ProviderPluginManaging"),
        .package(path: "../ProviderPromptSuggestion"),
        .package(path: "../ProviderProject"),
        .package(path: "../ProviderRailView"),
        .package(path: "../ProviderRootView"),
        .package(path: "../ProviderSettingView"),
        .package(path: "../ProviderSkill"),
        .package(path: "../ProviderAgentRules"),
        .package(path: "../ProviderStorage"),
        .package(path: "../ProviderToast"),
        .package(path: "../ProviderToolManager"),
        .package(path: "../ProviderToolbar"),
        .package(path: "../ProviderWebServer"),
        .package(path: "../ProviderDeveloperMode"),
        .package(path: "../ProviderACP"),
        .package(path: "../PluginACP"),
        .package(path: "../PluginStorage"),
        .package(path: "../PluginCommand"),
        .package(path: "../PluginToast"),
        .package(path: "../PluginLLMManager"),
        .package(path: "../PluginToolManager"),
        .package(path: "../PluginAgentLoop"),
        .package(path: "../PluginAgentLoopRetry"),
        .package(path: "../PluginMessageSender"),
        .package(path: "../PluginConversationManager"),
        .package(path: "../PluginMessageManager"),
        .package(path: "../PluginLLMContext"),
        .package(path: "../PluginConversationState"),
        .package(path: "../PluginConversationPendingMessage"),
        .package(path: "../PluginConversationTitle"),
        .package(path: "../PluginAskUser"),
        .package(path: "../PluginAgentRules"),
        .package(path: "../PluginAgentTempStorage"),
        .package(path: "../PluginAgentPlanStorage"),
        .package(path: "../PluginFileLog"),
        .package(path: "../PluginSkill"),
        .package(path: "../PluginPluginManager"),
        .package(path: "../PluginLLMProviderSettings"),
        .package(path: "../PluginModelSelector"),
        .package(path: "../PluginMCP"),
        .package(path: "../PluginWebFetch"),
        .package(path: "../PluginWebSearch"),
        .package(path: "../PluginDocxRead"),
        .package(path: "../PluginTerminal"),
        .package(path: "../PluginLLMProviderAiRouter"),
        .package(path: "../PluginLLMProviderAliyun"),
        .package(path: "../PluginLLMProviderAnthropic"),
        .package(path: "../PluginLLMProviderDeepSeek"),
        .package(path: "../PluginLLMProviderFeifeimiao"),
        .package(path: "../PluginLLMProviderFlyMux"),
        .package(path: "../PluginLLMProviderHappyCode"),
        .package(path: "../PluginLLMProviderHyperAPI"),
        .package(path: "../PluginLLMProviderKimiCode"),
        .package(path: "../PluginLLMProviderLPgpt"),
        .package(path: "../PluginLLMProviderMegaLLM"),
        .package(path: "../PluginLLMProviderMiniMax"),
        .package(path: "../PluginLLMProviderOpenAI"),
        .package(path: "../PluginLLMProviderOpenCode"),
        .package(path: "../PluginLLMProviderCommandCode"),
        .package(path: "../PluginLLMProviderOpenRouter"),
        .package(path: "../PluginLLMProviderStepFun"),
        .package(path: "../PluginLLMProviderSublyx"),
        .package(path: "../PluginLLMProviderTencent"),
        .package(path: "../PluginLLMProviderXiaomi"),
        .package(path: "../PluginLLMProviderXybbz"),
        .package(path: "../PluginLLMProviderZhipu"),
        .package(path: "../PluginLLMProviderCodex"),
        .package(path: "../PluginLLMProviderMLX"),
    ],
    targets: [
        .target(
            name: "FactoryLumiACP",
            dependencies: [
                .product(name: "KernelCore", package: "KernelCore"),
                .product(name: "KitLLM", package: "KitLLM"),
                .product(name: "ProviderActivityBar", package: "ProviderActivityBar"),
                .product(name: "ProviderAgentLoop", package: "ProviderAgentLoop"),
                .product(name: "ProviderChatSection", package: "ProviderChatSection"),
                .product(name: "ProviderCommand", package: "ProviderCommand"),
                .product(name: "ProviderContentView", package: "ProviderContentView"),
                .product(name: "ProviderConversation", package: "ProviderConversation"),
                .product(name: "ProviderConversationInput", package: "ProviderConversationInput"),
                .product(name: "ProviderDocsView", package: "ProviderDocsView"),
                .product(name: "ProviderExternalFile", package: "ProviderExternalFile"),
                .product(name: "ProviderIdleTime", package: "ProviderIdleTime"),
                .product(name: "ProviderLegacyData", package: "ProviderLegacyData"),
                .product(name: "ProviderLifecycleHooks", package: "ProviderLifecycleHooks"),
                .product(name: "ProviderLLMContext", package: "ProviderLLMContext"),
                .product(name: "ProviderLLMManager", package: "ProviderLLMManager"),
                .product(name: "ProviderLogo", package: "ProviderLogo"),
                .product(name: "ProviderMenuBar", package: "ProviderMenuBar"),
                .product(name: "ProviderMessage", package: "ProviderMessage"),
                .product(name: "ProviderMessageRendering", package: "ProviderMessageRendering"),
                .product(name: "ProviderMessageSender", package: "ProviderMessageSender"),
                .product(name: "ProviderMessageStreaming", package: "ProviderMessageStreaming"),
                .product(name: "ProviderNetwork", package: "ProviderNetwork"),
                .product(name: "ProviderPluginControl", package: "ProviderPluginControl"),
                .product(name: "ProviderPluginManaging", package: "ProviderPluginManaging"),
                .product(name: "ProviderPromptSuggestion", package: "ProviderPromptSuggestion"),
                .product(name: "ProviderProject", package: "ProviderProject"),
                .product(name: "ProviderRailView", package: "ProviderRailView"),
                .product(name: "ProviderRootView", package: "ProviderRootView"),
                .product(name: "ProviderSettingView", package: "ProviderSettingView"),
                .product(name: "ProviderSkill", package: "ProviderSkill"),
                .product(name: "ProviderAgentRules", package: "ProviderAgentRules"),
                .product(name: "ProviderStorage", package: "ProviderStorage"),
                .product(name: "ProviderToast", package: "ProviderToast"),
                .product(name: "ProviderToolManager", package: "ProviderToolManager"),
                .product(name: "ProviderToolbar", package: "ProviderToolbar"),
                .product(name: "ProviderWebServer", package: "ProviderWebServer"),
                .product(name: "ProviderDeveloperMode", package: "ProviderDeveloperMode"),
                .product(name: "ProviderACP", package: "ProviderACP"),
                .product(name: "PluginACP", package: "PluginACP"),
                .product(name: "PluginStorage", package: "PluginStorage"),
                .product(name: "PluginCommand", package: "PluginCommand"),
                .product(name: "PluginToast", package: "PluginToast"),
                .product(name: "PluginLLMManager", package: "PluginLLMManager"),
                .product(name: "PluginToolManager", package: "PluginToolManager"),
                .product(name: "PluginAgentLoop", package: "PluginAgentLoop"),
                .product(name: "PluginAgentLoopRetry", package: "PluginAgentLoopRetry"),
                .product(name: "PluginMessageSender", package: "PluginMessageSender"),
                .product(name: "PluginConversationManager", package: "PluginConversationManager"),
                .product(name: "PluginMessageManager", package: "PluginMessageManager"),
                .product(name: "PluginLLMContext", package: "PluginLLMContext"),
                .product(name: "PluginConversationState", package: "PluginConversationState"),
                .product(name: "PluginConversationPendingMessage", package: "PluginConversationPendingMessage"),
                .product(name: "PluginConversationTitle", package: "PluginConversationTitle"),
                .product(name: "PluginAskUser", package: "PluginAskUser"),
                .product(name: "PluginAgentRules", package: "PluginAgentRules"),
                .product(name: "PluginAgentTempStorage", package: "PluginAgentTempStorage"),
                .product(name: "PluginAgentPlanStorage", package: "PluginAgentPlanStorage"),
                .product(name: "PluginFileLog", package: "PluginFileLog"),
                .product(name: "PluginSkill", package: "PluginSkill"),
                .product(name: "PluginPluginManager", package: "PluginPluginManager"),
                .product(name: "PluginLLMProviderSettings", package: "PluginLLMProviderSettings"),
                .product(name: "PluginModelSelector", package: "PluginModelSelector"),
                .product(name: "PluginMCP", package: "PluginMCP"),
                .product(name: "PluginWebFetch", package: "PluginWebFetch"),
                .product(name: "PluginWebSearch", package: "PluginWebSearch"),
                .product(name: "PluginDocxRead", package: "PluginDocxRead"),
                .product(name: "PluginTerminal", package: "PluginTerminal"),
                .product(name: "PluginLLMProviderAiRouter", package: "PluginLLMProviderAiRouter"),
                .product(name: "PluginLLMProviderAliyun", package: "PluginLLMProviderAliyun"),
                .product(name: "PluginLLMProviderAnthropic", package: "PluginLLMProviderAnthropic"),
                .product(name: "PluginLLMProviderDeepSeek", package: "PluginLLMProviderDeepSeek"),
                .product(name: "PluginLLMProviderFeifeimiao", package: "PluginLLMProviderFeifeimiao"),
                .product(name: "PluginLLMProviderFlyMux", package: "PluginLLMProviderFlyMux"),
                .product(name: "PluginLLMProviderHappyCode", package: "PluginLLMProviderHappyCode"),
                .product(name: "PluginLLMProviderHyperAPI", package: "PluginLLMProviderHyperAPI"),
                .product(name: "PluginLLMProviderKimiCode", package: "PluginLLMProviderKimiCode"),
                .product(name: "PluginLLMProviderLPgpt", package: "PluginLLMProviderLPgpt"),
                .product(name: "PluginLLMProviderMegaLLM", package: "PluginLLMProviderMegaLLM"),
                .product(name: "PluginLLMProviderMiniMax", package: "PluginLLMProviderMiniMax"),
                .product(name: "PluginLLMProviderOpenAI", package: "PluginLLMProviderOpenAI"),
                .product(name: "PluginLLMProviderOpenCode", package: "PluginLLMProviderOpenCode"),
                .product(name: "PluginLLMProviderCommandCode", package: "PluginLLMProviderCommandCode"),
                .product(name: "PluginLLMProviderOpenRouter", package: "PluginLLMProviderOpenRouter"),
                .product(name: "PluginLLMProviderStepFun", package: "PluginLLMProviderStepFun"),
                .product(name: "PluginLLMProviderSublyx", package: "PluginLLMProviderSublyx"),
                .product(name: "PluginLLMProviderTencent", package: "PluginLLMProviderTencent"),
                .product(name: "PluginLLMProviderXiaomi", package: "PluginLLMProviderXiaomi"),
                .product(name: "PluginLLMProviderXybbz", package: "PluginLLMProviderXybbz"),
                .product(name: "PluginLLMProviderZhipu", package: "PluginLLMProviderZhipu"),
                .product(name: "PluginLLMProviderCodex", package: "PluginLLMProviderCodex"),
                .product(name: "PluginLLMProviderMLX", package: "PluginLLMProviderMLX"),
            ],
            path: "Sources/FactoryLumiACP"
        ),
        .executableTarget(
            name: "LumiACPExecutable",
            dependencies: ["FactoryLumiACP"],
            path: "Sources/LumiACPExecutable"
        ),
    ]
)
