import Foundation
import AppKit
import OSLog
import MagicKit

@MainActor
class CacheCleanerService: ObservableObject, SuperLog {
    static let shared = CacheCleanerService()

    @Published var categories: [CacheCategory] = []
    @Published var isScanning = false
    @Published var scanProgress: String = ""

    private struct CacheScanRule {
        let level: CacheCategory.SafetyLevel
        let id: String
        let name: String
        let desc: String
        let icon: String
        let paths: [String]
    }

    // MARK: - Predefined scan rules
    
    // Use closure to delay path retrieval (because homeDirectory might change, although unlikely)
    private var scanRules: [CacheScanRule] {
        let home = FileManager.default.homeDirectoryForCurrentUser.path
        return [
            // level, id, name, desc, icon, paths
            .init(level: .safe, id: "user_app_cache", name: String(localized: "App Cache"), desc: String(localized: "Clear temporary files generated by applications"), icon: "app.badge", paths: ["\(home)/Library/Caches"]),
            .init(level: .safe, id: "browser_cache", name: String(localized: "Browser Cache"), desc: String(localized: "Clear Chrome, Safari, Firefox and other browser caches"), icon: "safari", paths: [
                "\(home)/Library/Caches/Google/Chrome",
                "\(home)/Library/Caches/com.apple.Safari",
                "\(home)/Library/Caches/Firefox"
            ]),
            .init(level: .safe, id: "dev_cache", name: String(localized: "Developer Tool Cache"), desc: String(localized: "Clear Xcode DerivedData, Archives, and package manager caches"), icon: "hammer", paths: [
                "\(home)/Library/Developer/Xcode/DerivedData",
                "\(home)/Library/Developer/Xcode/Archives",
                "\(home)/.npm/_cacache",
                "\(home)/.cargo/registry"
            ]),
            .init(level: .medium, id: "system_logs", name: String(localized: "System Logs"), desc: String(localized: "Clear system runtime log files"), icon: "doc.text", paths: [
                "\(home)/Library/Logs"
            ]),
            .init(level: .safe, id: "trash", name: String(localized: "Trash"), desc: String(localized: "Empty files in the trash"), icon: "trash", paths: [
                "\(home)/.Trash"
            ])
        ]
    }

    // MARK: - Public API

    func scanCaches() async {
        isScanning = true
        scanProgress = String(localized: "Initializing...")

        let rules = scanRules
        let results = await withTaskGroup(of: CacheCategory?.self, returning: [CacheCategory].self) { group in
            for rule in rules {
                group.addTask(priority: .utility) {
                    await Self.scanCategory(rule: rule)
                }
            }

            var categories: [CacheCategory] = []
            for await category in group {
                if let category {
                    categories.append(category)
                }
            }
            return categories
        }

        categories = results.sorted { $0.safetyLevel < $1.safetyLevel }
        isScanning = false
        scanProgress = ""
    }
    
    func cleanup(paths: [CachePath]) async throws -> Int64 {
        let freedSpace = await Task.detached(priority: .utility) {
            var total: Int64 = 0
            let fileManager = FileManager.default
            for item in paths {
                do {
                    try fileManager.removeItem(atPath: item.path)
                    total += item.size
                } catch {
                    os_log(.error, "\(Self.t)Cleanup failed: \(item.path) - \(error.localizedDescription)")
                }
            }
            return total
        }.value

        // Rescan to update status
        await scanCaches()
        return freedSpace
    }

    // MARK: - Private Implementation
    
    nonisolated private static func scanCategory(rule: CacheScanRule) async -> CacheCategory? {
        var cachePaths: [CachePath] = []

        for path in rule.paths {
            if let info = await getPathInfo(path) {
                // Special handling: if it's ~/Library/Caches, we don't want to delete the entire folder, but list subfolders
                if path.hasSuffix("/Library/Caches") {
                    let subPaths = await scanSubDirectories(at: path)
                    cachePaths.append(contentsOf: subPaths)
                } else {
                    cachePaths.append(CachePath(
                        path: path,
                        name: URL(fileURLWithPath: path).lastPathComponent,
                        description: path,
                        size: info.size,
                        fileCount: info.count,
                        canDelete: true
                    ))
                }
            }
        }
        
        if cachePaths.isEmpty {
            return nil
        }

        return CacheCategory(
            id: rule.id,
            name: rule.name,
            description: rule.desc,
            icon: rule.icon,
            paths: cachePaths,
            safetyLevel: rule.level
        )
    }
    
    nonisolated private static func scanSubDirectories(at path: String) async -> [CachePath] {
        let url = URL(fileURLWithPath: path)
        var results: [CachePath] = []
        
        guard let contents = try? FileManager.default.contentsOfDirectory(at: url, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles]) else {
            return []
        }
        
        for content in contents {
            if let info = await getPathInfo(content.path), info.size > 0 {
                results.append(CachePath(
                    path: content.path,
                    name: content.lastPathComponent,
                    description: String(localized: "App Cache"),
                    size: info.size,
                    fileCount: info.count,
                    canDelete: true
                ))
            }
        }
        
        return results.sorted { $0.size > $1.size }
    }
    
    nonisolated private static func getPathInfo(_ path: String) async -> (size: Int64, count: Int)? {
        let fileManager = FileManager.default
        var isDir: ObjCBool = false
        
        guard fileManager.fileExists(atPath: path, isDirectory: &isDir) else {
            return nil
        }
        
        if !isDir.boolValue {
            // Single file
            if let attrs = try? fileManager.attributesOfItem(atPath: path),
               let size = attrs[.size] as? Int64 {
                return (size, 1)
            }
            return nil
        }
        
        // Directory: recursively calculate size
        // For performance, we don't use DiskService's full scan here, but a quick traversal
        // Or reuse DiskService.scan but don't build a tree?
        // For simplicity, use Enumerator
        
        return await Task.detached {
            var localSize: Int64 = 0
            var localCount = 0
            
            guard let enumerator = fileManager.enumerator(atPath: path) else { return nil }
            
            // FileManager.DirectoryEnumerator is not thread-safe and not Sendable,
            // but we are inside a detached Task with a local instance created on that thread (if fileManager is thread safe).
            // Actually FileManager.default is thread-safe.
            // However, makeIterator() availability in async context is the issue.
            // We can iterate using while loop with nextObject() which is the ObjC way and avoids Sequence conformance issues in async
            
            while let _ = enumerator.nextObject() {
                if let fileAttrs = enumerator.fileAttributes,
                   let fileSize = fileAttrs[.size] as? Int64 {
                    localSize += fileSize
                    localCount += 1
                }
            }
            return (localSize, localCount)
        }.value
    }
}
