import AppKit
import Foundation
import MagicKit
import OSLog

@MainActor
class CacheCleanerService: ObservableObject, SuperLog {
    nonisolated static let emoji = "🗑️"
    nonisolated static let verbose = true
    static let shared = CacheCleanerService()

    @Published var categories: [CacheCategory] = []
    @Published var isScanning = false
    @Published var scanProgress: String = ""

    private struct CacheScanRule {
        let level: CacheCategory.SafetyLevel
        let id: String
        let name: String
        let desc: String
        let icon: String
        let paths: [String]
    }

    // MARK: - 预定义扫描规则

    // 使用计算属性延迟获取路径（因为 homeDirectory 可能会变化，虽然不太可能）
    private var scanRules: [CacheScanRule] {
        let home = FileManager.default.homeDirectoryForCurrentUser.path
        return [
            // level, id, name, desc, icon, paths
            .init(level: .safe, id: "user_app_cache", name: String(localized: "App Cache"), desc: String(localized: "Clear temporary files generated by applications"), icon: "app.badge", paths: ["\(home)/Library/Caches"]),
            .init(level: .safe, id: "browser_cache", name: String(localized: "Browser Cache"), desc: String(localized: "Clear Chrome, Safari, Firefox and other browser caches"), icon: "safari", paths: [
                "\(home)/Library/Caches/Google/Chrome",
                "\(home)/Library/Caches/com.apple.Safari",
                "\(home)/Library/Caches/Firefox",
            ]),
            .init(level: .safe, id: "dev_cache", name: String(localized: "Developer Tool Cache"), desc: String(localized: "Clear Xcode DerivedData, Archives, and package manager caches"), icon: "hammer", paths: [
                "\(home)/Library/Developer/Xcode/DerivedData",
                "\(home)/Library/Developer/Xcode/Archives",
                "\(home)/.npm/_cacache",
                "\(home)/.cargo/registry",
            ]),
            .init(level: .medium, id: "system_logs", name: String(localized: "System Logs"), desc: String(localized: "Clear system runtime log files"), icon: "doc.text", paths: [
                "\(home)/Library/Logs",
            ]),
            .init(level: .safe, id: "trash", name: String(localized: "Trash"), desc: String(localized: "Empty files in the trash"), icon: "trash", paths: [
                "\(home)/.Trash",
            ]),
        ]
    }

    // MARK: - 公开 API

    func scanCaches() async {
        isScanning = true
        scanProgress = String(localized: "Initializing...")

        // 在后台执行扫描操作
        let rules = scanRules
        let results = await Task.detached(priority: .utility) {
            if Self.verbose {
                os_log("\(self.t)开始扫描缓存分类")
            }
            return await withTaskGroup(of: CacheCategory?.self, returning: [CacheCategory].self) { group in
                for rule in rules {
                    group.addTask(priority: .utility) {
                        await Self.scanCategory(rule: rule)
                    }
                }

                var categories: [CacheCategory] = []
                for await category in group {
                    if let category {
                        categories.append(category)
                    }
                }
                return categories.sorted { $0.safetyLevel < $1.safetyLevel }
            }
        }.value

        // 更新 UI 状态
        await MainActor.run {
            self.categories = results
            self.isScanning = false
            self.scanProgress = ""
        }

        if Self.verbose {
            os_log("\(self.t)缓存扫描完成：\(self.categories.count) 个分类")
        }
    }

    func cleanup(paths: [CachePath]) async throws -> Int64 {
        if Self.verbose {
            os_log("\(self.t)开始清理 \(paths.count) 个缓存路径")
        }

        let freedSpace = await Task.detached(priority: .utility) {
            var total: Int64 = 0
            let fileManager = FileManager.default
            for item in paths {
                do {
                    try fileManager.removeItem(atPath: item.path)
                    total += item.size
                } catch {
                    os_log(.error, "\(Self.t)清理失败：\(item.path) - \(error.localizedDescription)")
                }
            }
            return total
        }.value

        if Self.verbose {
            os_log("\(self.t)清理完成，释放 \(ByteCountFormatter.string(fromByteCount: freedSpace, countStyle: .file))")
        }

        // 在后台重新扫描以更新状态
        await Task.detached(priority: .utility) {
            await self.scanCaches()
        }.value

        return freedSpace
    }

    // MARK: - 私有实现

    private nonisolated static func scanCategory(rule: CacheScanRule) async -> CacheCategory? {
        if Self.verbose {
            os_log("\(self.t)开始扫描分类：\(rule.name)")
        }
        var cachePaths: [CachePath] = []

        for path in rule.paths {
            if let info = await getPathInfo(path) {
                // 特殊处理：如果是 ~/Library/Caches，不删除整个文件夹，而是列出子文件夹
                if path.hasSuffix("/Library/Caches") {
                    let subPaths = await scanSubDirectories(at: path)
                    cachePaths.append(contentsOf: subPaths)
                } else {
                    cachePaths.append(CachePath(
                        path: path,
                        name: URL(fileURLWithPath: path).lastPathComponent,
                        description: path,
                        size: info.size,
                        fileCount: info.count,
                        canDelete: true
                    ))
                }
            }
        }

        if cachePaths.isEmpty {
            return nil
        }

        return CacheCategory(
            id: rule.id,
            name: rule.name,
            description: rule.desc,
            icon: rule.icon,
            paths: cachePaths,
            safetyLevel: rule.level
        )
    }

    private nonisolated static func scanSubDirectories(at path: String) async -> [CachePath] {
        let url = URL(fileURLWithPath: path)
        var results: [CachePath] = []

        guard let contents = try? FileManager.default.contentsOfDirectory(at: url, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles]) else {
            return []
        }

        for content in contents {
            if let info = await getPathInfo(content.path), info.size > 0 {
                results.append(CachePath(
                    path: content.path,
                    name: content.lastPathComponent,
                    description: String(localized: "App Cache"),
                    size: info.size,
                    fileCount: info.count,
                    canDelete: true
                ))
            }
        }

        return results.sorted { $0.size > $1.size }
    }

    private nonisolated static func getPathInfo(_ path: String) async -> (size: Int64, count: Int)? {
        let fileManager = FileManager.default
        var isDir: ObjCBool = false

        guard fileManager.fileExists(atPath: path, isDirectory: &isDir) else {
            return nil
        }

        if !isDir.boolValue {
            // 单个文件
            if let attrs = try? fileManager.attributesOfItem(atPath: path),
               let size = attrs[.size] as? Int64 {
                return (size, 1)
            }
            return nil
        }

        // 目录：递归计算大小
        // 为了性能，这里不使用 DiskService 的完整扫描，而是快速遍历
        // 为简单起见，使用 Enumerator

        return await Task.detached {
            var localSize: Int64 = 0
            var localCount = 0

            guard let enumerator = fileManager.enumerator(atPath: path) else { return nil }

            // FileManager.DirectoryEnumerator 不是线程安全的，也不是 Sendable
            // 但我们在 detached Task 内部，使用本地实例（如果 fileManager 是线程安全的）
            // 实际上 FileManager.default 是线程安全的
            // 问题在于 makeIterator() 在 async 上下文中的可用性
            // 我们可以使用 while 循环和 nextObject()，这是 ObjC 方式，避免了 async 中的 Sequence 一致性问题

            while let _ = enumerator.nextObject() {
                if let fileAttrs = enumerator.fileAttributes,
                   let fileSize = fileAttrs[.size] as? Int64 {
                    localSize += fileSize
                    localCount += 1
                }
            }
            return (localSize, localCount)
        }.value
    }
}
