import EditorKernelCore

typealias DocumentSymbolProvider = EditorKernelCore.EditorDocumentSymbolProviderCore
extension EditorKernelCore.EditorDocumentSymbolProviderCore: SuperEditorDocumentSymbolProvider {}
