import EditorKernelCore

typealias RequestGeneration = EditorKernelCore.RequestGeneration
typealias CancellationContext = EditorKernelCore.CancellationContext
typealias LSPRequestLifecycle = EditorKernelCore.LSPRequestLifecycle
