import Foundation

/// Resource bundle accessor for LumiCoreKit.
///
/// Generated by SPM when resources are processed.
public enum LumiCoreKitResources {
    public static var bundle: Bundle {
        Bundle.module
    }
}
