import Foundation
import HttpKit

/// Runtime localization for LumiLLMProviderSupport bundle.
public enum LumiLLMProviderSupportLocalization {
    static func string(_ key: String, locale: Locale = .current) -> String {
        // Bundle.module is generated by SwiftPM but its access level is internal
        // when the target contains no localized resources. Fall back to main bundle.
        let bundle = Bundle.allBundles.first(where: { $0.bundleIdentifier?.contains("LumiLLMProviderSupport") ?? false }) ?? Bundle.main
        return NSLocalizedString(key, bundle: bundle, comment: "")
    }

    static func format(_ key: String, locale: Locale = .current, _ arguments: CVarArg...) -> String {
        let template = string(key, locale: locale)
        return String(format: template, locale: locale, arguments: arguments)
    }

    public static func userFacingDescription(for error: Error, locale: Locale = .current) -> String {
        let detail = LumiLLMFailureDetailResolver.resolve(from: error, locale: locale)
        let summary = detail.summary.trimmingCharacters(in: .whitespacesAndNewlines)
        if !summary.isEmpty {
            return summary
        }
        return detail.transportDetails?.trimmingCharacters(in: .whitespacesAndNewlines)
            ?? string("Request failed", locale: locale)
    }
}
