/// Unified public namespace for LumiPreviewKit.
public enum LumiPreviewPackage {}

typealias PreviewSession = LumiPreviewPackage.PreviewSession
typealias PreviewPerformanceMetrics = LumiPreviewPackage.PreviewPerformanceMetrics
typealias PreviewSessionState = LumiPreviewPackage.PreviewSessionState
typealias PreviewDiscovery = LumiPreviewPackage.PreviewDiscovery
typealias PreviewError = LumiPreviewPackage.PreviewError
typealias PreviewScanner = LumiPreviewPackage.PreviewScanner
typealias PreviewDisplayMode = LumiPreviewPackage.PreviewDisplayMode
typealias LivePreviewState = LumiPreviewPackage.LivePreviewState
typealias LivePreviewInfo = LumiPreviewPackage.LivePreviewInfo
typealias PreviewFileContextCache = LumiPreviewPackage.PreviewFileContextCache
typealias PreviewEntryBuilder = LumiPreviewPackage.PreviewEntryBuilder
typealias PreviewHostCommand = LumiPreviewPackage.PreviewHostCommand
typealias RenderRequest = LumiPreviewPackage.RenderRequest
typealias LiveFrameRequest = LumiPreviewPackage.LiveFrameRequest
typealias RenderResponse = LumiPreviewPackage.RenderResponse
typealias PreviewEntryDescriptor = LumiPreviewPackage.PreviewEntryDescriptor
typealias ErrorResponse = LumiPreviewPackage.ErrorResponse
typealias BuildStrategy = LumiPreviewPackage.BuildStrategy
typealias BuildPlanner = LumiPreviewPackage.BuildPlanner
typealias PreviewFrameAlignment = LumiPreviewPackage.PreviewFrameAlignment
typealias LivePreviewFrameAlignment = LumiPreviewPackage.LivePreviewFrameAlignment
typealias XcodeCompiler = LumiPreviewPackage.XcodeCompiler
typealias SPMCompiler = LumiPreviewPackage.SPMCompiler
typealias EditorPreviewRefreshSignal = LumiPreviewPackage.EditorPreviewRefreshSignal
typealias IncrementalCompiler = LumiPreviewPackage.IncrementalCompiler
typealias LiveCanvasService = LumiPreviewPackage.LiveCanvasService
typealias EditorPreviewLiveCanvasService = LumiPreviewPackage.EditorPreviewLiveCanvasService
typealias PreviewEnvironmentInjection = LumiPreviewPackage.PreviewEnvironmentInjection
typealias PreviewRenderConfiguration = LumiPreviewPackage.PreviewRenderConfiguration
typealias EditorPreviewRefreshPolicy = LumiPreviewPackage.EditorPreviewRefreshPolicy

public extension LumiPreviewPackage {
    typealias LivePreviewFrameAlignment = PreviewFrameAlignment
    typealias EditorPreviewLiveCanvasService = LiveCanvasService
}
