import EditorKernel

public typealias DocumentSymbolProvider = EditorKernel.EditorDocumentSymbolProviderCore
extension EditorKernel.EditorDocumentSymbolProviderCore: SuperEditorDocumentSymbolProvider {}
