import Foundation

/// Resource bundle accessor for LumiKernel.
///
/// Generated by SPM when resources are processed.
public enum LumiKernelResources {
    public static var bundle: Bundle {
        Bundle.module
    }
}
