import EditorKernelCore

public typealias DocumentSymbolProvider = EditorKernelCore.EditorDocumentSymbolProviderCore
extension EditorKernelCore.EditorDocumentSymbolProviderCore: SuperEditorDocumentSymbolProvider {}
