import EditorKernel

public typealias WorkspaceEditFileOperationsExecutor = EditorKernel.WorkspaceEditFileOperationsExecutor
public typealias WorkspaceEditFileOperations = EditorKernel.WorkspaceEditFileOperations
