import EditorKernelCore

public typealias WorkspaceEditFileOperationsExecutor = EditorKernelCore.WorkspaceEditFileOperationsExecutor
public typealias WorkspaceEditFileOperations = EditorKernelCore.WorkspaceEditFileOperations
