import EditorKernelCore

typealias WorkspaceEditFileOperationsExecutor = EditorKernelCore.WorkspaceEditFileOperationsExecutor
typealias WorkspaceEditFileOperations = EditorKernelCore.WorkspaceEditFileOperations
