// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "LumiFactory",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "LumiFactory", targets: ["LumiFactory"]),
    ],
    dependencies: [
        .package(path: "../LumiKernel"),
        .package(path: "../LumiUI"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../LocalizationKit"),
        .package(path: "../SuperLogKit"),
        .package(path: "../EditorService"),
        // Core plugins - provide required services
        .package(path: "../../Plugins/StoragePlugin"),
        .package(path: "../../Plugins/LegacyDataPlugin"),
        .package(path: "../../Plugins/ProjectsPlugin"),
        .package(path: "../../Plugins/WorkspacePlugin"),
        .package(path: "../../Plugins/EditorProviderPlugin"),
        .package(path: "../../Plugins/EditorKernelPlugin"),
        .package(path: "../../Plugins/EditorPanelPlugin"),
        .package(path: "../../Plugins/EditorSwiftPlugin"),
        .package(path: "../../Plugins/ProjectFilesPlugin"),
        .package(path: "../../Plugins/EditorPreviewPlugin"),
        .package(path: "../../Plugins/TerminalPlugin"),
        .package(path: "../../Plugins/CommandPlugin"),
        .package(path: "../../Plugins/ChatPanelPlugin"),
        .package(path: "../../Plugins/MessageListPlugin"),
        .package(path: "../../Plugins/ModelSelectorPlugin"),
        .package(path: "../../Plugins/ConversationListPlugin"),
        .package(path: "../../Plugins/ConversationNewPlugin"),
        .package(path: "../../Plugins/ConversationManagerPlugin"),
        .package(path: "../../Plugins/MessageManagerPlugin"),
        .package(path: "../../Plugins/MessageSenderPlugin"),
        .package(path: "../../Plugins/MessageStreamingPlugin"),
        .package(path: "../../Plugins/AgentTurnRunnerPlugin"),
        .package(path: "../../Plugins/MessageRendererPlugin"),
        .package(path: "../../Plugins/ConversationInputPlugin"),
        .package(path: "../../Plugins/ConversationMessageCountPlugin"),
        .package(path: "../../Plugins/ConversationContextSizePlugin"),
        .package(path: "../../Plugins/ConversationTitlePlugin"),
        .package(path: "../../Plugins/ConversationAttachmentPlugin"),
        .package(path: "../../Plugins/ConversationPendingMessagePlugin"),
        .package(path: "../../Plugins/ChatScreenshotPlugin"),
        .package(path: "../../Plugins/ChatFileAttachmentPlugin"),
        .package(path: "../../Plugins/PluginManagerPlugin"),
        .package(path: "../../Plugins/ToolManagerPlugin"),
        .package(path: "../../Plugins/SettingsPlugin"),
        .package(path: "../../Plugins/LogoPlugin"),
        .package(path: "../../Plugins/LogoCofficPlugin"),
        .package(path: "../../Plugins/LogoSmartLightPlugin"),
        .package(path: "../../Plugins/ThemeManagerPlugin"),
        .package(path: "../../Plugins/ThemeLumiPlugin"),
        .package(path: "../../Plugins/ThemeAuroraPlugin"),
        .package(path: "../../Plugins/ThemeAutumnPlugin"),
        .package(path: "../../Plugins/ThemeDraculaPlugin"),
        .package(path: "../../Plugins/ThemeGithubPlugin"),
        .package(path: "../../Plugins/ThemeMidnightPlugin"),
        .package(path: "../../Plugins/ThemeMountainPlugin"),
        .package(path: "../../Plugins/ThemeNebulaPlugin"),
        .package(path: "../../Plugins/ThemeOneDarkPlugin"),
        .package(path: "../../Plugins/ThemeOrchardPlugin"),
        .package(path: "../../Plugins/ThemeRiverPlugin"),
        .package(path: "../../Plugins/ThemeSkyPlugin"),
        .package(path: "../../Plugins/ThemeSpringPlugin"),
        .package(path: "../../Plugins/ThemeSummerPlugin"),
        .package(path: "../../Plugins/ThemeVoidPlugin"),
        .package(path: "../../Plugins/ThemeVscodePlugin"),
        .package(path: "../../Plugins/ThemeWinterPlugin"),
        .package(path: "../../Plugins/LLMProviderManagerPlugin"),
        // LLM Providers
        .package(path: "../../Plugins/LLMProviderAiRouterPlugin"),
        .package(path: "../../Plugins/LLMProviderAliyunPlugin"),
        .package(path: "../../Plugins/LLMProviderAnthropicPlugin"),
        .package(path: "../../Plugins/LLMProviderCodexPlugin"),
        .package(path: "../../Plugins/LLMProviderDeepSeekPlugin"),
        .package(path: "../../Plugins/LLMProviderFeifeimiaoPlugin"),
        .package(path: "../../Plugins/LLMProviderFlyMuxPlugin"),
        .package(path: "../../Plugins/LLMProviderFreeModelPlugin"),
        .package(path: "../../Plugins/LLMProviderHappyCodePlugin"),
        .package(path: "../../Plugins/LLMProviderHyperAPIPlugin"),
        .package(path: "../../Plugins/LLMProviderKimiCodePlugin"),
        .package(path: "../../Plugins/LLMProviderLPgptPlugin"),
        .package(path: "../../Plugins/LLMProviderMegaLLMPlugin"),
        .package(path: "../../Plugins/LLMProviderMiniMaxPlugin"),
        .package(path: "../../Plugins/LLMProviderMLXPlugin"),
        .package(path: "../../Plugins/LLMProviderOpenAIPlugin"),
        .package(path: "../../Plugins/LLMProviderOpenRouterPlugin"),
        .package(path: "../../Plugins/LLMProviderStepFunPlugin"),
        .package(path: "../../Plugins/LLMProviderSublyxPlugin"),
        .package(path: "../../Plugins/LLMProviderXiaomiPlugin"),
        .package(path: "../../Plugins/LLMProviderXybbzPlugin"),
        .package(path: "../../Plugins/LLMProviderZhipuPlugin"),
        // Editor and UI plugins
        .package(path: "../../Plugins/GitPlugin"),
        // Utility plugins
        .package(path: "../../Plugins/DeviceInfoPlugin"),
        .package(path: "../../Plugins/ProjectFileTreePlugin"),
        .package(path: "../../Plugins/ClipboardManagerPlugin"),
        .package(path: "../../Plugins/BrewManagerPlugin"),
        .package(path: "../../Plugins/DiskManagerPlugin"),
        .package(path: "../../Plugins/HostsManagerPlugin"),
        .package(path: "../../Plugins/VideoConverterPlugin"),
        .package(path: "../../Plugins/NettoPlugin"),
        .package(path: "../../Plugins/QuickLauncherPlugin"),
        .package(path: "../../Plugins/PortManagerPlugin"),
        .package(path: "../../Plugins/AppManagerPlugin"),
        .package(path: "../../Plugins/RegistryManagerPlugin"),
        .package(path: "../../Plugins/DisplayControlPlugin"),
        .package(path: "../../Plugins/DockerManagerPlugin"),
        .package(path: "../../Plugins/RClickPlugin"),
        .package(path: "../../Plugins/InputPlugin"),
        .package(path: "../../Plugins/IdleTimePlugin"),
        .package(path: "../../Plugins/MenuBarManagerPlugin"),
        .package(path: "../../Plugins/MenuBarHelperPlugin"),
        .package(path: "../../Plugins/ConversationReasoningPlugin"),
        .package(path: "../../Plugins/VerbosityPlugin"),
        .package(path: "../../Plugins/ConversationSpeedPlugin"),
        .package(path: "../../Plugins/ChatModePlugin"),
        .package(path: "../../Plugins/ConversationLanguagePlugin"),
        .package(path: "../../Plugins/QuickFileSearchPlugin"),
        .package(path: "../../Plugins/SkillPlugin"),
        .package(path: "../../Plugins/DocxReadPlugin"),
        .package(path: "../../Plugins/NetworkManagerPlugin"),
        .package(path: "../../Plugins/ProjectOverviewPlugin"),
        // Open-in external apps
        .package(path: "../../Plugins/OpenInFinderPlugin"),
        .package(path: "../../Plugins/OpenInXcodePlugin"),
        .package(path: "../../Plugins/OpenInCursorPlugin"),
        .package(path: "../../Plugins/OpenInAntigravityPlugin"),
        .package(path: "../../Plugins/OpenInGitHubDesktopPlugin"),
        .package(path: "../../Plugins/OpenInGitOKPlugin"),
        .package(path: "../../Plugins/OpenRemotePlugin"),
        .package(path: "../../Plugins/ProjectRAGPlugin"),
        .package(path: "../../Plugins/AgentRulesPlugin"),
        .package(path: "../../Plugins/CaffeinatePlugin"),
        .package(path: "../../Plugins/AgentTempStoragePlugin"),
        .package(path: "../../Plugins/AppIconDesignerPlugin"),
        .package(path: "../../Plugins/WebFetchPlugin"),
        .package(path: "../../Plugins/WebSearchPlugin"),
        .package(path: "../../Plugins/MemoryPlugin"),
        .package(path: "../../Plugins/DownloadPlugin"),
        .package(path: "../../Plugins/BrowserPlugin"),
        .package(path: "../../Plugins/ShowImagePlugin"),
        .package(path: "../../Plugins/GitHubPlugin"),
        .package(path: "../../Plugins/GoalTaskPlugin"),
        .package(path: "../../Plugins/AppStoreConnectPlugin"),
        .package(path: "../../Plugins/CADDesignerPlugin"),
        .package(path: "../../Plugins/ActivityHeatmapPlugin"),
        .package(path: "../../Plugins/FileLogPlugin"),
        .package(path: "../../Plugins/OnboardingPlugin"),
        .package(path: "../../Plugins/DatabaseManagerPlugin"),
        .package(path: "../../Plugins/ConversationForkPlugin"),
        .package(path: "../../Plugins/AgentTurnNotificationPlugin"),
        .package(path: "../../Plugins/AppUpdatePlugin"),
        // User interaction
        .package(path: "../../Plugins/AskUserPlugin"),
        .package(path: "../../Plugins/SubAgentProviderPlugin"),
    ],
    targets: [
        .target(
            name: "LumiFactory",
            dependencies: [
                .product(name: "LumiKernel", package: "LumiKernel"),
                .product(name: "LumiUI", package: "LumiUI"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LocalizationKit", package: "LocalizationKit"),
                .product(name: "SuperLogKit", package: "SuperLogKit"),
                // Core plugins - provide required services
                .product(name: "StoragePlugin", package: "StoragePlugin"),
                .product(name: "LegacyDataPlugin", package: "LegacyDataPlugin"),
                .product(name: "ProjectsPlugin", package: "ProjectsPlugin"),
                .product(name: "WorkspacePlugin", package: "WorkspacePlugin"),
                .product(name: "EditorProviderPlugin", package: "EditorProviderPlugin"),
                .product(name: "EditorKernelPlugin", package: "EditorKernelPlugin"),
                .product(name: "EditorPanelPlugin", package: "EditorPanelPlugin"),
                .product(name: "EditorSwiftPlugin", package: "EditorSwiftPlugin"),
                .product(name: "ProjectFilesPlugin", package: "ProjectFilesPlugin"),
                .product(name: "EditorPreviewPlugin", package: "EditorPreviewPlugin"),
                .product(name: "TerminalPlugin", package: "TerminalPlugin"),
                .product(name: "CommandPlugin", package: "CommandPlugin"),
                .product(name: "ChatPanelPlugin", package: "ChatPanelPlugin"),
                .product(name: "MessageListPlugin", package: "MessageListPlugin"),
                .product(name: "ModelSelectorPlugin", package: "ModelSelectorPlugin"),
                .product(name: "ConversationListPlugin", package: "ConversationListPlugin"),
                .product(name: "ConversationNewPlugin", package: "ConversationNewPlugin"),
                .product(name: "ConversationManagerPlugin", package: "ConversationManagerPlugin"),
                .product(name: "MessageManagerPlugin", package: "MessageManagerPlugin"),
                .product(name: "MessageSenderPlugin", package: "MessageSenderPlugin"),
                .product(name: "MessageStreamingPlugin", package: "MessageStreamingPlugin"),
                .product(name: "AgentTurnRunnerPlugin", package: "AgentTurnRunnerPlugin"),
                .product(name: "MessageRendererPlugin", package: "MessageRendererPlugin"),
                .product(name: "ConversationInputPlugin", package: "ConversationInputPlugin"),
                .product(name: "ConversationMessageCountPlugin", package: "ConversationMessageCountPlugin"),
                .product(name: "ConversationContextSizePlugin", package: "ConversationContextSizePlugin"),
                .product(name: "ConversationTitlePlugin", package: "ConversationTitlePlugin"),
                .product(name: "ConversationAttachmentPlugin", package: "ConversationAttachmentPlugin"),
                .product(name: "ConversationPendingMessagePlugin", package: "ConversationPendingMessagePlugin"),
                .product(name: "ChatScreenshotPlugin", package: "ChatScreenshotPlugin"),
                .product(name: "ChatFileAttachmentPlugin", package: "ChatFileAttachmentPlugin"),
                .product(name: "PluginManagerPlugin", package: "PluginManagerPlugin"),
                .product(name: "ToolManagerPlugin", package: "ToolManagerPlugin"),
                .product(name: "SettingsPlugin", package: "SettingsPlugin"),
                .product(name: "LogoPlugin", package: "LogoPlugin"),
                .product(name: "LogoCofficPlugin", package: "LogoCofficPlugin"),
                .product(name: "LogoSmartLightPlugin", package: "LogoSmartLightPlugin"),
                .product(name: "ThemeManagerPlugin", package: "ThemeManagerPlugin"),
                .product(name: "ThemeLumiPlugin", package: "ThemeLumiPlugin"),
                .product(name: "ThemeAuroraPlugin", package: "ThemeAuroraPlugin"),
                .product(name: "ThemeAutumnPlugin", package: "ThemeAutumnPlugin"),
                .product(name: "ThemeDraculaPlugin", package: "ThemeDraculaPlugin"),
                .product(name: "ThemeGithubPlugin", package: "ThemeGithubPlugin"),
                .product(name: "ThemeMidnightPlugin", package: "ThemeMidnightPlugin"),
                .product(name: "ThemeMountainPlugin", package: "ThemeMountainPlugin"),
                .product(name: "ThemeNebulaPlugin", package: "ThemeNebulaPlugin"),
                .product(name: "ThemeOneDarkPlugin", package: "ThemeOneDarkPlugin"),
                .product(name: "ThemeOrchardPlugin", package: "ThemeOrchardPlugin"),
                .product(name: "ThemeRiverPlugin", package: "ThemeRiverPlugin"),
                .product(name: "ThemeSkyPlugin", package: "ThemeSkyPlugin"),
                .product(name: "ThemeSpringPlugin", package: "ThemeSpringPlugin"),
                .product(name: "ThemeSummerPlugin", package: "ThemeSummerPlugin"),
                .product(name: "ThemeVoidPlugin", package: "ThemeVoidPlugin"),
                .product(name: "ThemeWinterPlugin", package: "ThemeWinterPlugin"),
                .product(name: "ThemeVscodePlugin", package: "ThemeVscodePlugin"),
                .product(name: "LLMProviderManagerPlugin", package: "LLMProviderManagerPlugin"),
                // LLM Providers
                .product(name: "LLMProviderAiRouterPlugin", package: "LLMProviderAiRouterPlugin"),
                .product(name: "LLMProviderAliyunPlugin", package: "LLMProviderAliyunPlugin"),
                .product(name: "LLMProviderAnthropicPlugin", package: "LLMProviderAnthropicPlugin"),
                .product(name: "LLMProviderCodexPlugin", package: "LLMProviderCodexPlugin"),
                .product(name: "LLMProviderDeepSeekPlugin", package: "LLMProviderDeepSeekPlugin"),
                .product(name: "LLMProviderFeifeimiaoPlugin", package: "LLMProviderFeifeimiaoPlugin"),
                .product(name: "LLMProviderFlyMuxPlugin", package: "LLMProviderFlyMuxPlugin"),
                .product(name: "LLMProviderFreeModelPlugin", package: "LLMProviderFreeModelPlugin"),
                .product(name: "LLMProviderHappyCodePlugin", package: "LLMProviderHappyCodePlugin"),
                .product(name: "LLMProviderHyperAPIPlugin", package: "LLMProviderHyperAPIPlugin"),
                .product(name: "LLMProviderKimiCodePlugin", package: "LLMProviderKimiCodePlugin"),
                .product(name: "LLMProviderLPgptPlugin", package: "LLMProviderLPgptPlugin"),
                .product(name: "LLMProviderMegaLLMPlugin", package: "LLMProviderMegaLLMPlugin"),
                .product(name: "LLMProviderMiniMaxPlugin", package: "LLMProviderMiniMaxPlugin"),
                .product(name: "LLMProviderMLXPlugin", package: "LLMProviderMLXPlugin"),
                .product(name: "LLMProviderOpenAIPlugin", package: "LLMProviderOpenAIPlugin"),
                .product(name: "LLMProviderOpenRouterPlugin", package: "LLMProviderOpenRouterPlugin"),
                .product(name: "LLMProviderStepFunPlugin", package: "LLMProviderStepFunPlugin"),
                .product(name: "LLMProviderSublyxPlugin", package: "LLMProviderSublyxPlugin"),
                .product(name: "LLMProviderXiaomiPlugin", package: "LLMProviderXiaomiPlugin"),
                .product(name: "LLMProviderXybbzPlugin", package: "LLMProviderXybbzPlugin"),
                .product(name: "LLMProviderZhipuPlugin", package: "LLMProviderZhipuPlugin"),
                // Editor and UI plugins
                .product(name: "EditorService", package: "EditorService"),
                .product(name: "GitPlugin", package: "GitPlugin"),
                // Utility plugins
                .product(name: "DeviceInfoPlugin", package: "DeviceInfoPlugin"),
                .product(name: "ProjectFileTreePlugin", package: "ProjectFileTreePlugin"),
                .product(name: "ClipboardManagerPlugin", package: "ClipboardManagerPlugin"),
                .product(name: "BrewManagerPlugin", package: "BrewManagerPlugin"),
                .product(name: "DiskManagerPlugin", package: "DiskManagerPlugin"),
                .product(name: "HostsManagerPlugin", package: "HostsManagerPlugin"),
                .product(name: "ConversationReasoningPlugin", package: "ConversationReasoningPlugin"),
                .product(name: "VideoConverterPlugin", package: "VideoConverterPlugin"),
                .product(name: "NettoPlugin", package: "NettoPlugin"),
                .product(name: "QuickLauncherPlugin", package: "QuickLauncherPlugin"),
                .product(name: "PortManagerPlugin", package: "PortManagerPlugin"),
                .product(name: "AppManagerPlugin", package: "AppManagerPlugin"),
                .product(name: "RegistryManagerPlugin", package: "RegistryManagerPlugin"),
                .product(name: "DisplayControlPlugin", package: "DisplayControlPlugin"),
                .product(name: "DockerManagerPlugin", package: "DockerManagerPlugin"),
                .product(name: "RClickPlugin", package: "RClickPlugin"),
                .product(name: "InputPlugin", package: "InputPlugin"),
                .product(name: "IdleTimePlugin", package: "IdleTimePlugin"),
                .product(name: "MenuBarManagerPlugin", package: "MenuBarManagerPlugin"),
                .product(name: "MenuBarHelperPlugin", package: "MenuBarHelperPlugin"),
                .product(name: "VerbosityPlugin", package: "VerbosityPlugin"),
                .product(name: "ConversationSpeedPlugin", package: "ConversationSpeedPlugin"),
                .product(name: "ChatModePlugin", package: "ChatModePlugin"),
                .product(name: "ConversationLanguagePlugin", package: "ConversationLanguagePlugin"),
                .product(name: "QuickFileSearchPlugin", package: "QuickFileSearchPlugin"),
                .product(name: "SkillPlugin", package: "SkillPlugin"),
                .product(name: "DocxReadPlugin", package: "DocxReadPlugin"),
                .product(name: "NetworkManagerPlugin", package: "NetworkManagerPlugin"),
                .product(name: "ProjectOverviewPlugin", package: "ProjectOverviewPlugin"),
                // Open-in external apps
                .product(name: "OpenInFinderPlugin", package: "OpenInFinderPlugin"),
                .product(name: "OpenInXcodePlugin", package: "OpenInXcodePlugin"),
                .product(name: "OpenInCursorPlugin", package: "OpenInCursorPlugin"),
                .product(name: "OpenInAntigravityPlugin", package: "OpenInAntigravityPlugin"),
                .product(name: "OpenInGitHubDesktopPlugin", package: "OpenInGitHubDesktopPlugin"),
                .product(name: "OpenInGitOKPlugin", package: "OpenInGitOKPlugin"),
                .product(name: "OpenRemotePlugin", package: "OpenRemotePlugin"),
                .product(name: "ProjectRAGPlugin", package: "ProjectRAGPlugin"),
                .product(name: "AgentRulesPlugin", package: "AgentRulesPlugin"),
                .product(name: "CaffeinatePlugin", package: "CaffeinatePlugin"),
                .product(name: "AgentTempStoragePlugin", package: "AgentTempStoragePlugin"),
                .product(name: "AppIconDesignerPlugin", package: "AppIconDesignerPlugin"),
                .product(name: "WebFetchPlugin", package: "WebFetchPlugin"),
                .product(name: "WebSearchPlugin", package: "WebSearchPlugin"),
                .product(name: "MemoryPlugin", package: "MemoryPlugin"),
                .product(name: "DownloadPlugin", package: "DownloadPlugin"),
                .product(name: "BrowserPlugin", package: "BrowserPlugin"),
                .product(name: "ShowImagePlugin", package: "ShowImagePlugin"),
                .product(name: "GitHubPlugin", package: "GitHubPlugin"),
                .product(name: "GoalTaskPlugin", package: "GoalTaskPlugin"),
                .product(name: "AppStoreConnectPlugin", package: "AppStoreConnectPlugin"),
                .product(name: "CADDesignerPlugin", package: "CADDesignerPlugin"),
                .product(name: "ActivityHeatmapPlugin", package: "ActivityHeatmapPlugin"),
                .product(name: "FileLogPlugin", package: "FileLogPlugin"),
                .product(name: "OnboardingPlugin", package: "OnboardingPlugin"),
                .product(name: "DatabaseManagerPlugin", package: "DatabaseManagerPlugin"),
                .product(name: "ConversationForkPlugin", package: "ConversationForkPlugin"),
                .product(name: "AgentTurnNotificationPlugin", package: "AgentTurnNotificationPlugin"),
                .product(name: "AppUpdatePlugin", package: "AppUpdatePlugin"),
                .product(name: "AskUserPlugin", package: "AskUserPlugin"),
                .product(name: "SubAgentProviderPlugin", package: "SubAgentProviderPlugin"),
            ],
            resources: [
                .process("Resources")
            ]
        )
    ]
)
