// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "LumiFactory",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "LumiFactory", targets: ["LumiFactory"]),
    ],
    dependencies: [
        .package(path: "../LumiCoreAgentTool"),
        .package(path: "../LumiCoreChat"),
        .package(path: "../LumiCoreLayout"),
        .package(path: "../LumiCoreLLMProvider"),
        .package(path: "../LumiCoreMessage"),
        .package(path: "../LumiCoreProject"),
        .package(path: "../LumiCoreStorage"),
        .package(path: "../LumiCoreSubAgent"),
        .package(path: "../LumiKernel"),
        .package(path: "../LumiUI"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../LocalizationKit"),
        .package(path: "../SuperLogKit"),
        .package(path: "../EditorService"),
        // Core plugins - provide required services
        .package(path: "../../Plugins/StoragePlugin"),
        .package(path: "../../Plugins/ProjectsPlugin"),
        .package(path: "../../Plugins/LayoutKernelPlugin"),
        .package(path: "../../Plugins/ViewContainerPlugin"),
        .package(path: "../../Plugins/CommandPlugin"),
        .package(path: "../../Plugins/MenuBarPlugin"),
        .package(path: "../../Plugins/TitleToolbarPlugin"),
        .package(path: "../../Plugins/SendMiddlewarePlugin"),
        .package(path: "../../Plugins/ChatKernelPlugin"),
        .package(path: "../../Plugins/ChatPanelPlugin"),
        .package(path: "../../Plugins/ChatSectionPlugin"),
        .package(path: "../../Plugins/ChatComposerPlugin"),
        .package(path: "../../Plugins/MessageListPlugin"),
        .package(path: "../../Plugins/ConversationListPlugin"),
        .package(path: "../../Plugins/ConversationManagerPlugin"),
        .package(path: "../../Plugins/EditorKernelPlugin"),
        .package(path: "../../Plugins/AgentToolPlugin"),
        .package(path: "../../Plugins/PanelPlugin"),
        .package(path: "../../Plugins/StatusBarPlugin"),
        .package(path: "../../Plugins/SettingsPlugin"),
        .package(path: "../../Plugins/LogoPlugin"),
        .package(path: "../../Plugins/ThemeStatusBarPlugin"),
        .package(path: "../../Plugins/ThemeLumiPlugin"),
        .package(path: "../../Plugins/ThemeAuroraPlugin"),
        .package(path: "../../Plugins/ThemeAutumnPlugin"),
        .package(path: "../../Plugins/ThemeDraculaPlugin"),
        .package(path: "../../Plugins/ThemeGithubPlugin"),
        .package(path: "../../Plugins/ThemeMidnightPlugin"),
        .package(path: "../../Plugins/ThemeMountainPlugin"),
        .package(path: "../../Plugins/ThemeNebulaPlugin"),
        .package(path: "../../Plugins/ThemeOneDarkPlugin"),
        .package(path: "../../Plugins/ThemeOrchardPlugin"),
        .package(path: "../../Plugins/ThemeRiverPlugin"),
        .package(path: "../../Plugins/ThemeSkyPlugin"),
        .package(path: "../../Plugins/ThemeSpringPlugin"),
        .package(path: "../../Plugins/ThemeSummerPlugin"),
        .package(path: "../../Plugins/ThemeVoidPlugin"),
        .package(path: "../../Plugins/ThemeVscodePlugin"),
        .package(path: "../../Plugins/ThemeWinterPlugin"),
        .package(path: "../../Plugins/PluginManagementPlugin"),
        // Editor and UI plugins
        .package(path: "../../Plugins/EditorPanelPlugin"),
        // Utility plugins
        .package(path: "../../Plugins/DeviceInfoPlugin"),
        .package(path: "../../Plugins/ClipboardManagerPlugin"),
        .package(path: "../../Plugins/BrewManagerPlugin"),
        .package(path: "../../Plugins/DiskManagerPlugin"),
        .package(path: "../../Plugins/HostsManagerPlugin"),
        .package(path: "../../Plugins/VideoConverterPlugin"),
        .package(path: "../../Plugins/NettoPlugin"),
        .package(path: "../../Plugins/QuickLauncherPlugin"),
        .package(path: "../../Plugins/PortManagerPlugin"),
        .package(path: "../../Plugins/AppManagerPlugin"),
        .package(path: "../../Plugins/RegistryManagerPlugin"),
        .package(path: "../../Plugins/DisplayControlPlugin"),
        .package(path: "../../Plugins/DockerManagerPlugin"),
        .package(path: "../../Plugins/RClickPlugin"),
        .package(path: "../../Plugins/InputPlugin"),
        .package(path: "../../Plugins/MenuBarManagerPlugin"),
    ],
    targets: [
        .target(
            name: "LumiFactory",
            dependencies: [
                .product(name: "LumiCoreAgentTool", package: "LumiCoreAgentTool"),
                .product(name: "LumiCoreChat", package: "LumiCoreChat"),
                .product(name: "LumiCoreLayout", package: "LumiCoreLayout"),
                .product(name: "LumiCoreLLMProvider", package: "LumiCoreLLMProvider"),
                .product(name: "LumiCoreMessage", package: "LumiCoreMessage"),
                .product(name: "LumiCoreProject", package: "LumiCoreProject"),
                .product(name: "LumiCoreStorage", package: "LumiCoreStorage"),
                .product(name: "LumiCoreSubAgent", package: "LumiCoreSubAgent"),
                .product(name: "LumiKernel", package: "LumiKernel"),
                .product(name: "LumiUI", package: "LumiUI"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LocalizationKit", package: "LocalizationKit"),
                .product(name: "SuperLogKit", package: "SuperLogKit"),
                // Core plugins - provide required services
                .product(name: "StoragePlugin", package: "StoragePlugin"),
                .product(name: "ProjectsPlugin", package: "ProjectsPlugin"),
                .product(name: "LayoutKernelPlugin", package: "LayoutKernelPlugin"),
                .product(name: "ViewContainerPlugin", package: "ViewContainerPlugin"),
                .product(name: "CommandPlugin", package: "CommandPlugin"),
                .product(name: "MenuBarPlugin", package: "MenuBarPlugin"),
                .product(name: "TitleToolbarPlugin", package: "TitleToolbarPlugin"),
                .product(name: "SendMiddlewarePlugin", package: "SendMiddlewarePlugin"),
                .product(name: "ChatKernelPlugin", package: "ChatKernelPlugin"),
                .product(name: "ChatPanelPlugin", package: "ChatPanelPlugin"),
                .product(name: "ChatSectionPlugin", package: "ChatSectionPlugin"),
                .product(name: "ChatComposerPlugin", package: "ChatComposerPlugin"),
                .product(name: "MessageListPlugin", package: "MessageListPlugin"),
                .product(name: "ConversationListPlugin", package: "ConversationListPlugin"),
                .product(name: "ConversationManagerPlugin", package: "ConversationManagerPlugin"),
                .product(name: "EditorKernelPlugin", package: "EditorKernelPlugin"),
                .product(name: "AgentToolPlugin", package: "AgentToolPlugin"),
                .product(name: "PanelPlugin", package: "PanelPlugin"),
                .product(name: "StatusBarPlugin", package: "StatusBarPlugin"),
                .product(name: "SettingsPlugin", package: "SettingsPlugin"),
                .product(name: "LogoPlugin", package: "LogoPlugin"),
                .product(name: "ThemeStatusBarPlugin", package: "ThemeStatusBarPlugin"),
                .product(name: "ThemeLumiPlugin", package: "ThemeLumiPlugin"),
                .product(name: "ThemeAuroraPlugin", package: "ThemeAuroraPlugin"),
                .product(name: "ThemeAutumnPlugin", package: "ThemeAutumnPlugin"),
                .product(name: "ThemeDraculaPlugin", package: "ThemeDraculaPlugin"),
                .product(name: "ThemeGithubPlugin", package: "ThemeGithubPlugin"),
                .product(name: "ThemeMidnightPlugin", package: "ThemeMidnightPlugin"),
                .product(name: "ThemeMountainPlugin", package: "ThemeMountainPlugin"),
                .product(name: "ThemeNebulaPlugin", package: "ThemeNebulaPlugin"),
                .product(name: "ThemeOneDarkPlugin", package: "ThemeOneDarkPlugin"),
                .product(name: "ThemeOrchardPlugin", package: "ThemeOrchardPlugin"),
                .product(name: "ThemeRiverPlugin", package: "ThemeRiverPlugin"),
                .product(name: "ThemeSkyPlugin", package: "ThemeSkyPlugin"),
                .product(name: "ThemeSpringPlugin", package: "ThemeSpringPlugin"),
                .product(name: "ThemeSummerPlugin", package: "ThemeSummerPlugin"),
                .product(name: "ThemeVoidPlugin", package: "ThemeVoidPlugin"),
                .product(name: "ThemeVscodePlugin", package: "ThemeVscodePlugin"),
                .product(name: "ThemeWinterPlugin", package: "ThemeWinterPlugin"),
                .product(name: "PluginManagementPlugin", package: "PluginManagementPlugin"),
                // Editor and UI plugins
                .product(name: "EditorPanelPlugin", package: "EditorPanelPlugin"),
                .product(name: "EditorService", package: "EditorService"),
                // Utility plugins
                .product(name: "DeviceInfoPlugin", package: "DeviceInfoPlugin"),
                .product(name: "ClipboardManagerPlugin", package: "ClipboardManagerPlugin"),
                .product(name: "BrewManagerPlugin", package: "BrewManagerPlugin"),
                .product(name: "DiskManagerPlugin", package: "DiskManagerPlugin"),
                .product(name: "HostsManagerPlugin", package: "HostsManagerPlugin"),
                .product(name: "VideoConverterPlugin", package: "VideoConverterPlugin"),
                .product(name: "NettoPlugin", package: "NettoPlugin"),
                .product(name: "QuickLauncherPlugin", package: "QuickLauncherPlugin"),
                .product(name: "PortManagerPlugin", package: "PortManagerPlugin"),
                .product(name: "AppManagerPlugin", package: "AppManagerPlugin"),
                .product(name: "RegistryManagerPlugin", package: "RegistryManagerPlugin"),
                .product(name: "DisplayControlPlugin", package: "DisplayControlPlugin"),
                .product(name: "DockerManagerPlugin", package: "DockerManagerPlugin"),
                .product(name: "RClickPlugin", package: "RClickPlugin"),
                .product(name: "InputPlugin", package: "InputPlugin"),
                .product(name: "MenuBarManagerPlugin", package: "MenuBarManagerPlugin"),
            ],
            resources: [
                .process("Resources")
            ]
        )
    ]
)
