#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${SRCROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PLUGINS_DIR="$ROOT_DIR/Plugins"
REGISTRY_DIR="$ROOT_DIR/Packages/LumiPluginRegistry"
REGISTRY_SOURCES_DIR="$REGISTRY_DIR/Sources/LumiPluginRegistry"
PACKAGE_OUTPUT="$REGISTRY_DIR/Package.swift"
REGISTRY_OUTPUT="$REGISTRY_SOURCES_DIR/GeneratedPluginRegistry.swift"
PACKAGE_TMP_OUTPUT="$PACKAGE_OUTPUT.tmp"
REGISTRY_TMP_OUTPUT="$REGISTRY_OUTPUT.tmp"

mkdir -p "$REGISTRY_SOURCES_DIR"

registry_entries="$(
  find "$PLUGINS_DIR" -mindepth 4 -maxdepth 4 -path "$PLUGINS_DIR/Plugin*/Sources/*/*.swift" -print |
    sort |
    while IFS= read -r plugin_file; do
      actor_name="$(sed -E -n 's/^[[:space:]]*public[[:space:]]+actor[[:space:]]+([A-Za-z0-9_]*Plugin):.*SuperPlugin.*/\1/p' "$plugin_file" | head -1)"
      [[ -n "$actor_name" ]] || continue

      package_name="$(printf '%s\n' "$plugin_file" | sed -E "s#^$PLUGINS_DIR/([^/]+)/.*#\1#")"
      [[ -n "$package_name" ]] || continue
      printf '%s|%s\n' "$actor_name" "$package_name"
    done
)"

registry_imports="$(printf '%s\n' "$registry_entries" | awk -F'|' '{ print $2 }' | sort -u)"

{
  printf '// This file is generated by scripts/generate-plugin-registry.sh.\n'
  printf '// Do not edit by hand.\n\n'
  printf 'import LumiCoreKit\n'
  printf '%s\n' "$registry_imports" |
    while IFS= read -r package_name; do
      [[ -n "$package_name" ]] || continue
      printf 'import %s\n' "$package_name"
    done
  printf '\n'
  printf 'public enum GeneratedPluginRegistry {\n'
  printf '    @MainActor\n'
  printf '    public static var plugins: [any LumiCoreKit.SuperPlugin] {\n'
  printf '        var plugins: [any LumiCoreKit.SuperPlugin] = []\n'
  printf '%s\n' "$registry_entries" |
    while IFS='|' read -r actor_name package_name; do
      [[ -n "$actor_name" && -n "$package_name" ]] || continue
      printf '        plugins.append(%s.%s.shared)\n' "$package_name" "$actor_name"
    done
  printf '        return plugins\n'
  printf '    }\n'
  printf '}\n'
} > "$REGISTRY_TMP_OUTPUT"

if [[ -f "$REGISTRY_OUTPUT" ]] && cmp -s "$REGISTRY_TMP_OUTPUT" "$REGISTRY_OUTPUT"; then
  rm "$REGISTRY_TMP_OUTPUT"
else
  mv "$REGISTRY_TMP_OUTPUT" "$REGISTRY_OUTPUT"
fi

{
  printf '// swift-tools-version: 6.0\n'
  printf '// This file is generated by scripts/generate-plugin-registry.sh.\n'
  printf '// Do not edit by hand.\n\n'
  printf 'import PackageDescription\n\n'
  printf 'let package = Package(\n'
  printf '    name: "LumiPluginRegistry",\n'
  printf '    platforms: [\n'
  printf '        .macOS(.v14),\n'
  printf '    ],\n'
  printf '    products: [\n'
  printf '        .library(name: "LumiPluginRegistry", targets: ["LumiPluginRegistry"]),\n'
  printf '    ],\n'
  printf '    dependencies: [\n'
  printf '        .package(path: "../LumiCoreKit"),\n'
  printf '%s\n' "$registry_imports" |
    while IFS= read -r package_name; do
      [[ -n "$package_name" ]] || continue
      printf '        .package(path: "../../Plugins/%s"),\n' "$package_name"
    done
  printf '    ],\n'
  printf '    targets: [\n'
  printf '        .target(\n'
  printf '            name: "LumiPluginRegistry",\n'
  printf '            dependencies: [\n'
  printf '                "LumiCoreKit",\n'
  printf '%s\n' "$registry_imports" |
    while IFS= read -r package_name; do
      [[ -n "$package_name" ]] || continue
      printf '                "%s",\n' "$package_name"
    done
  printf '            ],\n'
  printf '            path: "Sources/LumiPluginRegistry"\n'
  printf '        ),\n'
  printf '    ]\n'
  printf ')\n'
} > "$PACKAGE_TMP_OUTPUT"

if [[ -f "$PACKAGE_OUTPUT" ]] && cmp -s "$PACKAGE_TMP_OUTPUT" "$PACKAGE_OUTPUT"; then
  rm "$PACKAGE_TMP_OUTPUT"
else
  mv "$PACKAGE_TMP_OUTPUT" "$PACKAGE_OUTPUT"
fi
