#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${SRCROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PLUGINS_DIR="$ROOT_DIR/Plugins"
OUTPUT="$ROOT_DIR/LumiApp/Core/Generated/GeneratedPluginRegistry.swift"
TMP_OUTPUT="$OUTPUT.tmp"

mkdir -p "$(dirname "$OUTPUT")"

registry_entries="$(
  find "$PLUGINS_DIR" -mindepth 4 -maxdepth 4 -path "$PLUGINS_DIR/Plugin*/Sources/*/*.swift" -print |
    sort |
    while IFS= read -r plugin_file; do
      actor_name="$(sed -E -n 's/^[[:space:]]*public[[:space:]]+actor[[:space:]]+([A-Za-z0-9_]*Plugin):.*SuperPlugin.*/\1/p' "$plugin_file" | head -1)"
      [[ -n "$actor_name" ]] || continue

      package_name="$(printf '%s\n' "$plugin_file" | sed -E "s#^$PLUGINS_DIR/([^/]+)/.*#\1#")"
      [[ -n "$package_name" ]] || continue
      printf '%s|%s\n' "$actor_name" "$package_name"
    done
)"

registry_imports="$(printf '%s\n' "$registry_entries" | awk -F'|' '{ print $2 }' | sort -u)"

{
  printf '// This file is generated by scripts/generate-plugin-registry.sh.\n'
  printf '// Do not edit by hand.\n\n'
  printf 'import Foundation\n'
  printf '%s\n' "$registry_imports" |
    while IFS= read -r package_name; do
      [[ -n "$package_name" ]] || continue
      printf 'import %s\n' "$package_name"
    done
  printf '\n'
  printf 'enum GeneratedPluginRegistry {\n'
  printf '    @MainActor\n'
  printf '    static var plugins: [any SuperPlugin] {\n'
  printf '        var plugins: [any SuperPlugin] = []\n'
  printf '%s\n' "$registry_entries" |
    while IFS='|' read -r actor_name package_name; do
      [[ -n "$actor_name" && -n "$package_name" ]] || continue
      printf '        plugins.append(PackagePluginAdapter<%s.%s>.shared)\n' "$package_name" "$actor_name"
    done
  printf '        return plugins\n'
  printf '    }\n'
  printf '}\n'
} > "$TMP_OUTPUT"

if [[ -f "$OUTPUT" ]] && cmp -s "$TMP_OUTPUT" "$OUTPUT"; then
  rm "$TMP_OUTPUT"
else
  mv "$TMP_OUTPUT" "$OUTPUT"
fi
