#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${SRCROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
APP_PLUGINS_DIR="$ROOT_DIR/LumiApp/Plugins"
OUTPUT="$ROOT_DIR/LumiApp/Core/Generated/GeneratedPluginRegistry.swift"
TMP_OUTPUT="$OUTPUT.tmp"

mkdir -p "$(dirname "$OUTPUT")"

registry_entries="$(
  find "$APP_PLUGINS_DIR" -maxdepth 1 -type f -name '*Plugin.swift' -print |
    sort |
    while IFS= read -r plugin_file; do
      actor_name="$(sed -E -n 's/^[[:space:]]*(public[[:space:]]+)?actor[[:space:]]+([A-Za-z0-9_]*Plugin):.*SuperPlugin.*/\2/p' "$plugin_file" | head -1)"
      if [[ -n "$actor_name" ]]; then
        printf '%s|%s|%s\n' "$actor_name" "" "direct"
        continue
      fi

      typealias_line="$(sed -E -n 's/^[[:space:]]*typealias[[:space:]]+([A-Za-z0-9_]*Plugin)[[:space:]]*=[[:space:]]*([A-Za-z0-9_.]*)[[:space:]]*$/\1|\2/p' "$plugin_file" | head -1)"
      [[ -n "$typealias_line" ]] || continue

      alias_name="${typealias_line%%|*}"
      packaged_type="${typealias_line#*|}"
      package_name="${packaged_type%%.*}"
      [[ -n "$alias_name" && -n "$packaged_type" && -n "$package_name" ]] || continue
      printf '%s|%s|%s\n' "$packaged_type" "$package_name" "package"
    done
)"

registry_imports="$(printf '%s\n' "$registry_entries" | awk -F'|' '$3 == "package" { print $2 }' | sort -u)"

{
  printf '// This file is generated by scripts/generate-plugin-registry.sh.\n'
  printf '// Do not edit by hand.\n\n'
  printf 'import Foundation\n'
  printf '%s\n' "$registry_imports" |
    while IFS= read -r package_name; do
      [[ -n "$package_name" ]] || continue
      printf 'import %s\n' "$package_name"
    done
  printf '\n'
  printf 'enum GeneratedPluginRegistry {\n'
  printf '    @MainActor\n'
  printf '    static var plugins: [any SuperPlugin] {\n'
  printf '        var plugins: [any SuperPlugin] = []\n'
  printf '%s\n' "$registry_entries" |
    while IFS='|' read -r type_or_actor package_name source; do
      [[ -n "$type_or_actor" ]] || continue
      if [[ "$source" == "package" ]]; then
        printf '        plugins.append(PackagePluginAdapter<%s>.shared)\n' "$type_or_actor"
      else
        printf '        plugins.append(%s.shared)\n' "$type_or_actor"
      fi
    done
  printf '        return plugins\n'
  printf '    }\n'
  printf '}\n'
} > "$TMP_OUTPUT"

if [[ -f "$OUTPUT" ]] && cmp -s "$TMP_OUTPUT" "$OUTPUT"; then
  rm "$TMP_OUTPUT"
else
  mv "$TMP_OUTPUT" "$OUTPUT"
fi
