// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "FactoryLumi",
    defaultLocalization: "en",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "FactoryLumi", targets: ["FactoryLumi"]),
    ],
    dependencies: [
        .package(path: "../KernelCore"),
        .package(path: "../KitLocalization"),
        .package(path: "../LumiUI"),
        .package(path: "../PluginAppIconDesigner"),
        .package(path: "../PluginAppStorePromoDesigner"),
        .package(path: "../PluginMindMapDesigner"),
        .package(path: "../PluginResumeDesigner"),
        .package(path: "../PluginActivityBar"),
        .package(path: "../PluginDevice"),
        .package(path: "../PluginDiskManager"),
        .package(path: "../PluginNetworkManager"),
        .package(path: "../PluginCaffeinate"),
        .package(path: "../PluginHostsManager"),
        .package(path: "../PluginDocxRead"),
        .package(path: "../PluginWebFetch"),
        .package(path: "../PluginWebSearch"),
        .package(path: "../PluginWebServer"),
        .package(path: "../PluginAgentTempStorage"),
        .package(path: "../PluginOcr"),
        .package(path: "../PluginAgentRules"),
        .package(path: "../PluginLogoCoffic"),
        .package(path: "../PluginLogoManager"),
        .package(path: "../PluginLogoSmartLight"),
        .package(path: "../PluginSettingGeneral"),
        .package(path: "../PluginSettingView"),
        .package(path: "../PluginThemePack"),
        .package(path: "../PluginToolbarSettings"),
        .package(path: "../PluginVideoConverter"),
        .package(path: "../PluginWhiteNoise"),
        .package(path: "../PluginIdleTime"),
        .package(path: "../PluginActivityHeatmap"),
        .package(path: "../PluginChatFileAttachment"),
        .package(path: "../PluginChatPanel"),
        .package(path: "../PluginChatScreenshot"),
        .package(path: "../PluginConversationMode"),
        .package(path: "../PluginConversationBehavior"),
        .package(path: "../PluginConversationCacheHitRate"),
        .package(path: "../PluginConversationStats"),
        .package(path: "../PluginConversationSpeed"),
        .package(path: "../PluginConversationTitle"),
        .package(path: "../PluginConversationState"),
        .package(path: "../PluginConversationPendingMessage"),
        .package(path: "../PluginConversationFork"),
        .package(path: "../PluginAskUser"),
        .package(path: "../PluginOpenInFinder"),
        .package(path: "../PluginOpenInXcode"),
        .package(path: "../PluginOpenInCursor"),
        .package(path: "../PluginOpenInVSCode"),
        .package(path: "../PluginOpenInAntigravity"),
        .package(path: "../PluginOpenInGitHubDesktop"),
        .package(path: "../PluginOpenInGitOK"),
        .package(path: "../OpenInKit"),
        .package(path: "../PluginAgentTurnNotification"),
        .package(path: "../PluginSkill"),
        .package(path: "../PluginOnboarding"),
        .package(path: "../PluginMemory"),
        .package(path: "../PluginModelSelector"),
        .package(path: "../PluginConversationInput"),
        .package(path: "../PluginProjects"),
        .package(path: "../PluginProjectFileTree"),
        .package(path: "../PluginProjectFiles"),
        .package(path: "../PluginCodeEditorHost"),
        .package(path: "../PluginCodeEditorLanguages"),
        .package(path: "../PluginCodeEditor"),
        .package(path: "../PluginProjectRAG"),
        .package(path: "../PluginMessageList"),
        .package(path: "../PluginMessageRenderer"),
        .package(path: "../PluginConversationList"),
        .package(path: "../PluginConversationNew"),
        .package(path: "../PluginConversationManager"),
        .package(path: "../PluginMessageManager"),
        .package(path: "../PluginMessageSender"),
        .package(path: "../PluginPluginManager"),
        .package(path: "../PluginAgentLoop"),
        .package(path: "../PluginToolManager"),
        .package(path: "../PluginDebugBadge"),
        .package(path: "../PluginFileLog"),
        .package(path: "../PluginShowImage"),
        .package(name: "PluginImageToPDF", path: "../PluginImageToPDF"),
        .package(name: "PluginDownload", path: "../PluginDownload"),
        .package(name: "PluginAppManager", path: "../PluginAppManager"),
        .package(name: "PluginClipboardManager", path: "../PluginClipboardManager"),
        .package(name: "PluginBrowser", path: "../PluginBrowser"),
        .package(name: "PluginComputerUse", path: "../PluginComputerUse"),
        .package(name: "PluginBrewManager", path: "../PluginBrewManager"),
        .package(name: "PluginDisplayControl", path: "../PluginDisplayControl"),
        .package(name: "PluginPortManager", path: "../PluginPortManager"),
        .package(name: "PluginDockerManager", path: "../PluginDockerManager"),
        .package(name: "PluginRegistryManager", path: "../PluginRegistryManager"),
        .package(name: "PluginRClick", path: "../PluginRClick"),
        .package(name: "PluginInput", path: "../PluginInput"),
        .package(name: "PluginBookletMaker", path: "../PluginBookletMaker"),
        .package(name: "PluginScreenRecorder", path: "../PluginScreenRecorder"),
        .package(name: "PluginStoryWriter", path: "../PluginStoryWriter"),
        .package(name: "PluginQuickFileSearch", path: "../PluginQuickFileSearch"),
        .package(name: "PluginProjectOverview", path: "../PluginProjectOverview"),
        .package(name: "PluginQuickLauncher", path: "../PluginQuickLauncher"),
        .package(name: "PluginTextActions", path: "../PluginTextActions"),
        .package(name: "PluginTerminal", path: "../PluginTerminal"),
        .package(name: "PluginDatabaseManager", path: "../PluginDatabaseManager"),
        .package(name: "PluginGit", path: "../PluginGit"),
        .package(name: "PluginGoalTask", path: "../PluginGoalTask"),
        .package(name: "PluginNetto", path: "../PluginNetto"),
        .package(path: "../PluginStorage"),
        .package(path: "../PluginToast"),
        .package(path: "../PluginCommand"),
        .package(path: "../ProviderActivityBar"),
        .package(path: "../ProviderConversation"),
        .package(path: "../ProviderContentView"),
        .package(path: "../ProviderChatSection"),
        .package(path: "../ProviderMessage"),
        .package(path: "../ProviderAgentLoop"),
        .package(path: "../KitLLM"),
        .package(path: "../ProviderLLMManager"),
        .package(path: "../PluginLLMProviderAiRouter"),
        .package(path: "../PluginLLMManager"),
        .package(path: "../PluginLLMProviderAliyun"),
        .package(path: "../PluginLLMProviderAnthropic"),
        .package(path: "../PluginLLMProviderDeepSeek"),
        .package(path: "../PluginLLMProviderFeifeimiao"),
        .package(path: "../PluginLLMProviderFlyMux"),
        .package(path: "../PluginLLMProviderHappyCode"),
        .package(path: "../PluginLLMProviderHyperAPI"),
        .package(path: "../PluginLLMProviderKimiCode"),
        .package(path: "../PluginLLMProviderLPgpt"),
        .package(path: "../PluginLLMProviderMegaLLM"),
        .package(path: "../PluginLLMProviderMiniMax"),
        .package(path: "../PluginLLMProviderSettings"),
        .package(path: "../PluginLLMProviderOpenAI"),
        .package(path: "../PluginLLMProviderOpenCode"),
        .package(path: "../PluginLLMProviderOpenRouter"),
        .package(path: "../PluginLLMProviderStepFun"),
        .package(path: "../PluginLLMProviderSublyx"),
        .package(path: "../PluginLLMProviderTencent"),
        .package(path: "../PluginLLMProviderXiaomi"),
        .package(path: "../PluginLLMProviderXybbz"),
        .package(path: "../PluginLLMProviderZhipu"),
        .package(path: "../PluginLLMProviderCodex"),
        .package(path: "../PluginLLMProviderMLX"),
        .package(path: "../ProviderMessageSender"),
        .package(path: "../ProviderDocsView"),
        .package(path: "../ProviderMenuBar"),
        .package(path: "../ProviderLogo"),
        .package(path: "../ProviderNetwork"),
        .package(path: "../ProviderProject"),
        .package(path: "../ProviderProjectRAG"),
        .package(path: "../ProviderRailView"),
        .package(path: "../ProviderRootView"),
        .package(path: "../ProviderSettingView"),
        .package(path: "../ProviderStorage"),
        .package(path: "../ProviderTheme"),
        .package(path: "../ProviderToast"),
        .package(path: "../ProviderToolbar"),
        .package(path: "../ProviderToolManager"),
        .package(path: "../ProviderCommand"),
        .package(path: "../ProviderConversationInput"),
        .package(path: "../ProviderIdleTime"),
        .package(path: "../ProviderLegacyData"),
        .package(path: "../ProviderMessageRendering"),
        .package(path: "../ProviderMessageStreaming"),
        .package(path: "../ProviderPluginControl"),
        .package(path: "../ProviderPluginManaging"),
        .package(path: "../ProviderPromptSuggestion"),
        .package(path: "../ProviderOnboarding"),
        .package(path: "../ProviderWebServer"),
        .package(path: "../ProviderLifecycleHooks"),
        .package(path: "../ProviderExternalFile"),
    ],
    targets: [
        .target(
            name: "FactoryLumi",
            dependencies: [
                .product(name: "KernelCore", package: "KernelCore"),
                .product(name: "KitLocalization", package: "KitLocalization"),
                .product(name: "LumiUI", package: "LumiUI"),
                .product(name: "PluginAppIconDesigner", package: "PluginAppIconDesigner"),
                .product(name: "PluginAppStorePromoDesigner", package: "PluginAppStorePromoDesigner"),
                .product(name: "PluginMindMapDesigner", package: "PluginMindMapDesigner"),
                .product(name: "PluginResumeDesigner", package: "PluginResumeDesigner"),
                .product(name: "PluginActivityBar", package: "PluginActivityBar"),
                .product(name: "PluginDevice", package: "PluginDevice"),
                .product(name: "PluginDiskManager", package: "PluginDiskManager"),
                .product(name: "PluginNetworkManager", package: "PluginNetworkManager"),
                .product(name: "PluginCaffeinate", package: "PluginCaffeinate"),
                .product(name: "PluginHostsManager", package: "PluginHostsManager"),
                .product(name: "PluginDocxRead", package: "PluginDocxRead"),
                .product(name: "PluginWebFetch", package: "PluginWebFetch"),
                .product(name: "PluginWebSearch", package: "PluginWebSearch"),
                .product(name: "PluginWebServer", package: "PluginWebServer"),
                .product(name: "PluginAgentTempStorage", package: "PluginAgentTempStorage"),
                .product(name: "PluginOcr", package: "PluginOcr"),
                .product(name: "PluginAgentRules", package: "PluginAgentRules"),
                .product(name: "PluginLogoCoffic", package: "PluginLogoCoffic"),
                .product(name: "PluginLogoManager", package: "PluginLogoManager"),
                .product(name: "PluginLogoSmartLight", package: "PluginLogoSmartLight"),
                .product(name: "PluginSettingGeneral", package: "PluginSettingGeneral"),
                .product(name: "PluginSettingView", package: "PluginSettingView"),
                .product(name: "PluginThemePack", package: "PluginThemePack"),
                .product(name: "PluginToolbarSettings", package: "PluginToolbarSettings"),
                .product(name: "PluginVideoConverter", package: "PluginVideoConverter"),
                .product(name: "PluginWhiteNoise", package: "PluginWhiteNoise"),
                .product(name: "PluginIdleTime", package: "PluginIdleTime"),
                .product(name: "PluginActivityHeatmap", package: "PluginActivityHeatmap"),
                .product(name: "PluginChatFileAttachment", package: "PluginChatFileAttachment"),
                .product(name: "PluginChatPanel", package: "PluginChatPanel"),
                .product(name: "PluginChatScreenshot", package: "PluginChatScreenshot"),
                .product(name: "PluginConversationMode", package: "PluginConversationMode"),
                .product(name: "PluginConversationBehavior", package: "PluginConversationBehavior"),
                .product(name: "PluginConversationCacheHitRate", package: "PluginConversationCacheHitRate"),
                .product(name: "PluginConversationStats", package: "PluginConversationStats"),
                .product(name: "PluginConversationSpeed", package: "PluginConversationSpeed"),
                .product(name: "PluginConversationTitle", package: "PluginConversationTitle"),
                .product(name: "PluginConversationState", package: "PluginConversationState"),
                .product(name: "PluginConversationPendingMessage", package: "PluginConversationPendingMessage"),
                .product(name: "PluginConversationFork", package: "PluginConversationFork"),
                .product(name: "PluginAskUser", package: "PluginAskUser"),
                .product(name: "PluginOpenInFinder", package: "PluginOpenInFinder"),
                .product(name: "PluginOpenInXcode", package: "PluginOpenInXcode"),
                .product(name: "PluginOpenInCursor", package: "PluginOpenInCursor"),
                .product(name: "PluginOpenInVSCode", package: "PluginOpenInVSCode"),
                .product(name: "PluginOpenInAntigravity", package: "PluginOpenInAntigravity"),
                .product(name: "PluginOpenInGitHubDesktop", package: "PluginOpenInGitHubDesktop"),
                .product(name: "PluginOpenInGitOK", package: "PluginOpenInGitOK"),
                .product(name: "OpenInKit", package: "OpenInKit"),
                .product(name: "PluginAgentTurnNotification", package: "PluginAgentTurnNotification"),
                .product(name: "PluginSkill", package: "PluginSkill"),
                .product(name: "PluginOnboarding", package: "PluginOnboarding"),
                .product(name: "PluginMemory", package: "PluginMemory"),
                .product(name: "PluginModelSelector", package: "PluginModelSelector"),
                .product(name: "PluginConversationInput", package: "PluginConversationInput"),
                .product(name: "PluginProjects", package: "PluginProjects"),
                .product(name: "PluginProjectFileTree", package: "PluginProjectFileTree"),
                .product(name: "PluginProjectFiles", package: "PluginProjectFiles"),
                .product(name: "PluginCodeEditorHost", package: "PluginCodeEditorHost"),
                .product(name: "PluginCodeEditorLanguages", package: "PluginCodeEditorLanguages"),
                .product(name: "PluginCodeEditor", package: "PluginCodeEditor"),
                .product(name: "PluginProjectRAG", package: "PluginProjectRAG"),
                .product(name: "PluginMessageList", package: "PluginMessageList"),
                .product(name: "PluginMessageRenderer", package: "PluginMessageRenderer"),
                .product(name: "PluginConversationList", package: "PluginConversationList"),
                .product(name: "PluginConversationNew", package: "PluginConversationNew"),
                .product(name: "PluginConversationManager", package: "PluginConversationManager"),
                .product(name: "PluginMessageManager", package: "PluginMessageManager"),
                .product(name: "PluginMessageSender", package: "PluginMessageSender"),
                .product(name: "PluginPluginManager", package: "PluginPluginManager"),
                .product(name: "PluginAgentLoop", package: "PluginAgentLoop"),
                .product(name: "PluginToolManager", package: "PluginToolManager"),
                .product(name: "PluginDebugBadge", package: "PluginDebugBadge"),
                .product(name: "PluginFileLog", package: "PluginFileLog"),
                .product(name: "PluginShowImage", package: "PluginShowImage"),
                .product(name: "PluginImageToPDF", package: "PluginImageToPDF"),
                .product(name: "PluginDownload", package: "PluginDownload"),
                .product(name: "PluginAppManager", package: "PluginAppManager"),
                .product(name: "PluginClipboardManager", package: "PluginClipboardManager"),
                .product(name: "PluginBrowser", package: "PluginBrowser"),
                .product(name: "PluginComputerUse", package: "PluginComputerUse"),
                .product(name: "PluginBrewManager", package: "PluginBrewManager"),
                .product(name: "PluginDisplayControl", package: "PluginDisplayControl"),
                .product(name: "PluginPortManager", package: "PluginPortManager"),
                .product(name: "PluginDockerManager", package: "PluginDockerManager"),
                .product(name: "PluginRegistryManager", package: "PluginRegistryManager"),
                .product(name: "PluginRClick", package: "PluginRClick"),
                .product(name: "PluginInput", package: "PluginInput"),
                .product(name: "PluginBookletMaker", package: "PluginBookletMaker"),
                .product(name: "PluginScreenRecorder", package: "PluginScreenRecorder"),
                .product(name: "PluginStoryWriter", package: "PluginStoryWriter"),
                .product(name: "PluginQuickFileSearch", package: "PluginQuickFileSearch"),
                .product(name: "PluginProjectOverview", package: "PluginProjectOverview"),
                .product(name: "PluginQuickLauncher", package: "PluginQuickLauncher"),
                .product(name: "PluginTextActions", package: "PluginTextActions"),
                .product(name: "PluginTerminal", package: "PluginTerminal"),
                .product(name: "PluginDatabaseManager", package: "PluginDatabaseManager"),
                .product(name: "PluginGit", package: "PluginGit"),
                .product(name: "PluginGoalTask", package: "PluginGoalTask"),
                .product(name: "PluginNetto", package: "PluginNetto"),
                .product(name: "PluginStorage", package: "PluginStorage"),
                .product(name: "PluginToast", package: "PluginToast"),
                .product(name: "PluginCommand", package: "PluginCommand"),
                .product(name: "ProviderActivityBar", package: "ProviderActivityBar"),
                .product(name: "ProviderConversation", package: "ProviderConversation"),
                .product(name: "ProviderContentView", package: "ProviderContentView"),
                .product(name: "ProviderChatSection", package: "ProviderChatSection"),
                .product(name: "ProviderMessage", package: "ProviderMessage"),
                .product(name: "ProviderAgentLoop", package: "ProviderAgentLoop"),
                .product(name: "KitLLM", package: "KitLLM"),
                .product(name: "ProviderLLMManager", package: "ProviderLLMManager"),
                .product(name: "PluginLLMProviderAiRouter", package: "PluginLLMProviderAiRouter"),
                .product(name: "PluginLLMManager", package: "PluginLLMManager"),
                .product(name: "PluginLLMProviderAliyun", package: "PluginLLMProviderAliyun"),
                .product(name: "PluginLLMProviderAnthropic", package: "PluginLLMProviderAnthropic"),
                .product(name: "PluginLLMProviderDeepSeek", package: "PluginLLMProviderDeepSeek"),
                .product(name: "PluginLLMProviderFeifeimiao", package: "PluginLLMProviderFeifeimiao"),
                .product(name: "PluginLLMProviderFlyMux", package: "PluginLLMProviderFlyMux"),
                .product(name: "PluginLLMProviderHappyCode", package: "PluginLLMProviderHappyCode"),
                .product(name: "PluginLLMProviderHyperAPI", package: "PluginLLMProviderHyperAPI"),
                .product(name: "PluginLLMProviderKimiCode", package: "PluginLLMProviderKimiCode"),
                .product(name: "PluginLLMProviderLPgpt", package: "PluginLLMProviderLPgpt"),
                .product(name: "PluginLLMProviderMegaLLM", package: "PluginLLMProviderMegaLLM"),
                .product(name: "PluginLLMProviderMiniMax", package: "PluginLLMProviderMiniMax"),
                .product(name: "PluginLLMProviderSettings", package: "PluginLLMProviderSettings"),
                .product(name: "PluginLLMProviderOpenAI", package: "PluginLLMProviderOpenAI"),
                .product(name: "PluginLLMProviderOpenCode", package: "PluginLLMProviderOpenCode"),
                .product(name: "PluginLLMProviderOpenRouter", package: "PluginLLMProviderOpenRouter"),
                .product(name: "PluginLLMProviderStepFun", package: "PluginLLMProviderStepFun"),
                .product(name: "PluginLLMProviderSublyx", package: "PluginLLMProviderSublyx"),
                .product(name: "PluginLLMProviderTencent", package: "PluginLLMProviderTencent"),
                .product(name: "PluginLLMProviderXiaomi", package: "PluginLLMProviderXiaomi"),
                .product(name: "PluginLLMProviderXybbz", package: "PluginLLMProviderXybbz"),
                .product(name: "PluginLLMProviderZhipu", package: "PluginLLMProviderZhipu"),
                .product(name: "PluginLLMProviderCodex", package: "PluginLLMProviderCodex"),
                .product(name: "PluginLLMProviderMLX", package: "PluginLLMProviderMLX"),
                .product(name: "ProviderMessageSender", package: "ProviderMessageSender"),
                .product(name: "ProviderDocsView", package: "ProviderDocsView"),
                .product(name: "ProviderMenuBar", package: "ProviderMenuBar"),
                .product(name: "ProviderLogo", package: "ProviderLogo"),
                .product(name: "ProviderNetwork", package: "ProviderNetwork"),
                .product(name: "ProviderProject", package: "ProviderProject"),
                .product(name: "ProviderProjectRAG", package: "ProviderProjectRAG"),
                .product(name: "ProviderRailView", package: "ProviderRailView"),
                .product(name: "ProviderRootView", package: "ProviderRootView"),
                .product(name: "ProviderSettingView", package: "ProviderSettingView"),
                .product(name: "ProviderStorage", package: "ProviderStorage"),
                .product(name: "ProviderTheme", package: "ProviderTheme"),
                .product(name: "ProviderToast", package: "ProviderToast"),
                .product(name: "ProviderToolbar", package: "ProviderToolbar"),
                .product(name: "ProviderToolManager", package: "ProviderToolManager"),
                .product(name: "ProviderConversationInput", package: "ProviderConversationInput"),
                .product(name: "ProviderMessageStreaming", package: "ProviderMessageStreaming"),
                .product(name: "ProviderMessageRendering", package: "ProviderMessageRendering"),
                .product(name: "ProviderPromptSuggestion", package: "ProviderPromptSuggestion"),
                .product(name: "ProviderOnboarding", package: "ProviderOnboarding"),
                .product(name: "ProviderCommand", package: "ProviderCommand"),
                .product(name: "ProviderIdleTime", package: "ProviderIdleTime"),
                .product(name: "ProviderLegacyData", package: "ProviderLegacyData"),
                .product(name: "ProviderPluginControl", package: "ProviderPluginControl"),
                .product(name: "ProviderPluginManaging", package: "ProviderPluginManaging"),
                .product(name: "ProviderWebServer", package: "ProviderWebServer"),
                .product(name: "ProviderLifecycleHooks", package: "ProviderLifecycleHooks"),
                .product(name: "ProviderExternalFile", package: "ProviderExternalFile"),
            ],
            path: ".",
            sources: ["Sources"],
            resources: [.process("Resources/Localizable.xcstrings")]
        ),
        .testTarget(
            name: "FactoryLumiTests",
            dependencies: [
                "FactoryLumi",
                .product(name: "ProviderLLMManager", package: "ProviderLLMManager"),
                .product(name: "PluginLLMProviderAiRouter", package: "PluginLLMProviderAiRouter"),
                .product(name: "PluginLLMProviderAliyun", package: "PluginLLMProviderAliyun"),
                .product(name: "PluginLLMProviderAnthropic", package: "PluginLLMProviderAnthropic"),
                .product(name: "PluginLLMProviderDeepSeek", package: "PluginLLMProviderDeepSeek"),
                .product(name: "PluginLLMProviderFeifeimiao", package: "PluginLLMProviderFeifeimiao"),
                .product(name: "PluginLLMProviderFlyMux", package: "PluginLLMProviderFlyMux"),
                .product(name: "PluginLLMProviderHappyCode", package: "PluginLLMProviderHappyCode"),
                .product(name: "PluginLLMProviderHyperAPI", package: "PluginLLMProviderHyperAPI"),
                .product(name: "PluginLLMProviderKimiCode", package: "PluginLLMProviderKimiCode"),
                .product(name: "PluginLLMProviderLPgpt", package: "PluginLLMProviderLPgpt"),
                .product(name: "PluginLLMProviderMegaLLM", package: "PluginLLMProviderMegaLLM"),
                .product(name: "PluginLLMProviderMiniMax", package: "PluginLLMProviderMiniMax"),
                .product(name: "PluginLLMProviderSettings", package: "PluginLLMProviderSettings"),
                .product(name: "PluginLLMProviderOpenAI", package: "PluginLLMProviderOpenAI"),
                .product(name: "PluginLLMProviderOpenCode", package: "PluginLLMProviderOpenCode"),
                .product(name: "PluginLLMProviderOpenRouter", package: "PluginLLMProviderOpenRouter"),
                .product(name: "PluginLLMProviderStepFun", package: "PluginLLMProviderStepFun"),
                .product(name: "PluginLLMProviderSublyx", package: "PluginLLMProviderSublyx"),
                .product(name: "PluginLLMProviderTencent", package: "PluginLLMProviderTencent"),
                .product(name: "PluginLLMProviderXiaomi", package: "PluginLLMProviderXiaomi"),
                .product(name: "PluginLLMProviderXybbz", package: "PluginLLMProviderXybbz"),
                .product(name: "PluginLLMProviderZhipu", package: "PluginLLMProviderZhipu"),
                .product(name: "KitLLM", package: "KitLLM"),
                .product(name: "ProviderMessage", package: "ProviderMessage"),
                .product(name: "ProviderIdleTime", package: "ProviderIdleTime"),
                .product(name: "ProviderConversation", package: "ProviderConversation"),
                .product(name: "PluginConversationManager", package: "PluginConversationManager"),
            ]
        )
    ]
)
