// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "FactoryLumi2",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "FactoryLumi2", targets: ["FactoryLumi2"]),
    ],
    dependencies: [
        .package(path: "../KernelCore"),
        .package(path: "../LumiUI"),
        .package(path: "../PluginAppIconDesigner"),
        .package(path: "../PluginAppStorePromoDesigner"),
        .package(path: "../PluginMindMapDesigner"),
        .package(path: "../PluginDevice"),
        .package(path: "../PluginLogoCoffic"),
        .package(path: "../PluginSettingGeneral"),
        .package(path: "../PluginThemePack"),
        .package(path: "../PluginToolbarSettings"),
        .package(path: "../PluginVideoConverter"),
        .package(path: "../PluginWhiteNoise"),
        .package(path: "../PluginChatPanel"),
        .package(path: "../PluginConversationInput"),
        .package(path: "../PluginMessageList"),
        .package(path: "../PluginConversationList"),
        .package(path: "../PluginConversationNew"),
        .package(path: "../ProviderActivityBar"),
        .package(path: "../ProviderConversation"),
        .package(path: "../ProviderContentView"),
        .package(path: "../ProviderChatSection"),
        .package(path: "../ProviderMessage"),
        .package(path: "../ProviderAgentLoop"),
        .package(path: "../ProviderLLM"),
        .package(path: "../ProviderLLMManager"),
        .package(path: "../ProviderMessageSender"),
        .package(path: "../ProviderDocsView"),
        .package(path: "../ProviderMenuBar"),
        .package(path: "../ProviderLogo"),
        .package(path: "../ProviderNetwork"),
        .package(path: "../ProviderProject"),
        .package(path: "../ProviderRailView"),
        .package(path: "../ProviderRootView"),
        .package(path: "../ProviderSettingView"),
        .package(path: "../ProviderStorage"),
        .package(path: "../ProviderTheme"),
        .package(path: "../ProviderToast"),
        .package(path: "../ProviderToolbar"),
        .package(path: "../ProviderToolManager"),
        .package(path: "../ProviderRuntime"),
        .package(path: "../ProviderWebServer"),
    ],
    targets: [
        .target(
            name: "FactoryLumi2",
            dependencies: [
                .product(name: "KernelCore", package: "KernelCore"),
                .product(name: "LumiUI", package: "LumiUI"),
                .product(name: "PluginAppIconDesigner", package: "PluginAppIconDesigner"),
                .product(name: "PluginAppStorePromoDesigner", package: "PluginAppStorePromoDesigner"),
                .product(name: "PluginMindMapDesigner", package: "PluginMindMapDesigner"),
                .product(name: "PluginDevice", package: "PluginDevice"),
                .product(name: "PluginLogoCoffic", package: "PluginLogoCoffic"),
                .product(name: "PluginSettingGeneral", package: "PluginSettingGeneral"),
                .product(name: "PluginThemePack", package: "PluginThemePack"),
                .product(name: "PluginToolbarSettings", package: "PluginToolbarSettings"),
                .product(name: "PluginVideoConverter", package: "PluginVideoConverter"),
                .product(name: "PluginWhiteNoise", package: "PluginWhiteNoise"),
                .product(name: "PluginChatPanel", package: "PluginChatPanel"),
                .product(name: "PluginConversationInput", package: "PluginConversationInput"),
                .product(name: "PluginMessageList", package: "PluginMessageList"),
                .product(name: "PluginConversationList", package: "PluginConversationList"),
                .product(name: "PluginConversationNew", package: "PluginConversationNew"),
                .product(name: "ProviderActivityBar", package: "ProviderActivityBar"),
                .product(name: "ProviderConversation", package: "ProviderConversation"),
                .product(name: "ProviderContentView", package: "ProviderContentView"),
                .product(name: "ProviderChatSection", package: "ProviderChatSection"),
                .product(name: "ProviderMessage", package: "ProviderMessage"),
                .product(name: "ProviderAgentLoop", package: "ProviderAgentLoop"),
                .product(name: "ProviderLLM", package: "ProviderLLM"),
                .product(name: "ProviderLLMManager", package: "ProviderLLMManager"),
                .product(name: "ProviderMessageSender", package: "ProviderMessageSender"),
                .product(name: "ProviderDocsView", package: "ProviderDocsView"),
                .product(name: "ProviderMenuBar", package: "ProviderMenuBar"),
                .product(name: "ProviderLogo", package: "ProviderLogo"),
                .product(name: "ProviderNetwork", package: "ProviderNetwork"),
                .product(name: "ProviderProject", package: "ProviderProject"),
                .product(name: "ProviderRailView", package: "ProviderRailView"),
                .product(name: "ProviderRootView", package: "ProviderRootView"),
                .product(name: "ProviderSettingView", package: "ProviderSettingView"),
                .product(name: "ProviderStorage", package: "ProviderStorage"),
                .product(name: "ProviderTheme", package: "ProviderTheme"),
                .product(name: "ProviderToast", package: "ProviderToast"),
                .product(name: "ProviderToolbar", package: "ProviderToolbar"),
                .product(name: "ProviderToolManager", package: "ProviderToolManager"),
                .product(name: "ProviderAgentTurn", package: "ProviderRuntime"),
                .product(name: "ProviderConversationInput", package: "ProviderRuntime"),
                .product(name: "ProviderMessageStreaming", package: "ProviderRuntime"),
                .product(name: "ProviderMessageRendering", package: "ProviderRuntime"),
                .product(name: "ProviderPromptSuggestion", package: "ProviderRuntime"),
                .product(name: "ProviderWorkspace", package: "ProviderRuntime"),
                .product(name: "ProviderOnboarding", package: "ProviderRuntime"),
                .product(name: "ProviderCommand", package: "ProviderRuntime"),
                .product(name: "ProviderIdleTime", package: "ProviderRuntime"),
                .product(name: "ProviderLegacyData", package: "ProviderRuntime"),
                .product(name: "ProviderPluginControl", package: "ProviderRuntime"),
                .product(name: "ProviderWebServer", package: "ProviderWebServer"),
            ],
            path: "Sources/FactoryLumi2"
        ),
        .testTarget(
            name: "FactoryLumi2Tests",
            dependencies: [
                "FactoryLumi2",
                .product(name: "ProviderLLMManager", package: "ProviderLLMManager"),
                .product(name: "ProviderLLM", package: "ProviderLLM"),
                .product(name: "ProviderMessage", package: "ProviderMessage"),
            ]
        )
    ]
)
