// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "FactoryLumi2",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "FactoryLumi2", targets: ["FactoryLumi2"]),
    ],
    dependencies: [
        .package(path: "../KernelCore"),
        .package(path: "../LumiUI"),
        .package(path: "../PluginAppIconDesigner"),
        .package(path: "../PluginAppStorePromoDesigner"),
        .package(path: "../PluginMindMapDesigner"),
        .package(path: "../PluginResumeDesigner"),
        .package(path: "../PluginActivityBar"),
        .package(path: "../PluginDevice"),
        .package(path: "../PluginDiskManager"),
        .package(path: "../PluginNetworkManager"),
        .package(path: "../PluginCaffeinate"),
        .package(path: "../PluginHostsManager"),
        .package(path: "../PluginDocxRead"),
        .package(path: "../PluginWebFetch"),
        .package(path: "../PluginWebSearch"),
        .package(path: "../PluginAgentTempStorage"),
        .package(path: "../PluginOcr"),
        .package(path: "../PluginAgentRules"),
        .package(path: "../PluginLogoCoffic"),
        .package(path: "../PluginLogoManager"),
        .package(path: "../PluginLogoSmartLight"),
        .package(path: "../PluginSettingGeneral"),
        .package(path: "../PluginSettingView"),
        .package(path: "../PluginThemePack"),
        .package(path: "../PluginToolbarSettings"),
        .package(path: "../PluginVideoConverter"),
        .package(path: "../PluginWhiteNoise"),
        .package(path: "../PluginIdleTime"),
        .package(path: "../PluginChatFileAttachment"),
        .package(path: "../PluginChatPanel"),
        .package(path: "../PluginChatScreenshot"),
        .package(path: "../PluginConversationMode"),
        .package(path: "../PluginConversationBehavior"),
        .package(path: "../PluginConversationStats"),
        .package(path: "../PluginConversationTitle"),
        .package(path: "../PluginConversationPendingMessage"),
        .package(path: "../PluginConversationFork"),
        .package(path: "../PluginAskUser"),
        .package(path: "../PluginOpenIn"),
        .package(path: "../PluginAgentTurnNotification"),
        .package(path: "../PluginSkill"),
        .package(path: "../PluginMemory"),
        .package(path: "../PluginModelSelector"),
        .package(path: "../PluginConversationInput"),
        .package(path: "../PluginProjects"),
        .package(path: "../PluginMessageList"),
        .package(path: "../PluginMessageRenderer"),
        .package(path: "../PluginConversationList"),
        .package(path: "../PluginConversationNew"),
        .package(path: "../PluginConversationManager"),
        .package(path: "../PluginMessageManager"),
        .package(path: "../PluginMessageSender"),
        .package(path: "../PluginPluginManager"),
        .package(path: "../PluginAgentLoop"),
        .package(path: "../PluginToolManager"),
        .package(path: "../PluginDebugBadge"),
        .package(path: "../PluginFileLog"),
        .package(path: "../PluginShowImage"),
        .package(path: "../PluginStorage"),
        .package(path: "../PluginToast"),
        .package(path: "../PluginCommand"),
        .package(path: "../ProviderActivityBar"),
        .package(path: "../ProviderConversation"),
        .package(path: "../ProviderContentView"),
        .package(path: "../ProviderChatSection"),
        .package(path: "../ProviderMessage"),
        .package(path: "../ProviderAgentLoop"),
        .package(path: "../KitLLM"),
        .package(path: "../ProviderLLMManager"),
        .package(path: "../PluginLLMProviderAiRouter"),
        .package(path: "../PluginLLMManager"),
        .package(path: "../PluginLLMProviderAliyun"),
        .package(path: "../PluginLLMProviderAnthropic"),
        .package(path: "../PluginLLMProviderDeepSeek"),
        .package(path: "../PluginLLMProviderFeifeimiao"),
        .package(path: "../PluginLLMProviderFlyMux"),
        .package(path: "../PluginLLMProviderHappyCode"),
        .package(path: "../PluginLLMProviderHyperAPI"),
        .package(path: "../PluginLLMProviderKimiCode"),
        .package(path: "../PluginLLMProviderLPgpt"),
        .package(path: "../PluginLLMProviderMegaLLM"),
        .package(path: "../PluginLLMProviderMiniMax"),
        .package(path: "../PluginLLMProviderSettings"),
        .package(path: "../PluginLLMProviderOpenAI"),
        .package(path: "../PluginLLMProviderOpenCode"),
        .package(path: "../PluginLLMProviderOpenRouter"),
        .package(path: "../PluginLLMProviderStepFun"),
        .package(path: "../PluginLLMProviderSublyx"),
        .package(path: "../PluginLLMProviderXiaomi"),
        .package(path: "../PluginLLMProviderXybbz"),
        .package(path: "../PluginLLMProviderZhipu"),
        .package(path: "../ProviderMessageSender"),
        .package(path: "../ProviderDocsView"),
        .package(path: "../ProviderMenuBar"),
        .package(path: "../ProviderLogo"),
        .package(path: "../ProviderNetwork"),
        .package(path: "../ProviderProject"),
        .package(path: "../ProviderRailView"),
        .package(path: "../ProviderRootView"),
        .package(path: "../ProviderSettingView"),
        .package(path: "../ProviderStorage"),
        .package(path: "../ProviderTheme"),
        .package(path: "../ProviderToast"),
        .package(path: "../ProviderToolbar"),
        .package(path: "../ProviderToolManager"),
        .package(path: "../ProviderCommand"),
        .package(path: "../ProviderConversationInput"),
        .package(path: "../ProviderIdleTime"),
        .package(path: "../ProviderLegacyData"),
        .package(path: "../ProviderMessageRendering"),
        .package(path: "../ProviderMessageStreaming"),
        .package(path: "../ProviderPluginControl"),
        .package(path: "../ProviderPluginManaging"),
        .package(path: "../ProviderPromptSuggestion"),
        .package(path: "../ProviderWorkspace"),
        .package(path: "../ProviderOnboarding"),
        .package(path: "../ProviderWebServer"),
        .package(path: "../ProviderLifecycleHooks"),
    ],
    targets: [
        .target(
            name: "FactoryLumi2",
            dependencies: [
                .product(name: "KernelCore", package: "KernelCore"),
                .product(name: "LumiUI", package: "LumiUI"),
                .product(name: "PluginAppIconDesigner", package: "PluginAppIconDesigner"),
                .product(name: "PluginAppStorePromoDesigner", package: "PluginAppStorePromoDesigner"),
                .product(name: "PluginMindMapDesigner", package: "PluginMindMapDesigner"),
                .product(name: "PluginResumeDesigner", package: "PluginResumeDesigner"),
                .product(name: "PluginActivityBar", package: "PluginActivityBar"),
                .product(name: "PluginDevice", package: "PluginDevice"),
                .product(name: "PluginDiskManager", package: "PluginDiskManager"),
                .product(name: "PluginNetworkManager", package: "PluginNetworkManager"),
                .product(name: "PluginCaffeinate", package: "PluginCaffeinate"),
                .product(name: "PluginHostsManager", package: "PluginHostsManager"),
                .product(name: "PluginDocxRead", package: "PluginDocxRead"),
                .product(name: "PluginWebFetch", package: "PluginWebFetch"),
                .product(name: "PluginWebSearch", package: "PluginWebSearch"),
                .product(name: "PluginAgentTempStorage", package: "PluginAgentTempStorage"),
                .product(name: "PluginOcr", package: "PluginOcr"),
                .product(name: "PluginAgentRules", package: "PluginAgentRules"),
                .product(name: "PluginLogoCoffic", package: "PluginLogoCoffic"),
                .product(name: "PluginLogoManager", package: "PluginLogoManager"),
                .product(name: "PluginLogoSmartLight", package: "PluginLogoSmartLight"),
                .product(name: "PluginSettingGeneral", package: "PluginSettingGeneral"),
                .product(name: "PluginSettingView", package: "PluginSettingView"),
                .product(name: "PluginThemePack", package: "PluginThemePack"),
                .product(name: "PluginToolbarSettings", package: "PluginToolbarSettings"),
                .product(name: "PluginVideoConverter", package: "PluginVideoConverter"),
                .product(name: "PluginWhiteNoise", package: "PluginWhiteNoise"),
                .product(name: "PluginIdleTime", package: "PluginIdleTime"),
                .product(name: "PluginChatFileAttachment", package: "PluginChatFileAttachment"),
                .product(name: "PluginChatPanel", package: "PluginChatPanel"),
                .product(name: "PluginChatScreenshot", package: "PluginChatScreenshot"),
                .product(name: "PluginConversationMode", package: "PluginConversationMode"),
                .product(name: "PluginConversationBehavior", package: "PluginConversationBehavior"),
                .product(name: "PluginConversationStats", package: "PluginConversationStats"),
                .product(name: "PluginConversationTitle", package: "PluginConversationTitle"),
                .product(name: "PluginConversationPendingMessage", package: "PluginConversationPendingMessage"),
                .product(name: "PluginConversationFork", package: "PluginConversationFork"),
                .product(name: "PluginAskUser", package: "PluginAskUser"),
                .product(name: "PluginOpenIn", package: "PluginOpenIn"),
                .product(name: "PluginAgentTurnNotification", package: "PluginAgentTurnNotification"),
                .product(name: "PluginSkill", package: "PluginSkill"),
                .product(name: "PluginMemory", package: "PluginMemory"),
                .product(name: "PluginModelSelector", package: "PluginModelSelector"),
                .product(name: "PluginConversationInput", package: "PluginConversationInput"),
                .product(name: "PluginProjects", package: "PluginProjects"),
                .product(name: "PluginMessageList", package: "PluginMessageList"),
                .product(name: "PluginMessageRenderer", package: "PluginMessageRenderer"),
                .product(name: "PluginConversationList", package: "PluginConversationList"),
                .product(name: "PluginConversationNew", package: "PluginConversationNew"),
                .product(name: "PluginConversationManager", package: "PluginConversationManager"),
                .product(name: "PluginMessageManager", package: "PluginMessageManager"),
                .product(name: "PluginMessageSender", package: "PluginMessageSender"),
                .product(name: "PluginPluginManager", package: "PluginPluginManager"),
                .product(name: "PluginAgentLoop", package: "PluginAgentLoop"),
                .product(name: "PluginToolManager", package: "PluginToolManager"),
                .product(name: "PluginDebugBadge", package: "PluginDebugBadge"),
                .product(name: "PluginFileLog", package: "PluginFileLog"),
                .product(name: "PluginShowImage", package: "PluginShowImage"),
                .product(name: "PluginStorage", package: "PluginStorage"),
                .product(name: "PluginToast", package: "PluginToast"),
                .product(name: "PluginCommand", package: "PluginCommand"),
                .product(name: "ProviderActivityBar", package: "ProviderActivityBar"),
                .product(name: "ProviderConversation", package: "ProviderConversation"),
                .product(name: "ProviderContentView", package: "ProviderContentView"),
                .product(name: "ProviderChatSection", package: "ProviderChatSection"),
                .product(name: "ProviderMessage", package: "ProviderMessage"),
                .product(name: "ProviderAgentLoop", package: "ProviderAgentLoop"),
                .product(name: "KitLLM", package: "KitLLM"),
                .product(name: "ProviderLLMManager", package: "ProviderLLMManager"),
                .product(name: "PluginLLMProviderAiRouter", package: "PluginLLMProviderAiRouter"),
                .product(name: "PluginLLMManager", package: "PluginLLMManager"),
                .product(name: "PluginLLMProviderAliyun", package: "PluginLLMProviderAliyun"),
                .product(name: "PluginLLMProviderAnthropic", package: "PluginLLMProviderAnthropic"),
                .product(name: "PluginLLMProviderDeepSeek", package: "PluginLLMProviderDeepSeek"),
                .product(name: "PluginLLMProviderFeifeimiao", package: "PluginLLMProviderFeifeimiao"),
                .product(name: "PluginLLMProviderFlyMux", package: "PluginLLMProviderFlyMux"),
                .product(name: "PluginLLMProviderHappyCode", package: "PluginLLMProviderHappyCode"),
                .product(name: "PluginLLMProviderHyperAPI", package: "PluginLLMProviderHyperAPI"),
                .product(name: "PluginLLMProviderKimiCode", package: "PluginLLMProviderKimiCode"),
                .product(name: "PluginLLMProviderLPgpt", package: "PluginLLMProviderLPgpt"),
                .product(name: "PluginLLMProviderMegaLLM", package: "PluginLLMProviderMegaLLM"),
                .product(name: "PluginLLMProviderMiniMax", package: "PluginLLMProviderMiniMax"),
                .product(name: "PluginLLMProviderSettings", package: "PluginLLMProviderSettings"),
                .product(name: "PluginLLMProviderOpenAI", package: "PluginLLMProviderOpenAI"),
                .product(name: "PluginLLMProviderOpenCode", package: "PluginLLMProviderOpenCode"),
                .product(name: "PluginLLMProviderOpenRouter", package: "PluginLLMProviderOpenRouter"),
                .product(name: "PluginLLMProviderStepFun", package: "PluginLLMProviderStepFun"),
                .product(name: "PluginLLMProviderSublyx", package: "PluginLLMProviderSublyx"),
                .product(name: "PluginLLMProviderXiaomi", package: "PluginLLMProviderXiaomi"),
                .product(name: "PluginLLMProviderXybbz", package: "PluginLLMProviderXybbz"),
                .product(name: "PluginLLMProviderZhipu", package: "PluginLLMProviderZhipu"),
                .product(name: "ProviderMessageSender", package: "ProviderMessageSender"),
                .product(name: "ProviderDocsView", package: "ProviderDocsView"),
                .product(name: "ProviderMenuBar", package: "ProviderMenuBar"),
                .product(name: "ProviderLogo", package: "ProviderLogo"),
                .product(name: "ProviderNetwork", package: "ProviderNetwork"),
                .product(name: "ProviderProject", package: "ProviderProject"),
                .product(name: "ProviderRailView", package: "ProviderRailView"),
                .product(name: "ProviderRootView", package: "ProviderRootView"),
                .product(name: "ProviderSettingView", package: "ProviderSettingView"),
                .product(name: "ProviderStorage", package: "ProviderStorage"),
                .product(name: "ProviderTheme", package: "ProviderTheme"),
                .product(name: "ProviderToast", package: "ProviderToast"),
                .product(name: "ProviderToolbar", package: "ProviderToolbar"),
                .product(name: "ProviderToolManager", package: "ProviderToolManager"),
                .product(name: "ProviderConversationInput", package: "ProviderConversationInput"),
                .product(name: "ProviderMessageStreaming", package: "ProviderMessageStreaming"),
                .product(name: "ProviderMessageRendering", package: "ProviderMessageRendering"),
                .product(name: "ProviderPromptSuggestion", package: "ProviderPromptSuggestion"),
                .product(name: "ProviderWorkspace", package: "ProviderWorkspace"),
                .product(name: "ProviderOnboarding", package: "ProviderOnboarding"),
                .product(name: "ProviderCommand", package: "ProviderCommand"),
                .product(name: "ProviderIdleTime", package: "ProviderIdleTime"),
                .product(name: "ProviderLegacyData", package: "ProviderLegacyData"),
                .product(name: "ProviderPluginControl", package: "ProviderPluginControl"),
                .product(name: "ProviderPluginManaging", package: "ProviderPluginManaging"),
                .product(name: "ProviderWebServer", package: "ProviderWebServer"),
                .product(name: "ProviderLifecycleHooks", package: "ProviderLifecycleHooks"),
            ],
            path: "Sources/FactoryLumi2"
        ),
        .testTarget(
            name: "FactoryLumi2Tests",
            dependencies: [
                "FactoryLumi2",
                .product(name: "ProviderLLMManager", package: "ProviderLLMManager"),
                .product(name: "PluginLLMProviderAiRouter", package: "PluginLLMProviderAiRouter"),
                .product(name: "PluginLLMProviderAliyun", package: "PluginLLMProviderAliyun"),
                .product(name: "PluginLLMProviderAnthropic", package: "PluginLLMProviderAnthropic"),
                .product(name: "PluginLLMProviderDeepSeek", package: "PluginLLMProviderDeepSeek"),
                .product(name: "PluginLLMProviderFeifeimiao", package: "PluginLLMProviderFeifeimiao"),
                .product(name: "PluginLLMProviderFlyMux", package: "PluginLLMProviderFlyMux"),
                .product(name: "PluginLLMProviderHappyCode", package: "PluginLLMProviderHappyCode"),
                .product(name: "PluginLLMProviderHyperAPI", package: "PluginLLMProviderHyperAPI"),
                .product(name: "PluginLLMProviderKimiCode", package: "PluginLLMProviderKimiCode"),
                .product(name: "PluginLLMProviderLPgpt", package: "PluginLLMProviderLPgpt"),
                .product(name: "PluginLLMProviderMegaLLM", package: "PluginLLMProviderMegaLLM"),
                .product(name: "PluginLLMProviderMiniMax", package: "PluginLLMProviderMiniMax"),
                .product(name: "PluginLLMProviderSettings", package: "PluginLLMProviderSettings"),
                .product(name: "PluginLLMProviderOpenAI", package: "PluginLLMProviderOpenAI"),
                .product(name: "PluginLLMProviderOpenCode", package: "PluginLLMProviderOpenCode"),
                .product(name: "PluginLLMProviderOpenRouter", package: "PluginLLMProviderOpenRouter"),
                .product(name: "PluginLLMProviderStepFun", package: "PluginLLMProviderStepFun"),
                .product(name: "PluginLLMProviderSublyx", package: "PluginLLMProviderSublyx"),
                .product(name: "PluginLLMProviderXiaomi", package: "PluginLLMProviderXiaomi"),
                .product(name: "PluginLLMProviderXybbz", package: "PluginLLMProviderXybbz"),
                .product(name: "PluginLLMProviderZhipu", package: "PluginLLMProviderZhipu"),
                .product(name: "KitLLM", package: "KitLLM"),
                .product(name: "ProviderMessage", package: "ProviderMessage"),
                .product(name: "ProviderIdleTime", package: "ProviderIdleTime"),
                .product(name: "ProviderConversation", package: "ProviderConversation"),
                .product(name: "PluginConversationManager", package: "PluginConversationManager"),
            ]
        )
    ]
)
