// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "EditorPanelPlugin",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .library(
            name: "EditorPanelPlugin",
            targets: ["EditorPanelPlugin"]
        )
    ],
    dependencies: [
        .package(path: "../../Packages/AgentToolKit"),
        .package(path: "../../Packages/CodeEditLanguages"),
        .package(path: "../../Packages/LumiCodeEditSourceEditor"),
        .package(path: "../../Packages/CodeEditTextView"),
        .package(path: "../../Packages/EditorOverlayKit"),
        .package(path: "../../Packages/EditorService"),
        .package(path: "../../Packages/FilePreviewKit"),
        .package(path: "../../Packages/LumiCoreKit"),
        .package(path: "../../Packages/LumiUI"),
        .package(path: "../../Packages/MarkdownKit"),
        .package(path: "../../Packages/SuperLogKit"),
        .package(path: "../LayoutPlugin"),
        .package(path: "../EditorTabStripPlugin"),
        .package(path: "../EditorBreadcrumbPlugin"),
        .package(path: "../EditorRailFileTreePlugin"),
        .package(path: "../EditorStickySymbolBarPlugin"),
        .package(path: "../EditorBottomProblemsPlugin"),
        .package(path: "../EditorBottomReferencesPlugin"),
        .package(path: "../EditorBottomSymbolsPlugin"),
        .package(path: "../EditorBottomSearchPlugin"),
        .package(path: "../EditorBottomCallHierarchyPlugin"),
        .package(path: "../EditorBottomTerminalPlugin"),
        .package(path: "../EditorPreviewPlugin"),
        .package(path: "../EditorXcodePlugin"),
        .package(path: "../LSPServiceEditorPlugin"),
        .package(path: "../LSPRealtimeSignalsEditorPlugin"),
        .package(path: "../LSPSheetsEditorPlugin"),
        .package(path: "../LSPToolbarEditorPlugin"),
        .package(path: "../LSPCodeActionEditorPlugin"),
        .package(path: "../LSPCallHierarchyEditorPlugin"),
        .package(path: "../LSPWorkspaceSymbolEditorPlugin"),
        .package(path: "../LSPDocumentHighlightEditorPlugin"),
        .package(path: "../LSPInlayHintEditorPlugin"),
        .package(path: "../LSPSignatureHelpEditorPlugin"),
        .package(path: "../LSPFoldingRangeEditorPlugin"),
        .package(path: "../LSPDocumentColorEditorPlugin"),
        .package(path: "../LSPDocumentLinkEditorPlugin"),
        .package(path: "../LSPSelectionRangeEditorPlugin"),
        .package(path: "../EditorLSPContextCommandsPlugin"),
        .package(path: "../EditorMultiCursorCommandsPlugin"),
        .package(path: "../VueEditorPlugin"),
        .package(path: "../JSEditorPlugin"),
        .package(path: "../GoEditorPlugin"),
        .package(path: "../HTMLEditorPlugin"),
        .package(path: "../CSSEditorPlugin"),
        .package(path: "../MarkdownEditorPlugin"),
        .package(path: "../SwiftPrimitiveTypesEditorPlugin"),
        .package(path: "../SwiftSelectionCodeActionEditorPlugin"),
        .package(path: "../EditorSwiftKeywordHoverPlugin"),
    ],
    targets: [
        .target(
            name: "EditorPanelPlugin",
            dependencies: [
                .product(name: "AgentToolKit", package: "AgentToolKit"),
                .product(name: "CodeEditLanguages", package: "CodeEditLanguages"),
                .product(name: "CodeEditSourceEditor", package: "LumiCodeEditSourceEditor"),
                .product(name: "CodeEditTextView", package: "CodeEditTextView"),
                .product(name: "EditorOverlayKit", package: "EditorOverlayKit"),
                .product(name: "EditorService", package: "EditorService"),
                .product(name: "FilePreviewKit", package: "FilePreviewKit"),
                .product(name: "LumiCoreKit", package: "LumiCoreKit"),
                .product(name: "LumiUI", package: "LumiUI"),
                .product(name: "MarkdownKit", package: "MarkdownKit"),
                .product(name: "SuperLogKit", package: "SuperLogKit"),
                .product(name: "LayoutPlugin", package: "LayoutPlugin"),
                .product(name: "EditorTabStripPlugin", package: "EditorTabStripPlugin"),
                .product(name: "EditorBreadcrumbPlugin", package: "EditorBreadcrumbPlugin"),
                .product(name: "EditorRailFileTreePlugin", package: "EditorRailFileTreePlugin"),
                .product(name: "EditorStickySymbolBarPlugin", package: "EditorStickySymbolBarPlugin"),
                .product(name: "EditorBottomProblemsPlugin", package: "EditorBottomProblemsPlugin"),
                .product(name: "EditorBottomReferencesPlugin", package: "EditorBottomReferencesPlugin"),
                .product(name: "EditorBottomSymbolsPlugin", package: "EditorBottomSymbolsPlugin"),
                .product(name: "EditorBottomSearchPlugin", package: "EditorBottomSearchPlugin"),
                .product(name: "EditorBottomCallHierarchyPlugin", package: "EditorBottomCallHierarchyPlugin"),
                .product(name: "EditorBottomTerminalPlugin", package: "EditorBottomTerminalPlugin"),
                .product(name: "EditorPreviewPlugin", package: "EditorPreviewPlugin"),
                .product(name: "EditorXcodePlugin", package: "EditorXcodePlugin"),
                .product(name: "LSPServiceEditorPlugin", package: "LSPServiceEditorPlugin"),
                .product(name: "LSPRealtimeSignalsEditorPlugin", package: "LSPRealtimeSignalsEditorPlugin"),
                .product(name: "LSPSheetsEditorPlugin", package: "LSPSheetsEditorPlugin"),
                .product(name: "LSPToolbarEditorPlugin", package: "LSPToolbarEditorPlugin"),
                .product(name: "LSPCodeActionEditorPlugin", package: "LSPCodeActionEditorPlugin"),
                .product(name: "LSPCallHierarchyEditorPlugin", package: "LSPCallHierarchyEditorPlugin"),
                .product(name: "LSPWorkspaceSymbolEditorPlugin", package: "LSPWorkspaceSymbolEditorPlugin"),
                .product(name: "LSPDocumentHighlightEditorPlugin", package: "LSPDocumentHighlightEditorPlugin"),
                .product(name: "LSPInlayHintEditorPlugin", package: "LSPInlayHintEditorPlugin"),
                .product(name: "LSPSignatureHelpEditorPlugin", package: "LSPSignatureHelpEditorPlugin"),
                .product(name: "LSPFoldingRangeEditorPlugin", package: "LSPFoldingRangeEditorPlugin"),
                .product(name: "LSPDocumentColorEditorPlugin", package: "LSPDocumentColorEditorPlugin"),
                .product(name: "LSPDocumentLinkEditorPlugin", package: "LSPDocumentLinkEditorPlugin"),
                .product(name: "LSPSelectionRangeEditorPlugin", package: "LSPSelectionRangeEditorPlugin"),
                .product(name: "EditorLSPContextCommandsPlugin", package: "EditorLSPContextCommandsPlugin"),
                .product(name: "EditorMultiCursorCommandsPlugin", package: "EditorMultiCursorCommandsPlugin"),
                .product(name: "VueEditorPlugin", package: "VueEditorPlugin"),
                .product(name: "JSEditorPlugin", package: "JSEditorPlugin"),
                .product(name: "GoEditorPlugin", package: "GoEditorPlugin"),
                .product(name: "HTMLEditorPlugin", package: "HTMLEditorPlugin"),
                .product(name: "CSSEditorPlugin", package: "CSSEditorPlugin"),
                .product(name: "MarkdownEditorPlugin", package: "MarkdownEditorPlugin"),
                .product(name: "SwiftPrimitiveTypesEditorPlugin", package: "SwiftPrimitiveTypesEditorPlugin"),
                .product(name: "SwiftSelectionCodeActionEditorPlugin", package: "SwiftSelectionCodeActionEditorPlugin"),
                .product(name: "EditorSwiftKeywordHoverPlugin", package: "EditorSwiftKeywordHoverPlugin"),
            ],
            path: ".",
            exclude: ["Tests", "README.md"],
            sources: ["Sources"],
            resources: [
                .process("Resources")
            ]
        ),
        .testTarget(
            name: "EditorPanelPluginTests",
            dependencies: ["EditorPanelPlugin"],
            path: "Tests"
        )
    ]
)
