// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "LumiPluginRegistry",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .library(
            name: "LumiPluginRegistry",
            targets: ["LumiPluginRegistry"]
        )
    ],
    dependencies: [
        .package(path: "../LumiCoreKit"),
        .package(path: "../../Plugins/ThemeLumiPlugin"),
        .package(path: "../../Plugins/ThemeMidnightPlugin"),
        .package(path: "../../Plugins/ThemeSkyPlugin"),
        .package(path: "../../Plugins/ThemeAuroraPlugin"),
        .package(path: "../../Plugins/ThemeNebulaPlugin"),
        .package(path: "../../Plugins/ThemeVoidPlugin"),
        .package(path: "../../Plugins/ThemeSpringPlugin"),
        .package(path: "../../Plugins/ThemeSummerPlugin"),
        .package(path: "../../Plugins/ThemeAutumnPlugin"),
        .package(path: "../../Plugins/ThemeWinterPlugin"),
        .package(path: "../../Plugins/ThemeGithubPlugin"),
        .package(path: "../../Plugins/ThemeOrchardPlugin"),
        .package(path: "../../Plugins/ThemeMountainPlugin"),
        .package(path: "../../Plugins/ThemeVscodeDarkPlugin"),
        .package(path: "../../Plugins/ThemeRiverPlugin"),
        .package(path: "../../Plugins/ThemeVscodeLightPlugin"),
        .package(path: "../../Plugins/ThemeOneDarkPlugin"),
        .package(path: "../../Plugins/ThemeDraculaPlugin"),
        .package(path: "../../Plugins/ThemeStatusBarPlugin"),
        .package(path: "../../Plugins/DeviceInfoPlugin"),
        .package(path: "../../Plugins/NetworkManagerPlugin"),
        .package(path: "../../Plugins/ChatPanelPlugin"),
        .package(path: "../../Plugins/LLMProviderOpenAIPlugin"),
        .package(path: "../../Plugins/LLMProviderZhipuPlugin"),
        .package(path: "../../Plugins/LLMProviderAiRouterPlugin"),
        .package(path: "../../Plugins/LLMProviderAliyunPlugin"),
        .package(path: "../../Plugins/LLMProviderAnthropicPlugin"),
        .package(path: "../../Plugins/LLMProviderDeepSeekPlugin"),
        .package(path: "../../Plugins/LLMProviderFeifeimiaoPlugin"),
        .package(path: "../../Plugins/LLMProviderFlyMuxPlugin"),
        .package(path: "../../Plugins/LLMProviderFreeModelPlugin"),
        .package(path: "../../Plugins/LLMProviderHappyCodePlugin"),
        .package(path: "../../Plugins/LLMProviderHyperAPIPlugin"),
        .package(path: "../../Plugins/LLMProviderLPgptPlugin"),
        .package(path: "../../Plugins/LLMProviderMegaLLMPlugin"),
        .package(path: "../../Plugins/LLMProviderOpenRouterPlugin"),
        .package(path: "../../Plugins/LLMProviderXiaomiPlugin"),
        .package(path: "../../Plugins/LLMProviderXybbzPlugin"),
        .package(path: "../../Plugins/LLMProviderCodexPlugin"),
        .package(path: "../../Plugins/LLMProviderMLXPlugin"),
        .package(path: "../../Plugins/ProjectsPlugin"),
        .package(path: "../../Plugins/AppManagerPlugin"),
        .package(path: "../../Plugins/DiskManagerPlugin"),
        .package(path: "../../Plugins/PortManagerPlugin"),
        .package(path: "../../Plugins/ToolCorePlugin"),
        .package(path: "../../Plugins/MessageRendererPlugin"),
        .package(path: "../../Plugins/AgentRulesPlugin"),
        .package(path: "../../Plugins/SkillPlugin"),
        .package(path: "../../Plugins/MemoryPlugin"),
        .package(path: "../../Plugins/AgentRAGPlugin"),
        .package(path: "../../Plugins/RequestLogPlugin"),
        .package(path: "../../Plugins/HistoryDBStatusBarPlugin"),
        .package(path: "../../Plugins/ConversationTitlePlugin"),
        .package(path: "../../Plugins/ConversationListPlugin"),
        .package(path: "../../Plugins/AutoTaskPlugin"),
        .package(path: "../../Plugins/GitHubPlugin"),
        .package(path: "../../Plugins/IdleTimePlugin"),
        .package(path: "../../Plugins/ProjectIssueScannerPlugin"),
        .package(path: "../../Plugins/DockerManagerPlugin"),
        .package(path: "../../Plugins/BrewManagerPlugin"),
        .package(path: "../../Plugins/ClipboardManagerPlugin"),
        .package(path: "../../Plugins/HostsManagerPlugin"),
        .package(path: "../../Plugins/InputPlugin"),
        .package(path: "../../Plugins/NettoPlugin"),
        .package(path: "../../Plugins/RClickPlugin"),
        .package(path: "../../Plugins/RegistryManagerPlugin"),
        .package(path: "../../Plugins/AppStoreConnectPlugin"),
        .package(path: "../../Plugins/TerminalPlugin"),
        .package(path: "../../Plugins/MenuBarManagerPlugin"),
        .package(path: "../../Plugins/QuickLauncherPlugin"),
        .package(path: "../../Plugins/AppUpdateStatusBarPlugin"),
        .package(path: "../../Plugins/AppLoadedPluginsPlugin"),
        .package(path: "../../Plugins/FontConfigPlugin"),
        .package(path: "../../Plugins/OpenInCursorPlugin"),
        .package(path: "../../Plugins/OpenInXcodePlugin"),
        .package(path: "../../Plugins/OpenInFinderPlugin"),
        .package(path: "../../Plugins/OpenInGitOKPlugin"),
        .package(path: "../../Plugins/OpenInGitHubDesktopPlugin"),
        .package(path: "../../Plugins/OpenInAntigravityPlugin"),
        .package(path: "../../Plugins/OpenRemotePlugin"),
        .package(path: "../../Plugins/LayoutPlugin"),
        .package(path: "../../Plugins/OnboardingPlugin"),
        .package(path: "../../Plugins/AgentTurnNotificationPlugin"),
        .package(path: "../../Plugins/FileLogPlugin"),
        .package(path: "../../Plugins/WebSearchPlugin"),
        .package(path: "../../Plugins/WebFetchPlugin"),
        .package(path: "../../Plugins/GitPlugin"),
        .package(path: "../../Plugins/AskUserPlugin"),
        .package(path: "../../Plugins/CaffeinatePlugin"),
        .package(path: "../../Plugins/BrowserPlugin"),
        .package(path: "../../Plugins/ProjectOverviewPlugin"),
        .package(path: "../../Plugins/ShowImagePlugin"),
        .package(path: "../../Plugins/AgentGitHubToolsPlugin"),
        .package(path: "../../Plugins/MultiAgentPlugin"),
        .package(path: "../../Plugins/DatabaseManagerPlugin"),
        .package(path: "../../Plugins/CodeReviewPlugin"),
        .package(path: "../../Plugins/AgentDelayMessagePlugin"),
        .package(path: "../../Plugins/LLMAvailabilityPlugin"),
        .package(path: "../../Plugins/EditorPanelPlugin"),
        .package(path: "../../Plugins/EditorBreadcrumbNavPlugin"),
        .package(path: "../../Plugins/EditorTabStripPlugin"),
        .package(path: "../../Plugins/EditorStickySymbolBarPlugin"),
        .package(path: "../../Plugins/EditorBottomProblemsPlugin"),
        .package(path: "../../Plugins/EditorBottomReferencesPlugin"),
        .package(path: "../../Plugins/EditorBottomSearchPlugin"),
        .package(path: "../../Plugins/EditorBottomSymbolsPlugin"),
        .package(path: "../../Plugins/EditorBottomCallHierarchyPlugin"),
        .package(path: "../../Plugins/EditorPreviewPlugin"),
        .package(path: "../../Plugins/EditorBottomTerminalPlugin"),
        .package(path: "../../Plugins/EditorRailFileTreePlugin"),
        .package(path: "../../Plugins/EditorOutlineRailPlugin"),
        .package(path: "../../Plugins/EditorRailProblemsPlugin"),
        .package(path: "../../Plugins/EditorRailReferencesPlugin"),
        .package(path: "../../Plugins/EditorRailSearchPlugin"),
        .package(path: "../../Plugins/EditorRailSymbolsPlugin"),
        .package(path: "../../Plugins/EditorRailCallHierarchyPlugin"),
        .package(path: "../../Plugins/LSPSignatureHelpEditorPlugin"),
        .package(path: "../../Plugins/LSPRealtimeSignalsEditorPlugin"),
        .package(path: "../../Plugins/LSPDocumentHighlightEditorPlugin"),
        .package(path: "../../Plugins/EditorJSPlugin"),
        .package(path: "../../Plugins/EditorGoPlugin"),
        .package(path: "../../Plugins/LSPServiceEditorPlugin"),
        .package(path: "../../Plugins/LSPSheetsEditorPlugin"),
        .package(path: "../../Plugins/LSPToolbarEditorPlugin"),
        .package(path: "../../Plugins/LSPCodeActionEditorPlugin"),
        .package(path: "../../Plugins/LSPCallHierarchyEditorPlugin"),
        .package(path: "../../Plugins/LSPWorkspaceSymbolEditorPlugin"),
        .package(path: "../../Plugins/LSPInlayHintEditorPlugin"),
        .package(path: "../../Plugins/LSPFoldingRangeEditorPlugin"),
        .package(path: "../../Plugins/LSPDocumentColorEditorPlugin"),
        .package(path: "../../Plugins/LSPDocumentLinkEditorPlugin"),
        .package(path: "../../Plugins/LSPSelectionRangeEditorPlugin"),
        .package(path: "../../Plugins/EditorLSPContextCommandsPlugin"),
        .package(path: "../../Plugins/EditorMultiCursorCommandsPlugin"),
        .package(path: "../../Plugins/EditorVuePlugin"),
        .package(path: "../../Plugins/EditorHTMLPlugin"),
        .package(path: "../../Plugins/EditorCSSPlugin"),
        .package(path: "../../Plugins/EditorMarkdownPlugin"),
        .package(path: "../../Plugins/EditorSwiftPrimitiveTypesPlugin"),
        .package(path: "../../Plugins/EditorSwiftSelectionCodeActionPlugin"),
        .package(path: "../../Plugins/EditorSwiftKeywordHoverPlugin"),
        .package(path: "../EditorService"),
        .package(path: "../../Plugins/AppIconDesignerPlugin"),
        .package(path: "../../Plugins/DisplayControlPlugin")
    ],
    targets: [
        .target(
            name: "LumiPluginRegistry",
            dependencies: [
                "LumiCoreKit",
                .product(name: "ThemeLumiPlugin", package: "ThemeLumiPlugin"),
                .product(name: "ThemeMidnightPlugin", package: "ThemeMidnightPlugin"),
                .product(name: "ThemeSkyPlugin", package: "ThemeSkyPlugin"),
                .product(name: "ThemeAuroraPlugin", package: "ThemeAuroraPlugin"),
                .product(name: "ThemeNebulaPlugin", package: "ThemeNebulaPlugin"),
                .product(name: "ThemeVoidPlugin", package: "ThemeVoidPlugin"),
                .product(name: "ThemeSpringPlugin", package: "ThemeSpringPlugin"),
                .product(name: "ThemeSummerPlugin", package: "ThemeSummerPlugin"),
                .product(name: "ThemeAutumnPlugin", package: "ThemeAutumnPlugin"),
                .product(name: "ThemeWinterPlugin", package: "ThemeWinterPlugin"),
                .product(name: "ThemeGithubPlugin", package: "ThemeGithubPlugin"),
                .product(name: "ThemeOrchardPlugin", package: "ThemeOrchardPlugin"),
                .product(name: "ThemeMountainPlugin", package: "ThemeMountainPlugin"),
                .product(name: "ThemeVscodeDarkPlugin", package: "ThemeVscodeDarkPlugin"),
                .product(name: "ThemeRiverPlugin", package: "ThemeRiverPlugin"),
                .product(name: "ThemeVscodeLightPlugin", package: "ThemeVscodeLightPlugin"),
                .product(name: "ThemeOneDarkPlugin", package: "ThemeOneDarkPlugin"),
                .product(name: "ThemeDraculaPlugin", package: "ThemeDraculaPlugin"),
                .product(name: "ThemeStatusBarPlugin", package: "ThemeStatusBarPlugin"),
                .product(name: "DeviceInfoPlugin", package: "DeviceInfoPlugin"),
                .product(name: "NetworkManagerPlugin", package: "NetworkManagerPlugin"),
                .product(name: "ChatPanelPlugin", package: "ChatPanelPlugin"),
                .product(name: "LLMProviderOpenAIPlugin", package: "LLMProviderOpenAIPlugin"),
                .product(name: "LLMProviderZhipuPlugin", package: "LLMProviderZhipuPlugin"),
                .product(name: "LLMProviderAiRouterPlugin", package: "LLMProviderAiRouterPlugin"),
                .product(name: "LLMProviderAliyunPlugin", package: "LLMProviderAliyunPlugin"),
                .product(name: "LLMProviderAnthropicPlugin", package: "LLMProviderAnthropicPlugin"),
                .product(name: "LLMProviderDeepSeekPlugin", package: "LLMProviderDeepSeekPlugin"),
                .product(name: "LLMProviderFeifeimiaoPlugin", package: "LLMProviderFeifeimiaoPlugin"),
                .product(name: "LLMProviderFlyMuxPlugin", package: "LLMProviderFlyMuxPlugin"),
                .product(name: "LLMProviderFreeModelPlugin", package: "LLMProviderFreeModelPlugin"),
                .product(name: "LLMProviderHappyCodePlugin", package: "LLMProviderHappyCodePlugin"),
                .product(name: "LLMProviderHyperAPIPlugin", package: "LLMProviderHyperAPIPlugin"),
                .product(name: "LLMProviderLPgptPlugin", package: "LLMProviderLPgptPlugin"),
                .product(name: "LLMProviderMegaLLMPlugin", package: "LLMProviderMegaLLMPlugin"),
                .product(name: "LLMProviderOpenRouterPlugin", package: "LLMProviderOpenRouterPlugin"),
                .product(name: "LLMProviderXiaomiPlugin", package: "LLMProviderXiaomiPlugin"),
                .product(name: "LLMProviderXybbzPlugin", package: "LLMProviderXybbzPlugin"),
                .product(name: "LLMProviderCodexPlugin", package: "LLMProviderCodexPlugin"),
                .product(name: "LLMProviderMLXPlugin", package: "LLMProviderMLXPlugin"),
                "ProjectsPlugin",
                .product(name: "AppManagerPlugin", package: "AppManagerPlugin"),
                .product(name: "DiskManagerPlugin", package: "DiskManagerPlugin"),
                .product(name: "PortManagerPlugin", package: "PortManagerPlugin"),
                .product(name: "ToolCorePlugin", package: "ToolCorePlugin"),
                .product(name: "MessageRendererPlugin", package: "MessageRendererPlugin"),
                .product(name: "AgentRulesPlugin", package: "AgentRulesPlugin"),
                .product(name: "SkillPlugin", package: "SkillPlugin"),
                .product(name: "MemoryPlugin", package: "MemoryPlugin"),
                .product(name: "AgentRAGPlugin", package: "AgentRAGPlugin"),
                .product(name: "RequestLogPlugin", package: "RequestLogPlugin"),
                .product(name: "HistoryDBStatusBarPlugin", package: "HistoryDBStatusBarPlugin"),
                .product(name: "ConversationTitlePlugin", package: "ConversationTitlePlugin"),
                .product(name: "ConversationListPlugin", package: "ConversationListPlugin"),
                .product(name: "AutoTaskPlugin", package: "AutoTaskPlugin"),
                .product(name: "GitHubPlugin", package: "GitHubPlugin"),
                .product(name: "IdleTimePlugin", package: "IdleTimePlugin"),
                .product(name: "ProjectIssueScannerPlugin", package: "ProjectIssueScannerPlugin"),
                .product(name: "DockerManagerPlugin", package: "DockerManagerPlugin"),
                .product(name: "BrewManagerPlugin", package: "BrewManagerPlugin"),
                .product(name: "ClipboardManagerPlugin", package: "ClipboardManagerPlugin"),
                .product(name: "HostsManagerPlugin", package: "HostsManagerPlugin"),
                .product(name: "InputPlugin", package: "InputPlugin"),
                .product(name: "NettoPlugin", package: "NettoPlugin"),
                .product(name: "RClickPlugin", package: "RClickPlugin"),
                .product(name: "RegistryManagerPlugin", package: "RegistryManagerPlugin"),
                .product(name: "AppStoreConnectPlugin", package: "AppStoreConnectPlugin"),
                .product(name: "TerminalPlugin", package: "TerminalPlugin"),
                .product(name: "MenuBarManagerPlugin", package: "MenuBarManagerPlugin"),
                .product(name: "QuickLauncherPlugin", package: "QuickLauncherPlugin"),
                .product(name: "AppUpdateStatusBarPlugin", package: "AppUpdateStatusBarPlugin"),
                .product(name: "AppLoadedPluginsPlugin", package: "AppLoadedPluginsPlugin"),
                .product(name: "FontConfigPlugin", package: "FontConfigPlugin"),
                .product(name: "OpenInCursorPlugin", package: "OpenInCursorPlugin"),
                .product(name: "OpenInXcodePlugin", package: "OpenInXcodePlugin"),
                .product(name: "OpenInFinderPlugin", package: "OpenInFinderPlugin"),
                .product(name: "OpenInGitOKPlugin", package: "OpenInGitOKPlugin"),
                .product(name: "OpenInGitHubDesktopPlugin", package: "OpenInGitHubDesktopPlugin"),
                .product(name: "OpenInAntigravityPlugin", package: "OpenInAntigravityPlugin"),
                .product(name: "OpenRemotePlugin", package: "OpenRemotePlugin"),
                .product(name: "LayoutPlugin", package: "LayoutPlugin"),
                .product(name: "OnboardingPlugin", package: "OnboardingPlugin"),
                .product(name: "AgentTurnNotificationPlugin", package: "AgentTurnNotificationPlugin"),
                .product(name: "FileLogPlugin", package: "FileLogPlugin"),
                .product(name: "WebSearchPlugin", package: "WebSearchPlugin"),
                .product(name: "WebFetchPlugin", package: "WebFetchPlugin"),
                .product(name: "GitPlugin", package: "GitPlugin"),
                .product(name: "AskUserPlugin", package: "AskUserPlugin"),
                .product(name: "CaffeinatePlugin", package: "CaffeinatePlugin"),
                .product(name: "BrowserPlugin", package: "BrowserPlugin"),
                .product(name: "ProjectOverviewPlugin", package: "ProjectOverviewPlugin"),
                .product(name: "ShowImagePlugin", package: "ShowImagePlugin"),
                .product(name: "AgentGitHubToolsPlugin", package: "AgentGitHubToolsPlugin"),
                .product(name: "MultiAgentPlugin", package: "MultiAgentPlugin"),
                .product(name: "DatabaseManagerPlugin", package: "DatabaseManagerPlugin"),
                .product(name: "CodeReviewPlugin", package: "CodeReviewPlugin"),
                .product(name: "AgentDelayMessagePlugin", package: "AgentDelayMessagePlugin"),
                .product(name: "LLMAvailabilityPlugin", package: "LLMAvailabilityPlugin"),
                .product(name: "EditorPanelPlugin", package: "EditorPanelPlugin"),
                .product(name: "EditorBreadcrumbNavPlugin", package: "EditorBreadcrumbNavPlugin"),
                .product(name: "EditorTabStripPlugin", package: "EditorTabStripPlugin"),
                .product(name: "EditorStickySymbolBarPlugin", package: "EditorStickySymbolBarPlugin"),
                .product(name: "EditorBottomProblemsPlugin", package: "EditorBottomProblemsPlugin"),
                .product(name: "EditorBottomReferencesPlugin", package: "EditorBottomReferencesPlugin"),
                .product(name: "EditorBottomSearchPlugin", package: "EditorBottomSearchPlugin"),
                .product(name: "EditorBottomSymbolsPlugin", package: "EditorBottomSymbolsPlugin"),
                .product(name: "EditorBottomCallHierarchyPlugin", package: "EditorBottomCallHierarchyPlugin"),
                .product(name: "EditorPreviewPlugin", package: "EditorPreviewPlugin"),
                .product(name: "EditorBottomTerminalPlugin", package: "EditorBottomTerminalPlugin"),
                .product(name: "EditorRailFileTreePlugin", package: "EditorRailFileTreePlugin"),
                .product(name: "EditorOutlineRailPlugin", package: "EditorOutlineRailPlugin"),
                .product(name: "EditorRailProblemsPlugin", package: "EditorRailProblemsPlugin"),
                .product(name: "EditorRailReferencesPlugin", package: "EditorRailReferencesPlugin"),
                .product(name: "EditorRailSearchPlugin", package: "EditorRailSearchPlugin"),
                .product(name: "EditorRailSymbolsPlugin", package: "EditorRailSymbolsPlugin"),
                .product(name: "EditorRailCallHierarchyPlugin", package: "EditorRailCallHierarchyPlugin"),
                .product(name: "LSPSignatureHelpEditorPlugin", package: "LSPSignatureHelpEditorPlugin"),
                .product(name: "LSPRealtimeSignalsEditorPlugin", package: "LSPRealtimeSignalsEditorPlugin"),
                .product(name: "LSPDocumentHighlightEditorPlugin", package: "LSPDocumentHighlightEditorPlugin"),
                .product(name: "EditorJSPlugin", package: "EditorJSPlugin"),
                .product(name: "EditorGoPlugin", package: "EditorGoPlugin"),
                .product(name: "LSPServiceEditorPlugin", package: "LSPServiceEditorPlugin"),
                .product(name: "EditorService", package: "EditorService"),
                .product(name: "LSPSheetsEditorPlugin", package: "LSPSheetsEditorPlugin"),
                .product(name: "LSPToolbarEditorPlugin", package: "LSPToolbarEditorPlugin"),
                .product(name: "LSPCodeActionEditorPlugin", package: "LSPCodeActionEditorPlugin"),
                .product(name: "LSPCallHierarchyEditorPlugin", package: "LSPCallHierarchyEditorPlugin"),
                .product(name: "LSPWorkspaceSymbolEditorPlugin", package: "LSPWorkspaceSymbolEditorPlugin"),
                .product(name: "LSPInlayHintEditorPlugin", package: "LSPInlayHintEditorPlugin"),
                .product(name: "LSPFoldingRangeEditorPlugin", package: "LSPFoldingRangeEditorPlugin"),
                .product(name: "LSPDocumentColorEditorPlugin", package: "LSPDocumentColorEditorPlugin"),
                .product(name: "LSPDocumentLinkEditorPlugin", package: "LSPDocumentLinkEditorPlugin"),
                .product(name: "LSPSelectionRangeEditorPlugin", package: "LSPSelectionRangeEditorPlugin"),
                .product(name: "EditorLSPContextCommandsPlugin", package: "EditorLSPContextCommandsPlugin"),
                .product(name: "EditorMultiCursorCommandsPlugin", package: "EditorMultiCursorCommandsPlugin"),
                .product(name: "EditorVuePlugin", package: "EditorVuePlugin"),
                .product(name: "EditorHTMLPlugin", package: "EditorHTMLPlugin"),
                .product(name: "EditorCSSPlugin", package: "EditorCSSPlugin"),
                .product(name: "EditorMarkdownPlugin", package: "EditorMarkdownPlugin"),
                .product(name: "EditorSwiftPrimitiveTypesPlugin", package: "EditorSwiftPrimitiveTypesPlugin"),
                .product(name: "EditorSwiftSelectionCodeActionPlugin", package: "EditorSwiftSelectionCodeActionPlugin"),
                .product(name: "EditorSwiftKeywordHoverPlugin", package: "EditorSwiftKeywordHoverPlugin"),
                .product(name: "AppIconDesignerPlugin", package: "AppIconDesignerPlugin"),
                .product(name: "DisplayControlPlugin", package: "DisplayControlPlugin")
            ]
        )
    ]
)
