// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "LumiPluginRegistry",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .library(
            name: "LumiPluginRegistry",
            targets: ["LumiPluginRegistry"]
        )
    ],
    dependencies: [
        .package(path: "../LumiCoreKit"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeLumiPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeMidnightPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeSkyPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeAuroraPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeNebulaPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeVoidPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeSpringPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeSummerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeAutumnPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeWinterPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeGithubPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeOrchardPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeMountainPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeVscodePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeRiverPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeOneDarkPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeDraculaPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ThemeStatusBarPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/DeviceInfoPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/NetworkManagerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ChatPanelPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ModelSelectorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/MessageListPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderOpenAIPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderZhipuPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderAiRouterPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderAliyunPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderAnthropicPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderDeepSeekPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderFeifeimiaoPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderFlyMuxPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderFreeModelPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderHappyCodePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderHyperAPIPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderLPgptPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderMiniMaxPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderMegaLLMPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderOpenRouterPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderXiaomiPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderXybbzPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderSublyxPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderStepFunPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderCodexPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LLMProviderMLXPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ProjectsPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/AppManagerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/DiskManagerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/PortManagerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ToolCorePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/MessageRendererPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/AgentRulesPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/SkillPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/MemoryPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/AgentRAGPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/AgentTempStoragePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/RequestLogPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/HistoryDBStatusBarPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ActivityHeatmapPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ConversationTitlePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ConversationTimelinePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ConversationLanguagePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ChatModePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/VerbosityPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ConversationListPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ConversationNewPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ConversationForkPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/AutoTaskPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/GitHubPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/IdleTimePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ProjectIssueScannerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/DockerManagerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/BrewManagerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ClipboardManagerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/HostsManagerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/InputPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/NettoPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/RClickPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/RegistryManagerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/AppStoreConnectPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/TerminalPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/MenuBarManagerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/QuickFileSearchPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/QuickLauncherPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/AppUpdateStatusBarPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/AppLoadedPluginsPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/FontConfigPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/OpenInCursorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/OpenInXcodePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/OpenInFinderPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/OpenInGitOKPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/OpenInGitHubDesktopPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/OpenInAntigravityPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/OpenRemotePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LayoutPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/OnboardingPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/AgentTurnNotificationPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/FileLogPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/WebSearchPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/WebFetchPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/GitPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/AskUserPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/CaffeinatePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/BrowserPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ProjectOverviewPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/ShowImagePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/MultiAgentPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/DatabaseManagerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/CodeReviewPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/AgentDelayMessagePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorPanelPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorBreadcrumbNavPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorTabStripPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorStickySymbolBarPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorProblemsPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorReferencesPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorSearchPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorSymbolsPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorCallHierarchyPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorPreviewPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorTerminalPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorFileTreePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorFileTreeV2Plugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorOutlinePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPSignatureHelpEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPRealtimeSignalsPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPDocumentHighlightEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorJSPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorGoPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPServiceEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPSheetsEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPToolbarEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPCodeActionEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPCallHierarchyEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPWorkspaceSymbolEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPInlayHintEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPFoldingRangeEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPDocumentColorEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPDocumentLinkEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LSPSelectionRangeEditorPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorLSPContextCommandsPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorChatIntegrationPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorMinimapContextMenuPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorMultiCursorCommandsPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorHTMLPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorCSSPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorMarkdownPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorSwiftPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorAgdaPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorBashPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorCPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorCSharpPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorDartPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorDockerfilePlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorElixirPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorHaskellPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorJSONPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorJavaPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorJuliaPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorKotlinPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorLuaPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorOCamlPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorPHPPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorPerlPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorPythonPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorRegexPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorRubyPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorRustPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorSQLPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorScalaPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorTOMLPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorVerilogPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorYAMLPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/EditorZigPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../EditorService"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/AppIconDesignerPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/DisplayControlPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LogoSmartLightPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/LogoCofficPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/VideoConverterPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/DownloadPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/DocxReadPlugin"),
        .package(path: "../LumiLocalizationKit"),
        .package(path: "../../Plugins/CADDesignerPlugin")
        .package(path: "../LumiLocalizationKit"),
    ],
    targets: [
        .target(
            name: "LumiPluginRegistry",
            dependencies: [
                "LumiCoreKit",
                .product(name: "ThemeLumiPlugin", package: "ThemeLumiPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeMidnightPlugin", package: "ThemeMidnightPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeSkyPlugin", package: "ThemeSkyPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeAuroraPlugin", package: "ThemeAuroraPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeNebulaPlugin", package: "ThemeNebulaPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeVoidPlugin", package: "ThemeVoidPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeSpringPlugin", package: "ThemeSpringPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeSummerPlugin", package: "ThemeSummerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeAutumnPlugin", package: "ThemeAutumnPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeWinterPlugin", package: "ThemeWinterPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeGithubPlugin", package: "ThemeGithubPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeOrchardPlugin", package: "ThemeOrchardPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeMountainPlugin", package: "ThemeMountainPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeVscodePlugin", package: "ThemeVscodePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeRiverPlugin", package: "ThemeRiverPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeOneDarkPlugin", package: "ThemeOneDarkPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeDraculaPlugin", package: "ThemeDraculaPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ThemeStatusBarPlugin", package: "ThemeStatusBarPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "DeviceInfoPlugin", package: "DeviceInfoPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "NetworkManagerPlugin", package: "NetworkManagerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ChatPanelPlugin", package: "ChatPanelPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ModelSelectorPlugin", package: "ModelSelectorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "MessageListPlugin", package: "MessageListPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderOpenAIPlugin", package: "LLMProviderOpenAIPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderZhipuPlugin", package: "LLMProviderZhipuPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderAiRouterPlugin", package: "LLMProviderAiRouterPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderAliyunPlugin", package: "LLMProviderAliyunPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderAnthropicPlugin", package: "LLMProviderAnthropicPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderDeepSeekPlugin", package: "LLMProviderDeepSeekPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderFeifeimiaoPlugin", package: "LLMProviderFeifeimiaoPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderFlyMuxPlugin", package: "LLMProviderFlyMuxPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderFreeModelPlugin", package: "LLMProviderFreeModelPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderHappyCodePlugin", package: "LLMProviderHappyCodePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderHyperAPIPlugin", package: "LLMProviderHyperAPIPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderLPgptPlugin", package: "LLMProviderLPgptPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderMiniMaxPlugin", package: "LLMProviderMiniMaxPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderMegaLLMPlugin", package: "LLMProviderMegaLLMPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderOpenRouterPlugin", package: "LLMProviderOpenRouterPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderXiaomiPlugin", package: "LLMProviderXiaomiPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderXybbzPlugin", package: "LLMProviderXybbzPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderSublyxPlugin", package: "LLMProviderSublyxPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderStepFunPlugin", package: "LLMProviderStepFunPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderCodexPlugin", package: "LLMProviderCodexPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LLMProviderMLXPlugin", package: "LLMProviderMLXPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ProjectsPlugin", package: "ProjectsPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "AppManagerPlugin", package: "AppManagerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "DiskManagerPlugin", package: "DiskManagerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "PortManagerPlugin", package: "PortManagerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ToolCorePlugin", package: "ToolCorePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "MessageRendererPlugin", package: "MessageRendererPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "AgentRulesPlugin", package: "AgentRulesPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "SkillPlugin", package: "SkillPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "MemoryPlugin", package: "MemoryPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "AgentRAGPlugin", package: "AgentRAGPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "AgentTempStoragePlugin", package: "AgentTempStoragePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "RequestLogPlugin", package: "RequestLogPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "HistoryDBStatusBarPlugin", package: "HistoryDBStatusBarPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ActivityHeatmapPlugin", package: "ActivityHeatmapPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ConversationTitlePlugin", package: "ConversationTitlePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ConversationTimelinePlugin", package: "ConversationTimelinePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ConversationLanguagePlugin", package: "ConversationLanguagePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ChatModePlugin", package: "ChatModePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "VerbosityPlugin", package: "VerbosityPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ConversationListPlugin", package: "ConversationListPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ConversationNewPlugin", package: "ConversationNewPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ConversationForkPlugin", package: "ConversationForkPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "AutoTaskPlugin", package: "AutoTaskPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "GitHubPlugin", package: "GitHubPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "IdleTimePlugin", package: "IdleTimePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ProjectIssueScannerPlugin", package: "ProjectIssueScannerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "DockerManagerPlugin", package: "DockerManagerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "BrewManagerPlugin", package: "BrewManagerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ClipboardManagerPlugin", package: "ClipboardManagerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "HostsManagerPlugin", package: "HostsManagerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "InputPlugin", package: "InputPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "NettoPlugin", package: "NettoPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "RClickPlugin", package: "RClickPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "RegistryManagerPlugin", package: "RegistryManagerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "AppStoreConnectPlugin", package: "AppStoreConnectPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "TerminalPlugin", package: "TerminalPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "MenuBarManagerPlugin", package: "MenuBarManagerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "QuickFileSearchPlugin", package: "QuickFileSearchPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "QuickLauncherPlugin", package: "QuickLauncherPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "AppUpdateStatusBarPlugin", package: "AppUpdateStatusBarPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "AppLoadedPluginsPlugin", package: "AppLoadedPluginsPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "FontConfigPlugin", package: "FontConfigPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "OpenInCursorPlugin", package: "OpenInCursorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "OpenInXcodePlugin", package: "OpenInXcodePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "OpenInFinderPlugin", package: "OpenInFinderPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "OpenInGitOKPlugin", package: "OpenInGitOKPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "OpenInGitHubDesktopPlugin", package: "OpenInGitHubDesktopPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "OpenInAntigravityPlugin", package: "OpenInAntigravityPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "OpenRemotePlugin", package: "OpenRemotePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LayoutPlugin", package: "LayoutPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "OnboardingPlugin", package: "OnboardingPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "AgentTurnNotificationPlugin", package: "AgentTurnNotificationPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "FileLogPlugin", package: "FileLogPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "WebSearchPlugin", package: "WebSearchPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "WebFetchPlugin", package: "WebFetchPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "GitPlugin", package: "GitPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "AskUserPlugin", package: "AskUserPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "CaffeinatePlugin", package: "CaffeinatePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "BrowserPlugin", package: "BrowserPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ProjectOverviewPlugin", package: "ProjectOverviewPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "ShowImagePlugin", package: "ShowImagePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "MultiAgentPlugin", package: "MultiAgentPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "DatabaseManagerPlugin", package: "DatabaseManagerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "CodeReviewPlugin", package: "CodeReviewPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "AgentDelayMessagePlugin", package: "AgentDelayMessagePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorPanelPlugin", package: "EditorPanelPlugin"),                .product(name: "EditorBreadcrumbNavPlugin", package: "EditorBreadcrumbNavPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorTabStripPlugin", package: "EditorTabStripPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorStickySymbolBarPlugin", package: "EditorStickySymbolBarPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorProblemsPlugin", package: "EditorProblemsPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorReferencesPlugin", package: "EditorReferencesPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorSearchPlugin", package: "EditorSearchPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorSymbolsPlugin", package: "EditorSymbolsPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorCallHierarchyPlugin", package: "EditorCallHierarchyPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorPreviewPlugin", package: "EditorPreviewPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorTerminalPlugin", package: "EditorTerminalPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorFileTreePlugin", package: "EditorFileTreePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorFileTreeV2Plugin", package: "EditorFileTreeV2Plugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorOutlinePlugin", package: "EditorOutlinePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPSignatureHelpEditorPlugin", package: "LSPSignatureHelpEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPRealtimeSignalsPlugin", package: "LSPRealtimeSignalsPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPDocumentHighlightEditorPlugin", package: "LSPDocumentHighlightEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorJSPlugin", package: "EditorJSPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorGoPlugin", package: "EditorGoPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPServiceEditorPlugin", package: "LSPServiceEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorService", package: "EditorService"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPSheetsEditorPlugin", package: "LSPSheetsEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPToolbarEditorPlugin", package: "LSPToolbarEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPCodeActionEditorPlugin", package: "LSPCodeActionEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPCallHierarchyEditorPlugin", package: "LSPCallHierarchyEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPWorkspaceSymbolEditorPlugin", package: "LSPWorkspaceSymbolEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPInlayHintEditorPlugin", package: "LSPInlayHintEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPFoldingRangeEditorPlugin", package: "LSPFoldingRangeEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPDocumentColorEditorPlugin", package: "LSPDocumentColorEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPDocumentLinkEditorPlugin", package: "LSPDocumentLinkEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LSPSelectionRangeEditorPlugin", package: "LSPSelectionRangeEditorPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorLSPContextCommandsPlugin", package: "EditorLSPContextCommandsPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorChatIntegrationPlugin", package: "EditorChatIntegrationPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorMinimapContextMenuPlugin", package: "EditorMinimapContextMenuPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorMultiCursorCommandsPlugin", package: "EditorMultiCursorCommandsPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorHTMLPlugin", package: "EditorHTMLPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorCSSPlugin", package: "EditorCSSPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorMarkdownPlugin", package: "EditorMarkdownPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorSwiftPlugin", package: "EditorSwiftPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorAgdaPlugin", package: "EditorAgdaPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorBashPlugin", package: "EditorBashPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorCPlugin", package: "EditorCPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorCSharpPlugin", package: "EditorCSharpPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorDartPlugin", package: "EditorDartPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorDockerfilePlugin", package: "EditorDockerfilePlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorElixirPlugin", package: "EditorElixirPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorHaskellPlugin", package: "EditorHaskellPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorJSONPlugin", package: "EditorJSONPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorJavaPlugin", package: "EditorJavaPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorJuliaPlugin", package: "EditorJuliaPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorKotlinPlugin", package: "EditorKotlinPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorLuaPlugin", package: "EditorLuaPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorOCamlPlugin", package: "EditorOCamlPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorPHPPlugin", package: "EditorPHPPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorPerlPlugin", package: "EditorPerlPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorPythonPlugin", package: "EditorPythonPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorRegexPlugin", package: "EditorRegexPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorRubyPlugin", package: "EditorRubyPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorRustPlugin", package: "EditorRustPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorSQLPlugin", package: "EditorSQLPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorScalaPlugin", package: "EditorScalaPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorTOMLPlugin", package: "EditorTOMLPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorVerilogPlugin", package: "EditorVerilogPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorYAMLPlugin", package: "EditorYAMLPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "EditorZigPlugin", package: "EditorZigPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "AppIconDesignerPlugin", package: "AppIconDesignerPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "DisplayControlPlugin", package: "DisplayControlPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LogoSmartLightPlugin", package: "LogoSmartLightPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "LogoCofficPlugin", package: "LogoCofficPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "VideoConverterPlugin", package: "VideoConverterPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "DownloadPlugin", package: "DownloadPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "DocxReadPlugin", package: "DocxReadPlugin"),
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
                .product(name: "CADDesignerPlugin", package: "CADDesignerPlugin")
                .product(name: "LumiLocalizationKit", package: "LumiLocalizationKit"),
            ],
            path: "Sources",
            resources: [
                .process("../Resources")
            ]
        )
    ]
)
