// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "LumiPluginRegistry",
    platforms: [
        .macOS(.v14),
    ],
    products: [
        .library(name: "LumiPluginRegistry", targets: ["LumiPluginRegistry"]),
    ],
    dependencies: [
        .package(path: "../LumiCoreKit"),
        .package(path: "../../Plugins/AgentAvailableToolsPlugin"),
        .package(path: "../../Plugins/AgentContextSyncPlugin"),
        .package(path: "../../Plugins/AgentCoreToolsPlugin"),
        .package(path: "../../Plugins/AgentDelayMessagePlugin"),
        .package(path: "../../Plugins/AgentGitHubToolsPlugin"),
        .package(path: "../../Plugins/ConversationLanguagePlugin"),
        .package(path: "../../Plugins/AgentMCPToolsPlugin"),
        .package(path: "../../Plugins/MessageRendererPlugin"),
        .package(path: "../../Plugins/AgentRAGPlugin"),
        .package(path: "../../Plugins/AgentRulesPlugin"),
        .package(path: "../../Plugins/AgentTurnNotificationPlugin"),
        .package(path: "../../Plugins/AppIconDesignerPlugin"),
        .package(path: "../../Plugins/AppLoadedPluginsPlugin"),
        .package(path: "../../Plugins/AppManagerPlugin"),
        .package(path: "../../Plugins/AppStoreConnectPlugin"),
        .package(path: "../../Plugins/AppUpdateStatusBarPlugin"),
        .package(path: "../../Plugins/AskUserPlugin"),
        .package(path: "../../Plugins/AutoTaskPlugin"),
        .package(path: "../../Plugins/BrewManagerPlugin"),
        .package(path: "../../Plugins/BrowserPlugin"),
        .package(path: "../../Plugins/BrowserAgentPlugin"),
        .package(path: "../../Plugins/CSSEditorPlugin"),
        .package(path: "../../Plugins/CaffeinatePlugin"),
        .package(path: "../../Plugins/ChatAttachmentPlugin"),
        .package(path: "../../Plugins/ChatInputPlugin"),
        .package(path: "../../Plugins/MessageListPlugin"),
        .package(path: "../../Plugins/MessageSenderPlugin"),
        .package(path: "../../Plugins/SendQueuePlugin"),
        .package(path: "../../Plugins/ToolExecutorPlugin"),
        .package(path: "../../Plugins/TurnLifecyclePlugin"),
        .package(path: "../../Plugins/ChatModePlugin"),
        .package(path: "../../Plugins/ChatPanelPlugin"),
        .package(path: "../../Plugins/ChatPendingMessagesPlugin"),
        .package(path: "../../Plugins/ChatSubmitPlugin"),
        .package(path: "../../Plugins/ClipboardManagerPlugin"),
        .package(path: "../../Plugins/CodeReviewPlugin"),
        .package(path: "../../Plugins/ConversationListPlugin"),
        .package(path: "../../Plugins/ConversationNewPlugin"),
        .package(path: "../../Plugins/ConversationTimelinePlugin"),
        .package(path: "../../Plugins/ConversationTitlePlugin"),
        .package(path: "../../Plugins/DatabaseManagerPlugin"),
        .package(path: "../../Plugins/DeviceInfoPlugin"),
        .package(path: "../../Plugins/DiskManagerPlugin"),
        .package(path: "../../Plugins/DockerManagerPlugin"),
        .package(path: "../../Plugins/EditorBottomCallHierarchyPlugin"),
        .package(path: "../../Plugins/EditorBottomProblemsPlugin"),
        .package(path: "../../Plugins/EditorBottomReferencesPlugin"),
        .package(path: "../../Plugins/EditorBottomSearchPlugin"),
        .package(path: "../../Plugins/EditorBottomSymbolsPlugin"),
        .package(path: "../../Plugins/EditorBottomTerminalPlugin"),
        .package(path: "../../Plugins/EditorBreadcrumbPlugin"),
        .package(path: "../../Plugins/EditorCallHierarchyRailPlugin"),
        .package(path: "../../Plugins/EditorChatIntegrationPlugin"),
        .package(path: "../../Plugins/EditorLSPContextCommandsPlugin"),
        .package(path: "../../Plugins/EditorOutlineRailPlugin"),
        .package(path: "../../Plugins/EditorPanelPlugin"),
        .package(path: "../../Plugins/EditorPreviewPlugin"),
        .package(path: "../../Plugins/EditorRailFileTreePlugin"),
        .package(path: "../../Plugins/EditorRailProblemsPlugin"),
        .package(path: "../../Plugins/EditorRailReferencesPlugin"),
        .package(path: "../../Plugins/EditorRailWorkspaceSearchPlugin"),
        .package(path: "../../Plugins/EditorRailWorkspaceSymbolsPlugin"),
        .package(path: "../../Plugins/EditorStickySymbolBarPlugin"),
        .package(path: "../../Plugins/EditorSwiftKeywordHoverPlugin"),
        .package(path: "../../Plugins/EditorTabStripPlugin"),
        .package(path: "../../Plugins/EditorXcodePlugin"),
        .package(path: "../../Plugins/FileLogPlugin"),
        .package(path: "../../Plugins/FontConfigPlugin"),
        .package(path: "../../Plugins/GitPlugin"),
        .package(path: "../../Plugins/GitHubCLIDetectPlugin"),
        .package(path: "../../Plugins/GitHubInsightPlugin"),
        .package(path: "../../Plugins/GoEditorPlugin"),
        .package(path: "../../Plugins/HTMLEditorPlugin"),
        .package(path: "../../Plugins/HistoryDBStatusBarPlugin"),
        .package(path: "../../Plugins/HostsManagerPlugin"),
        .package(path: "../../Plugins/IdleTimePlugin"),
        .package(path: "../../Plugins/InputPlugin"),
        .package(path: "../../Plugins/JSEditorPlugin"),
        .package(path: "../../Plugins/LLMAvailabilityPlugin"),
        .package(path: "../../Plugins/LLMProviderAiRouterPlugin"),
        .package(path: "../../Plugins/LLMProviderAliyunPlugin"),
        .package(path: "../../Plugins/LLMProviderAnthropicPlugin"),
        .package(path: "../../Plugins/LLMProviderCodexPlugin"),
        .package(path: "../../Plugins/LLMProviderDeepSeekPlugin"),
        .package(path: "../../Plugins/LLMProviderFeifeimiaoPlugin"),
        .package(path: "../../Plugins/LLMProviderFlyMuxPlugin"),
        .package(path: "../../Plugins/LLMProviderFreeModelPlugin"),
        .package(path: "../../Plugins/LLMProviderHappyCodePlugin"),
        .package(path: "../../Plugins/LLMProviderHyperAPIPlugin"),
        .package(path: "../../Plugins/LLMProviderLPgptPlugin"),
        .package(path: "../../Plugins/LLMProviderMLXPlugin"),
        .package(path: "../../Plugins/LLMProviderMegaLLMPlugin"),
        .package(path: "../../Plugins/LLMProviderOpenAIPlugin"),
        .package(path: "../../Plugins/LLMProviderOpenRouterPlugin"),
        .package(path: "../../Plugins/LLMProviderXiaomiPlugin"),
        .package(path: "../../Plugins/LLMProviderXybbzPlugin"),
        .package(path: "../../Plugins/LLMProviderZhipuPlugin"),
        .package(path: "../../Plugins/LSPCallHierarchyEditorPlugin"),
        .package(path: "../../Plugins/LSPCodeActionEditorPlugin"),
        .package(path: "../../Plugins/LSPDocumentColorEditorPlugin"),
        .package(path: "../../Plugins/LSPDocumentHighlightEditorPlugin"),
        .package(path: "../../Plugins/LSPDocumentLinkEditorPlugin"),
        .package(path: "../../Plugins/LSPFoldingRangeEditorPlugin"),
        .package(path: "../../Plugins/LSPInlayHintEditorPlugin"),
        .package(path: "../../Plugins/LSPRealtimeSignalsEditorPlugin"),
        .package(path: "../../Plugins/LSPSelectionRangeEditorPlugin"),
        .package(path: "../../Plugins/LSPServiceEditorPlugin"),
        .package(path: "../../Plugins/LSPSheetsEditorPlugin"),
        .package(path: "../../Plugins/LSPSignatureHelpEditorPlugin"),
        .package(path: "../../Plugins/LSPToolbarEditorPlugin"),
        .package(path: "../../Plugins/LSPWorkspaceSymbolEditorPlugin"),
        .package(path: "../../Plugins/LayoutPlugin"),
        .package(path: "../../Plugins/MarkdownEditorPlugin"),
        .package(path: "../../Plugins/MemoryPlugin"),
        .package(path: "../../Plugins/MenuBarManagerPlugin"),
        .package(path: "../../Plugins/ModelPreferencePlugin"),
        .package(path: "../../Plugins/ModelSelectorPlugin"),
        .package(path: "../../Plugins/MultiAgentPlugin"),
        .package(path: "../../Plugins/MultiCursorCommandsEditorPlugin"),
        .package(path: "../../Plugins/NettoPlugin"),
        .package(path: "../../Plugins/NetworkManagerPlugin"),
        .package(path: "../../Plugins/OnboardingPlugin"),
        .package(path: "../../Plugins/OpenInAntigravityPlugin"),
        .package(path: "../../Plugins/OpenInCursorPlugin"),
        .package(path: "../../Plugins/OpenInFinderPlugin"),
        .package(path: "../../Plugins/OpenInGitHubDesktopPlugin"),
        .package(path: "../../Plugins/OpenInGitOKPlugin"),
        .package(path: "../../Plugins/OpenInXcodePlugin"),
        .package(path: "../../Plugins/OpenRemotePlugin"),
        .package(path: "../../Plugins/PortManagerPlugin"),
        .package(path: "../../Plugins/ProjectIssueScannerPlugin"),
        .package(path: "../../Plugins/ProjectOverviewPlugin"),
        .package(path: "../../Plugins/ProjectsPlugin"),
        .package(path: "../../Plugins/QuickFileSearchPlugin"),
        .package(path: "../../Plugins/QuickLauncherPlugin"),
        .package(path: "../../Plugins/RClickPlugin"),
        .package(path: "../../Plugins/RegistryManagerPlugin"),
        .package(path: "../../Plugins/RequestLogPlugin"),
        .package(path: "../../Plugins/SampleDecorationEditorPlugin"),
        .package(path: "../../Plugins/SampleInsightsEditorPlugin"),
        .package(path: "../../Plugins/ScreenshotPlugin"),
        .package(path: "../../Plugins/ShowImagePlugin"),
        .package(path: "../../Plugins/SkillPlugin"),
        .package(path: "../../Plugins/SwiftPrimitiveTypesEditorPlugin"),
        .package(path: "../../Plugins/SwiftSelectionCodeActionEditorPlugin"),
        .package(path: "../../Plugins/TerminalPlugin"),
        .package(path: "../../Plugins/TextActionsPlugin"),
        .package(path: "../../Plugins/ThemeAuroraPlugin"),
        .package(path: "../../Plugins/ThemeAutumnPlugin"),
        .package(path: "../../Plugins/ThemeDraculaPlugin"),
        .package(path: "../../Plugins/ThemeGithubPlugin"),
        .package(path: "../../Plugins/ThemeLumiPlugin"),
        .package(path: "../../Plugins/ThemeMidnightPlugin"),
        .package(path: "../../Plugins/ThemeMountainPlugin"),
        .package(path: "../../Plugins/ThemeNebulaPlugin"),
        .package(path: "../../Plugins/ThemeOneDarkPlugin"),
        .package(path: "../../Plugins/ThemeOrchardPlugin"),
        .package(path: "../../Plugins/ThemeRiverPlugin"),
        .package(path: "../../Plugins/ThemeSkyPlugin"),
        .package(path: "../../Plugins/ThemeSpringPlugin"),
        .package(path: "../../Plugins/ThemeStatusBarPlugin"),
        .package(path: "../../Plugins/ThemeSummerPlugin"),
        .package(path: "../../Plugins/ThemeVoidPlugin"),
        .package(path: "../../Plugins/ThemeVscodeDarkPlugin"),
        .package(path: "../../Plugins/ThemeVscodeLightPlugin"),
        .package(path: "../../Plugins/ThemeWinterPlugin"),
        .package(path: "../../Plugins/ToolCallLoopDetectionPlugin"),
        .package(path: "../../Plugins/VerbosityPlugin"),
        .package(path: "../../Plugins/VueEditorPlugin"),
        .package(path: "../../Plugins/WebFetchPlugin"),
        .package(path: "../../Plugins/WebSearchPlugin"),
        .package(path: "../../Plugins/WindowPersistencePlugin"),
    ],
    targets: [
        .target(
            name: "LumiPluginRegistry",
            dependencies: [
                "LumiCoreKit",
                "AgentAvailableToolsPlugin",
                "AgentContextSyncPlugin",
                "AgentCoreToolsPlugin",
                "AgentDelayMessagePlugin",
                "AgentGitHubToolsPlugin",
                "ConversationLanguagePlugin",
                "AgentMCPToolsPlugin",
                "MessageRendererPlugin",
                "AgentRAGPlugin",
                "AgentRulesPlugin",
                "AgentTurnNotificationPlugin",
                "AppIconDesignerPlugin",
                "AppLoadedPluginsPlugin",
                "AppManagerPlugin",
                "AppStoreConnectPlugin",
                "AppUpdateStatusBarPlugin",
                "AskUserPlugin",
                "AutoTaskPlugin",
                "BrewManagerPlugin",
                "BrowserPlugin",
                "BrowserAgentPlugin",
                "CSSEditorPlugin",
                "CaffeinatePlugin",
                "ChatAttachmentPlugin",
                "ChatInputPlugin",
                "MessageListPlugin",
                "SendQueuePlugin",
                "MessageSenderPlugin",
                "ToolExecutorPlugin",
                "TurnLifecyclePlugin",
                "ChatModePlugin",
                "ChatPanelPlugin",
                "ChatPendingMessagesPlugin",
                "ChatSubmitPlugin",
                "ClipboardManagerPlugin",
                "CodeReviewPlugin",
                "ConversationListPlugin",
                "ConversationNewPlugin",
                "ConversationTimelinePlugin",
                "ConversationTitlePlugin",
                "DatabaseManagerPlugin",
                "DeviceInfoPlugin",
                "DiskManagerPlugin",
                "DockerManagerPlugin",
                "EditorBottomCallHierarchyPlugin",
                "EditorBottomProblemsPlugin",
                "EditorBottomReferencesPlugin",
                "EditorBottomSearchPlugin",
                "EditorBottomSymbolsPlugin",
                "EditorBottomTerminalPlugin",
                "EditorBreadcrumbPlugin",
                "EditorCallHierarchyRailPlugin",
                "EditorChatIntegrationPlugin",
                "EditorLSPContextCommandsPlugin",
                "EditorOutlineRailPlugin",
                "EditorPanelPlugin",
                "EditorPreviewPlugin",
                "EditorRailFileTreePlugin",
                "EditorRailProblemsPlugin",
                "EditorRailReferencesPlugin",
                "EditorRailWorkspaceSearchPlugin",
                "EditorRailWorkspaceSymbolsPlugin",
                "EditorStickySymbolBarPlugin",
                "EditorSwiftKeywordHoverPlugin",
                "EditorTabStripPlugin",
                "EditorXcodePlugin",
                "FileLogPlugin",
                "FontConfigPlugin",
                "GitPlugin",
                "GitHubCLIDetectPlugin",
                "GitHubInsightPlugin",
                "GoEditorPlugin",
                "HTMLEditorPlugin",
                "HistoryDBStatusBarPlugin",
                "HostsManagerPlugin",
                "IdleTimePlugin",
                "InputPlugin",
                "JSEditorPlugin",
                "LLMAvailabilityPlugin",
                "LLMProviderAiRouterPlugin",
                "LLMProviderAliyunPlugin",
                "LLMProviderAnthropicPlugin",
                "LLMProviderCodexPlugin",
                "LLMProviderDeepSeekPlugin",
                "LLMProviderFeifeimiaoPlugin",
                "LLMProviderFlyMuxPlugin",
                "LLMProviderFreeModelPlugin",
                "LLMProviderHappyCodePlugin",
                "LLMProviderHyperAPIPlugin",
                "LLMProviderLPgptPlugin",
                "LLMProviderMLXPlugin",
                "LLMProviderMegaLLMPlugin",
                "LLMProviderOpenAIPlugin",
                "LLMProviderOpenRouterPlugin",
                "LLMProviderXiaomiPlugin",
                "LLMProviderXybbzPlugin",
                "LLMProviderZhipuPlugin",
                "LSPCallHierarchyEditorPlugin",
                "LSPCodeActionEditorPlugin",
                "LSPDocumentColorEditorPlugin",
                "LSPDocumentHighlightEditorPlugin",
                "LSPDocumentLinkEditorPlugin",
                "LSPFoldingRangeEditorPlugin",
                "LSPInlayHintEditorPlugin",
                "LSPRealtimeSignalsEditorPlugin",
                "LSPSelectionRangeEditorPlugin",
                "LSPServiceEditorPlugin",
                "LSPSheetsEditorPlugin",
                "LSPSignatureHelpEditorPlugin",
                "LSPToolbarEditorPlugin",
                "LSPWorkspaceSymbolEditorPlugin",
                "LayoutPlugin",
                "MarkdownEditorPlugin",
                "MemoryPlugin",
                "MenuBarManagerPlugin",
                "ModelPreferencePlugin",
                "ModelSelectorPlugin",
                "MultiAgentPlugin",
                "MultiCursorCommandsEditorPlugin",
                "NettoPlugin",
                "NetworkManagerPlugin",
                "OnboardingPlugin",
                "OpenInAntigravityPlugin",
                "OpenInCursorPlugin",
                "OpenInFinderPlugin",
                "OpenInGitHubDesktopPlugin",
                "OpenInGitOKPlugin",
                "OpenInXcodePlugin",
                "OpenRemotePlugin",
                "PortManagerPlugin",
                "ProjectIssueScannerPlugin",
                "ProjectOverviewPlugin",
                "ProjectsPlugin",
                "QuickFileSearchPlugin",
                "QuickLauncherPlugin",
                "RClickPlugin",
                "RegistryManagerPlugin",
                "RequestLogPlugin",
                "SampleDecorationEditorPlugin",
                "SampleInsightsEditorPlugin",
                "ScreenshotPlugin",
                "ShowImagePlugin",
                "SkillPlugin",
                "SwiftPrimitiveTypesEditorPlugin",
                "SwiftSelectionCodeActionEditorPlugin",
                "TerminalPlugin",
                "TextActionsPlugin",
                "ThemeAuroraPlugin",
                "ThemeAutumnPlugin",
                "ThemeDraculaPlugin",
                "ThemeGithubPlugin",
                "ThemeLumiPlugin",
                "ThemeMidnightPlugin",
                "ThemeMountainPlugin",
                "ThemeNebulaPlugin",
                "ThemeOneDarkPlugin",
                "ThemeOrchardPlugin",
                "ThemeRiverPlugin",
                "ThemeSkyPlugin",
                "ThemeSpringPlugin",
                "ThemeStatusBarPlugin",
                "ThemeSummerPlugin",
                "ThemeVoidPlugin",
                "ThemeVscodeDarkPlugin",
                "ThemeVscodeLightPlugin",
                "ThemeWinterPlugin",
                "ToolCallLoopDetectionPlugin",
                "VerbosityPlugin",
                "VueEditorPlugin",
                "WebFetchPlugin",
                "WebSearchPlugin",
                "WindowPersistencePlugin",
            ],
            path: "Sources"
        ),
    ]
)
