import Foundation

/// Resource bundle accessor for KernelLumi.
///
/// Generated by SPM when resources are processed.
public enum KernelLumiResources {
    public static var bundle: Bundle {
        Bundle.module
    }
}
